// ==============================================================
// RTL generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
// Version: 2018.2
// Copyright (C) 1986-2018 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

`timescale 1 ns / 1 ps 

module ConvolutionInputGene_3 (
        ap_clk,
        ap_rst,
        ap_start,
        ap_done,
        ap_continue,
        ap_idle,
        ap_ready,
        in_V_V_dout,
        in_V_V_empty_n,
        in_V_V_read,
        out_V_V_din,
        out_V_V_full_n,
        out_V_V_write,
        numReps_dout,
        numReps_empty_n,
        numReps_read,
        numReps_out_din,
        numReps_out_full_n,
        numReps_out_write
);

parameter    ap_ST_fsm_state1 = 4'd1;
parameter    ap_ST_fsm_state2 = 4'd2;
parameter    ap_ST_fsm_pp0_stage0 = 4'd4;
parameter    ap_ST_fsm_state9 = 4'd8;

input   ap_clk;
input   ap_rst;
input   ap_start;
output   ap_done;
input   ap_continue;
output   ap_idle;
output   ap_ready;
input  [31:0] in_V_V_dout;
input   in_V_V_empty_n;
output   in_V_V_read;
output  [31:0] out_V_V_din;
input   out_V_V_full_n;
output   out_V_V_write;
input  [31:0] numReps_dout;
input   numReps_empty_n;
output   numReps_read;
output  [31:0] numReps_out_din;
input   numReps_out_full_n;
output   numReps_out_write;

reg ap_done;
reg ap_idle;
reg ap_ready;
reg in_V_V_read;
reg out_V_V_write;
reg numReps_read;
reg numReps_out_write;

reg    ap_done_reg;
(* fsm_encoding = "none" *) reg   [3:0] ap_CS_fsm;
wire    ap_CS_fsm_state1;
reg    in_V_V_blk_n;
reg    ap_enable_reg_pp0_iter2;
wire    ap_block_pp0_stage0;
reg   [0:0] tmp_i_2861_reg_1001;
reg   [0:0] or_cond_i_reg_1039;
reg    out_V_V_blk_n;
reg    ap_enable_reg_pp0_iter5;
reg   [0:0] tmp_i_2861_reg_1001_pp0_iter4_reg;
reg   [0:0] tmp_128_i_reg_1005;
reg   [0:0] tmp_128_i_reg_1005_pp0_iter4_reg;
reg    numReps_blk_n;
reg    numReps_out_blk_n;
reg   [39:0] indvar_flatten_reg_291;
reg   [7:0] i_i_reg_302;
reg   [31:0] reg_380;
wire    ap_CS_fsm_pp0_stage0;
reg    ap_enable_reg_pp0_iter1;
wire    ap_block_state3_pp0_stage0_iter0;
wire    ap_block_state4_pp0_stage0_iter1;
reg    ap_predicate_op160_read_state5;
reg    ap_block_state5_pp0_stage0_iter2;
wire    ap_block_state6_pp0_stage0_iter3;
wire    ap_block_state7_pp0_stage0_iter4;
reg    ap_predicate_op224_write_state8;
reg    ap_block_state8_pp0_stage0_iter5;
reg    ap_block_pp0_stage0_11001;
wire   [0:0] tmp_i_2861_fu_489_p2;
wire   [0:0] or_cond_i_fu_661_p2;
reg   [31:0] reg_384;
reg   [31:0] numReps_read_reg_971;
reg    ap_block_state1;
wire   [39:0] bound_fu_434_p2;
reg   [39:0] bound_reg_977;
wire    ap_CS_fsm_state2;
wire   [0:0] exitcond_flatten_fu_440_p2;
reg   [0:0] exitcond_flatten_reg_982;
wire   [39:0] indvar_flatten_next_fu_445_p2;
reg    ap_enable_reg_pp0_iter0;
wire   [0:0] tmp_i_fu_451_p2;
reg   [0:0] tmp_i_reg_991;
wire   [7:0] i_fu_463_p3;
reg   [0:0] tmp_i_2861_reg_1001_pp0_iter2_reg;
reg   [0:0] tmp_i_2861_reg_1001_pp0_iter3_reg;
wire   [0:0] tmp_128_i_fu_498_p2;
reg   [0:0] tmp_128_i_reg_1005_pp0_iter2_reg;
reg   [0:0] tmp_128_i_reg_1005_pp0_iter3_reg;
reg   [31:0] count_simd_3_load_reg_1009;
wire   [1:0] tmp_2992_fu_516_p1;
reg   [1:0] tmp_2992_reg_1014;
wire   [28:0] tmp_129_i_fu_534_p2;
reg   [28:0] tmp_129_i_reg_1019;
wire   [0:0] tmp_133_i_fu_546_p2;
wire   [0:0] tmp_135_i_fu_563_p2;
wire   [0:0] tmp_137_i_fu_574_p2;
reg   [0:0] or_cond_i_reg_1039_pp0_iter2_reg;
wire   [0:0] tmp_143_i_fu_362_p2;
reg   [0:0] tmp_143_i_reg_1043;
wire   [0:0] tmp_134_i_fu_368_p2;
reg   [0:0] tmp_134_i_reg_1048;
wire   [31:0] current_line_in_bloc_fu_769_p2;
reg   [31:0] current_line_in_bloc_reg_1052;
wire   [1:0] current_block_read_9_fu_780_p2;
reg   [1:0] current_block_read_9_reg_1057;
reg   [1:0] current_block_read_9_reg_1057_pp0_iter3_reg;
wire   [1:0] tmp_2996_fu_793_p1;
reg   [1:0] tmp_2996_reg_1062;
reg   [4:0] inputBuf_0_V_addr_4_reg_1066;
reg   [4:0] inputBuf_1_V_addr_4_reg_1071;
reg   [4:0] inputBuf_2_V_addr_4_reg_1076;
reg   [4:0] inputBuf_3_V_addr_4_reg_1081;
wire   [1:0] tmp_2991_fu_840_p1;
reg   [1:0] tmp_2991_reg_1086;
reg   [4:0] inputBuf_0_V_addr_reg_1090;
reg   [4:0] inputBuf_1_V_addr_reg_1095;
reg   [4:0] inputBuf_2_V_addr_reg_1100;
reg   [4:0] inputBuf_3_V_addr_reg_1105;
wire   [31:0] outElem_V_fu_876_p6;
reg   [31:0] outElem_V_reg_1130;
reg    ap_block_pp0_stage0_subdone;
reg    ap_condition_pp0_exit_iter0_state3;
reg    ap_enable_reg_pp0_iter3;
reg    ap_enable_reg_pp0_iter4;
wire   [4:0] inputBuf_0_V_address0;
reg    inputBuf_0_V_ce0;
wire   [31:0] inputBuf_0_V_q0;
reg   [4:0] inputBuf_0_V_address1;
reg    inputBuf_0_V_ce1;
reg    inputBuf_0_V_we1;
wire   [4:0] inputBuf_1_V_address0;
reg    inputBuf_1_V_ce0;
wire   [31:0] inputBuf_1_V_q0;
reg   [4:0] inputBuf_1_V_address1;
reg    inputBuf_1_V_ce1;
reg    inputBuf_1_V_we1;
wire   [4:0] inputBuf_2_V_address0;
reg    inputBuf_2_V_ce0;
wire   [31:0] inputBuf_2_V_q0;
reg   [4:0] inputBuf_2_V_address1;
reg    inputBuf_2_V_ce1;
reg    inputBuf_2_V_we1;
wire   [4:0] inputBuf_3_V_address0;
reg    inputBuf_3_V_ce0;
wire   [31:0] inputBuf_3_V_q0;
reg   [4:0] inputBuf_3_V_address1;
reg    inputBuf_3_V_ce1;
reg    inputBuf_3_V_we1;
wire   [63:0] tmp_142_i_fu_785_p1;
wire   [63:0] tmp_127_i_fu_832_p1;
wire   [63:0] tmp_132_i_fu_869_p1;
reg    ap_block_pp0_stage0_01001;
reg   [31:0] read_block_4_fu_96;
wire   [31:0] read_block_1_i_mid2_fu_477_p3;
wire   [31:0] read_block_3_cast_i_fu_689_p1;
wire   [31:0] read_block_fu_747_p2;
reg   [31:0] ofm_y_1_i_fu_100;
wire   [31:0] p_ofm_y_5_i_fu_628_p3;
wire   [0:0] tmp_138_i_fu_594_p2;
reg   [31:0] ofm_x_3_fu_104;
wire   [31:0] ofm_x_fu_588_p2;
reg   [31:0] k_y_3_fu_108;
wire   [31:0] k_y_fu_520_p2;
reg   [31:0] inp_3_fu_112;
wire   [31:0] p_inp_1_i_fu_620_p3;
wire   [31:0] inp_fu_731_p2;
reg   [31:0] k_x_3_fu_116;
wire   [31:0] k_x_fu_557_p2;
reg   [31:0] count_simd_3_fu_120;
wire   [31:0] count_simd_fu_540_p2;
reg   [31:0] current_block_write_13_fu_124;
wire   [31:0] current_block_write_16_fu_820_p3;
wire   [31:0] current_block_write_9_2858_fu_856_p3;
reg   [31:0] current_line_4_fu_128;
wire   [31:0] current_line_3_i_fu_673_p3;
wire   [31:0] grp_fu_356_p2;
reg   [31:0] counter_internal_blo_fu_132;
wire   [31:0] p_i_fu_718_p3;
wire   [38:0] tmp_s_fu_412_p3;
wire   [35:0] tmp_16_fu_423_p3;
wire   [39:0] p_shl_fu_419_p1;
wire   [39:0] p_shl2_fu_430_p1;
wire   [7:0] i_i_op_fu_457_p2;
wire   [28:0] tmp_2995_fu_530_p1;
wire   [28:0] tmp_2994_fu_526_p1;
wire   [0:0] tmp_139_i_fu_614_p2;
wire   [31:0] ofm_y_fu_608_p2;
wire   [0:0] tmp_140_i_fu_649_p2;
wire   [0:0] tmp_141_i_fu_655_p2;
wire   [1:0] tmp_2990_fu_485_p1;
wire   [1:0] read_block_4_cast_fu_667_p2;
wire   [1:0] read_block_3_fu_681_p3;
wire   [31:0] counter_internal_blo_12_fu_706_p2;
wire   [0:0] tmp_145_i_fu_712_p2;
wire   [31:0] tmp_131_i_fu_762_p3;
wire   [1:0] tmp_2993_fu_758_p1;
wire   [1:0] tmp_fu_774_p2;
wire   [31:0] current_block_write_14_fu_800_p2;
wire   [0:0] tmp_144_i_fu_806_p2;
wire   [31:0] current_block_write_15_fu_812_p3;
wire   [31:0] current_block_write_fu_844_p2;
wire   [0:0] tmp_136_i_fu_850_p2;
wire    ap_CS_fsm_state9;
reg   [3:0] ap_NS_fsm;
reg    ap_idle_pp0;
wire    ap_enable_pp0;
reg    ap_condition_458;
reg    ap_condition_470;
reg    ap_condition_481;
reg    ap_condition_492;

// power-on initialization
initial begin
#0 ap_done_reg = 1'b0;
#0 ap_CS_fsm = 4'd1;
#0 ap_enable_reg_pp0_iter2 = 1'b0;
#0 ap_enable_reg_pp0_iter5 = 1'b0;
#0 ap_enable_reg_pp0_iter1 = 1'b0;
#0 ap_enable_reg_pp0_iter0 = 1'b0;
#0 ap_enable_reg_pp0_iter3 = 1'b0;
#0 ap_enable_reg_pp0_iter4 = 1'b0;
end

ConvolutionInputGJfO #(
    .DataWidth( 32 ),
    .AddressRange( 24 ),
    .AddressWidth( 5 ))
inputBuf_0_V_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(inputBuf_0_V_address0),
    .ce0(inputBuf_0_V_ce0),
    .q0(inputBuf_0_V_q0),
    .address1(inputBuf_0_V_address1),
    .ce1(inputBuf_0_V_ce1),
    .we1(inputBuf_0_V_we1),
    .d1(reg_384)
);

ConvolutionInputGJfO #(
    .DataWidth( 32 ),
    .AddressRange( 24 ),
    .AddressWidth( 5 ))
inputBuf_1_V_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(inputBuf_1_V_address0),
    .ce0(inputBuf_1_V_ce0),
    .q0(inputBuf_1_V_q0),
    .address1(inputBuf_1_V_address1),
    .ce1(inputBuf_1_V_ce1),
    .we1(inputBuf_1_V_we1),
    .d1(reg_384)
);

ConvolutionInputGJfO #(
    .DataWidth( 32 ),
    .AddressRange( 24 ),
    .AddressWidth( 5 ))
inputBuf_2_V_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(inputBuf_2_V_address0),
    .ce0(inputBuf_2_V_ce0),
    .q0(inputBuf_2_V_q0),
    .address1(inputBuf_2_V_address1),
    .ce1(inputBuf_2_V_ce1),
    .we1(inputBuf_2_V_we1),
    .d1(reg_384)
);

ConvolutionInputGJfO #(
    .DataWidth( 32 ),
    .AddressRange( 24 ),
    .AddressWidth( 5 ))
inputBuf_3_V_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(inputBuf_3_V_address0),
    .ce0(inputBuf_3_V_ce0),
    .q0(inputBuf_3_V_q0),
    .address1(inputBuf_3_V_address1),
    .ce1(inputBuf_3_V_ce1),
    .we1(inputBuf_3_V_we1),
    .d1(reg_384)
);

BlackBoxJam_mux_4pcA #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 32 ),
    .din1_WIDTH( 32 ),
    .din2_WIDTH( 32 ),
    .din3_WIDTH( 32 ),
    .din4_WIDTH( 2 ),
    .dout_WIDTH( 32 ))
BlackBoxJam_mux_4pcA_U339(
    .din0(inputBuf_0_V_q0),
    .din1(inputBuf_1_V_q0),
    .din2(inputBuf_2_V_q0),
    .din3(inputBuf_3_V_q0),
    .din4(current_block_read_9_reg_1057_pp0_iter3_reg),
    .dout(outElem_V_fu_876_p6)
);

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_state1;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_done_reg <= 1'b0;
    end else begin
        if ((ap_continue == 1'b1)) begin
            ap_done_reg <= 1'b0;
        end else if ((1'b1 == ap_CS_fsm_state9)) begin
            ap_done_reg <= 1'b1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter0 <= 1'b0;
    end else begin
        if (((1'b0 == ap_block_pp0_stage0_subdone) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b1 == ap_condition_pp0_exit_iter0_state3))) begin
            ap_enable_reg_pp0_iter0 <= 1'b0;
        end else if ((1'b1 == ap_CS_fsm_state2)) begin
            ap_enable_reg_pp0_iter0 <= 1'b1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter1 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            if ((1'b1 == ap_condition_pp0_exit_iter0_state3)) begin
                ap_enable_reg_pp0_iter1 <= (1'b1 ^ ap_condition_pp0_exit_iter0_state3);
            end else if ((1'b1 == 1'b1)) begin
                ap_enable_reg_pp0_iter1 <= ap_enable_reg_pp0_iter0;
            end
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter2 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter2 <= ap_enable_reg_pp0_iter1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter3 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter3 <= ap_enable_reg_pp0_iter2;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter4 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter4 <= ap_enable_reg_pp0_iter3;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter5 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter5 <= ap_enable_reg_pp0_iter4;
        end else if ((1'b1 == ap_CS_fsm_state2)) begin
            ap_enable_reg_pp0_iter5 <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((tmp_133_i_fu_546_p2 == 1'd0) & (tmp_i_2861_fu_489_p2 == 1'd0) & (tmp_128_i_fu_498_p2 == 1'd1) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        count_simd_3_fu_120 <= count_simd_fu_540_p2;
    end else if ((((tmp_135_i_fu_563_p2 == 1'd0) & (tmp_i_2861_fu_489_p2 == 1'd0) & (tmp_133_i_fu_546_p2 == 1'd1) & (tmp_128_i_fu_498_p2 == 1'd1) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001)) | ((tmp_137_i_fu_574_p2 == 1'd0) & (tmp_i_2861_fu_489_p2 == 1'd0) & (tmp_135_i_fu_563_p2 == 1'd1) & (tmp_133_i_fu_546_p2 == 1'd1) & (tmp_128_i_fu_498_p2 == 1'd1) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001)) | ((tmp_138_i_fu_594_p2 == 1'd0) & (tmp_i_2861_fu_489_p2 == 1'd0) & (tmp_137_i_fu_574_p2 == 1'd1) & (tmp_135_i_fu_563_p2 == 1'd1) & (tmp_133_i_fu_546_p2 == 1'd1) & (tmp_128_i_fu_498_p2 == 1'd1) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001)) | ((tmp_i_2861_fu_489_p2 == 1'd0) & (tmp_138_i_fu_594_p2 == 1'd1) & (tmp_137_i_fu_574_p2 == 1'd1) & (tmp_135_i_fu_563_p2 == 1'd1) & (tmp_133_i_fu_546_p2 == 1'd1) & (tmp_128_i_fu_498_p2 == 1'd1) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001)) | (~((ap_start == 1'b0) | (numReps_out_full_n == 1'b0) | (numReps_empty_n == 1'b0) | (ap_done_reg == 1'b1)) & (1'b1 == ap_CS_fsm_state1)))) begin
        count_simd_3_fu_120 <= 32'd0;
    end
end

always @ (posedge ap_clk) begin
    if (((tmp_i_2861_fu_489_p2 == 1'd0) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        counter_internal_blo_fu_132 <= p_i_fu_718_p3;
    end else if ((((tmp_134_i_fu_368_p2 == 1'd1) & (tmp_i_2861_fu_489_p2 == 1'd1) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001)) | (~((ap_start == 1'b0) | (numReps_out_full_n == 1'b0) | (numReps_empty_n == 1'b0) | (ap_done_reg == 1'b1)) & (1'b1 == ap_CS_fsm_state1)))) begin
        counter_internal_blo_fu_132 <= 32'd0;
    end
end

always @ (posedge ap_clk) begin
    if (((tmp_134_i_reg_1048 == 1'd1) & (tmp_i_2861_reg_1001 == 1'd1) & (ap_enable_reg_pp0_iter2 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        current_block_write_13_fu_124 <= current_block_write_9_2858_fu_856_p3;
    end else if (((or_cond_i_reg_1039 == 1'd1) & (tmp_i_2861_reg_1001 == 1'd0) & (ap_enable_reg_pp0_iter2 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        current_block_write_13_fu_124 <= current_block_write_16_fu_820_p3;
    end else if ((~((ap_start == 1'b0) | (numReps_out_full_n == 1'b0) | (numReps_empty_n == 1'b0) | (ap_done_reg == 1'b1)) & (1'b1 == ap_CS_fsm_state1))) begin
        current_block_write_13_fu_124 <= 32'd0;
    end
end

always @ (posedge ap_clk) begin
    if (((tmp_134_i_fu_368_p2 == 1'd0) & (tmp_i_2861_fu_489_p2 == 1'd1) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        current_line_4_fu_128 <= grp_fu_356_p2;
    end else if (((tmp_i_2861_fu_489_p2 == 1'd0) & (or_cond_i_fu_661_p2 == 1'd1) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        current_line_4_fu_128 <= current_line_3_i_fu_673_p3;
    end else if ((((tmp_134_i_fu_368_p2 == 1'd1) & (tmp_i_2861_fu_489_p2 == 1'd1) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001)) | (~((ap_start == 1'b0) | (numReps_out_full_n == 1'b0) | (numReps_empty_n == 1'b0) | (ap_done_reg == 1'b1)) & (1'b1 == ap_CS_fsm_state1)))) begin
        current_line_4_fu_128 <= 32'd0;
    end
end

always @ (posedge ap_clk) begin
    if (((exitcond_flatten_fu_440_p2 == 1'd0) & (1'b1 == ap_CS_fsm_pp0_stage0) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        i_i_reg_302 <= i_fu_463_p3;
    end else if ((1'b1 == ap_CS_fsm_state2)) begin
        i_i_reg_302 <= 8'd0;
    end
end

always @ (posedge ap_clk) begin
    if (((exitcond_flatten_fu_440_p2 == 1'd0) & (1'b1 == ap_CS_fsm_pp0_stage0) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        indvar_flatten_reg_291 <= indvar_flatten_next_fu_445_p2;
    end else if ((1'b1 == ap_CS_fsm_state2)) begin
        indvar_flatten_reg_291 <= 40'd0;
    end
end

always @ (posedge ap_clk) begin
    if (((tmp_i_2861_fu_489_p2 == 1'd1) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        inp_3_fu_112 <= inp_fu_731_p2;
    end else if (((tmp_i_2861_fu_489_p2 == 1'd0) & (tmp_138_i_fu_594_p2 == 1'd1) & (tmp_137_i_fu_574_p2 == 1'd1) & (tmp_135_i_fu_563_p2 == 1'd1) & (tmp_133_i_fu_546_p2 == 1'd1) & (tmp_128_i_fu_498_p2 == 1'd1) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        inp_3_fu_112 <= p_inp_1_i_fu_620_p3;
    end else if ((~((ap_start == 1'b0) | (numReps_out_full_n == 1'b0) | (numReps_empty_n == 1'b0) | (ap_done_reg == 1'b1)) & (1'b1 == ap_CS_fsm_state1))) begin
        inp_3_fu_112 <= 32'd0;
    end
end

always @ (posedge ap_clk) begin
    if (((tmp_135_i_fu_563_p2 == 1'd0) & (tmp_i_2861_fu_489_p2 == 1'd0) & (tmp_133_i_fu_546_p2 == 1'd1) & (tmp_128_i_fu_498_p2 == 1'd1) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        k_x_3_fu_116 <= k_x_fu_557_p2;
    end else if ((((tmp_137_i_fu_574_p2 == 1'd0) & (tmp_i_2861_fu_489_p2 == 1'd0) & (tmp_135_i_fu_563_p2 == 1'd1) & (tmp_133_i_fu_546_p2 == 1'd1) & (tmp_128_i_fu_498_p2 == 1'd1) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001)) | ((tmp_138_i_fu_594_p2 == 1'd0) & (tmp_i_2861_fu_489_p2 == 1'd0) & (tmp_137_i_fu_574_p2 == 1'd1) & (tmp_135_i_fu_563_p2 == 1'd1) & (tmp_133_i_fu_546_p2 == 1'd1) & (tmp_128_i_fu_498_p2 == 1'd1) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001)) | ((tmp_i_2861_fu_489_p2 == 1'd0) & (tmp_138_i_fu_594_p2 == 1'd1) & (tmp_137_i_fu_574_p2 == 1'd1) & (tmp_135_i_fu_563_p2 == 1'd1) & (tmp_133_i_fu_546_p2 == 1'd1) & (tmp_128_i_fu_498_p2 == 1'd1) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001)) | (~((ap_start == 1'b0) | (numReps_out_full_n == 1'b0) | (numReps_empty_n == 1'b0) | (ap_done_reg == 1'b1)) & (1'b1 == ap_CS_fsm_state1)))) begin
        k_x_3_fu_116 <= 32'd0;
    end
end

always @ (posedge ap_clk) begin
    if (((tmp_137_i_fu_574_p2 == 1'd0) & (tmp_i_2861_fu_489_p2 == 1'd0) & (tmp_135_i_fu_563_p2 == 1'd1) & (tmp_133_i_fu_546_p2 == 1'd1) & (tmp_128_i_fu_498_p2 == 1'd1) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        k_y_3_fu_108 <= k_y_fu_520_p2;
    end else if ((((tmp_i_2861_fu_489_p2 == 1'd0) & (tmp_137_i_fu_574_p2 == 1'd1) & (tmp_135_i_fu_563_p2 == 1'd1) & (tmp_133_i_fu_546_p2 == 1'd1) & (tmp_128_i_fu_498_p2 == 1'd1) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001)) | (~((ap_start == 1'b0) | (numReps_out_full_n == 1'b0) | (numReps_empty_n == 1'b0) | (ap_done_reg == 1'b1)) & (1'b1 == ap_CS_fsm_state1)))) begin
        k_y_3_fu_108 <= 32'd0;
    end
end

always @ (posedge ap_clk) begin
    if (((tmp_138_i_fu_594_p2 == 1'd0) & (tmp_i_2861_fu_489_p2 == 1'd0) & (tmp_137_i_fu_574_p2 == 1'd1) & (tmp_135_i_fu_563_p2 == 1'd1) & (tmp_133_i_fu_546_p2 == 1'd1) & (tmp_128_i_fu_498_p2 == 1'd1) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        ofm_x_3_fu_104 <= ofm_x_fu_588_p2;
    end else if ((((tmp_i_2861_fu_489_p2 == 1'd0) & (tmp_138_i_fu_594_p2 == 1'd1) & (tmp_137_i_fu_574_p2 == 1'd1) & (tmp_135_i_fu_563_p2 == 1'd1) & (tmp_133_i_fu_546_p2 == 1'd1) & (tmp_128_i_fu_498_p2 == 1'd1) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001)) | (~((ap_start == 1'b0) | (numReps_out_full_n == 1'b0) | (numReps_empty_n == 1'b0) | (ap_done_reg == 1'b1)) & (1'b1 == ap_CS_fsm_state1)))) begin
        ofm_x_3_fu_104 <= 32'd0;
    end
end

always @ (posedge ap_clk) begin
    if (((tmp_i_2861_fu_489_p2 == 1'd0) & (tmp_138_i_fu_594_p2 == 1'd1) & (tmp_137_i_fu_574_p2 == 1'd1) & (tmp_135_i_fu_563_p2 == 1'd1) & (tmp_133_i_fu_546_p2 == 1'd1) & (tmp_128_i_fu_498_p2 == 1'd1) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        ofm_y_1_i_fu_100 <= p_ofm_y_5_i_fu_628_p3;
    end else if ((~((ap_start == 1'b0) | (numReps_out_full_n == 1'b0) | (numReps_empty_n == 1'b0) | (ap_done_reg == 1'b1)) & (1'b1 == ap_CS_fsm_state1))) begin
        ofm_y_1_i_fu_100 <= 32'd0;
    end
end

always @ (posedge ap_clk) begin
    if (((tmp_134_i_fu_368_p2 == 1'd1) & (tmp_i_2861_fu_489_p2 == 1'd1) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        read_block_4_fu_96 <= read_block_fu_747_p2;
    end else if (((tmp_i_2861_fu_489_p2 == 1'd0) & (or_cond_i_fu_661_p2 == 1'd1) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        read_block_4_fu_96 <= read_block_3_cast_i_fu_689_p1;
    end else if ((((tmp_134_i_fu_368_p2 == 1'd0) & (tmp_i_2861_fu_489_p2 == 1'd1) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001)) | ((or_cond_i_fu_661_p2 == 1'd0) & (tmp_i_2861_fu_489_p2 == 1'd0) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001)))) begin
        read_block_4_fu_96 <= read_block_1_i_mid2_fu_477_p3;
    end else if ((~((ap_start == 1'b0) | (numReps_out_full_n == 1'b0) | (numReps_empty_n == 1'b0) | (ap_done_reg == 1'b1)) & (1'b1 == ap_CS_fsm_state1))) begin
        read_block_4_fu_96 <= 32'd0;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state2)) begin
        bound_reg_977[39 : 4] <= bound_fu_434_p2[39 : 4];
    end
end

always @ (posedge ap_clk) begin
    if (((tmp_i_2861_fu_489_p2 == 1'd0) & (tmp_128_i_fu_498_p2 == 1'd1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        count_simd_3_load_reg_1009 <= count_simd_3_fu_120;
        tmp_129_i_reg_1019 <= tmp_129_i_fu_534_p2;
        tmp_2992_reg_1014 <= tmp_2992_fu_516_p1;
    end
end

always @ (posedge ap_clk) begin
    if (((tmp_128_i_reg_1005 == 1'd1) & (tmp_i_2861_reg_1001 == 1'd0) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        current_block_read_9_reg_1057 <= current_block_read_9_fu_780_p2;
        current_line_in_bloc_reg_1052 <= current_line_in_bloc_fu_769_p2;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b0 == ap_block_pp0_stage0_11001)) begin
        current_block_read_9_reg_1057_pp0_iter3_reg <= current_block_read_9_reg_1057;
        or_cond_i_reg_1039_pp0_iter2_reg <= or_cond_i_reg_1039;
        tmp_128_i_reg_1005_pp0_iter2_reg <= tmp_128_i_reg_1005;
        tmp_128_i_reg_1005_pp0_iter3_reg <= tmp_128_i_reg_1005_pp0_iter2_reg;
        tmp_128_i_reg_1005_pp0_iter4_reg <= tmp_128_i_reg_1005_pp0_iter3_reg;
        tmp_i_2861_reg_1001_pp0_iter2_reg <= tmp_i_2861_reg_1001;
        tmp_i_2861_reg_1001_pp0_iter3_reg <= tmp_i_2861_reg_1001_pp0_iter2_reg;
        tmp_i_2861_reg_1001_pp0_iter4_reg <= tmp_i_2861_reg_1001_pp0_iter3_reg;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        exitcond_flatten_reg_982 <= exitcond_flatten_fu_440_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((ap_predicate_op160_read_state5 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        inputBuf_0_V_addr_4_reg_1066 <= tmp_142_i_fu_785_p1;
        inputBuf_1_V_addr_4_reg_1071 <= tmp_142_i_fu_785_p1;
        inputBuf_2_V_addr_4_reg_1076 <= tmp_142_i_fu_785_p1;
        inputBuf_3_V_addr_4_reg_1081 <= tmp_142_i_fu_785_p1;
        tmp_2996_reg_1062 <= tmp_2996_fu_793_p1;
    end
end

always @ (posedge ap_clk) begin
    if (((tmp_i_2861_reg_1001 == 1'd1) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        inputBuf_0_V_addr_reg_1090 <= tmp_127_i_fu_832_p1;
        inputBuf_1_V_addr_reg_1095 <= tmp_127_i_fu_832_p1;
        inputBuf_2_V_addr_reg_1100 <= tmp_127_i_fu_832_p1;
        inputBuf_3_V_addr_reg_1105 <= tmp_127_i_fu_832_p1;
        tmp_2991_reg_1086 <= tmp_2991_fu_840_p1;
    end
end

always @ (posedge ap_clk) begin
    if ((~((ap_start == 1'b0) | (numReps_out_full_n == 1'b0) | (numReps_empty_n == 1'b0) | (ap_done_reg == 1'b1)) & (1'b1 == ap_CS_fsm_state1))) begin
        numReps_read_reg_971 <= numReps_dout;
    end
end

always @ (posedge ap_clk) begin
    if (((tmp_i_2861_fu_489_p2 == 1'd0) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        or_cond_i_reg_1039 <= or_cond_i_fu_661_p2;
        tmp_128_i_reg_1005 <= tmp_128_i_fu_498_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((tmp_i_2861_reg_1001_pp0_iter3_reg == 1'd0) & (tmp_128_i_reg_1005_pp0_iter3_reg == 1'd1) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        outElem_V_reg_1130 <= outElem_V_fu_876_p6;
    end
end

always @ (posedge ap_clk) begin
    if ((((tmp_i_2861_fu_489_p2 == 1'd1) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001)) | ((tmp_i_2861_fu_489_p2 == 1'd0) & (or_cond_i_fu_661_p2 == 1'd1) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001)))) begin
        reg_380 <= current_line_4_fu_128;
    end
end

always @ (posedge ap_clk) begin
    if ((((ap_predicate_op160_read_state5 == 1'b1) & (ap_enable_reg_pp0_iter2 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001)) | ((tmp_i_2861_reg_1001 == 1'd1) & (ap_enable_reg_pp0_iter2 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001)))) begin
        reg_384 <= in_V_V_dout;
    end
end

always @ (posedge ap_clk) begin
    if (((tmp_i_2861_fu_489_p2 == 1'd1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        tmp_134_i_reg_1048 <= tmp_134_i_fu_368_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((tmp_i_2861_fu_489_p2 == 1'd0) & (or_cond_i_fu_661_p2 == 1'd1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        tmp_143_i_reg_1043 <= tmp_143_i_fu_362_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((exitcond_flatten_reg_982 == 1'd0) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        tmp_i_2861_reg_1001 <= tmp_i_2861_fu_489_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((exitcond_flatten_fu_440_p2 == 1'd0) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        tmp_i_reg_991 <= tmp_i_fu_451_p2;
    end
end

always @ (*) begin
    if ((exitcond_flatten_fu_440_p2 == 1'd1)) begin
        ap_condition_pp0_exit_iter0_state3 = 1'b1;
    end else begin
        ap_condition_pp0_exit_iter0_state3 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state9)) begin
        ap_done = 1'b1;
    end else begin
        ap_done = ap_done_reg;
    end
end

always @ (*) begin
    if (((ap_start == 1'b0) & (1'b1 == ap_CS_fsm_state1))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter1 == 1'b0) & (ap_enable_reg_pp0_iter5 == 1'b0) & (ap_enable_reg_pp0_iter2 == 1'b0) & (ap_enable_reg_pp0_iter4 == 1'b0) & (ap_enable_reg_pp0_iter3 == 1'b0) & (ap_enable_reg_pp0_iter0 == 1'b0))) begin
        ap_idle_pp0 = 1'b1;
    end else begin
        ap_idle_pp0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state9)) begin
        ap_ready = 1'b1;
    end else begin
        ap_ready = 1'b0;
    end
end

always @ (*) begin
    if ((((or_cond_i_reg_1039 == 1'd1) & (tmp_i_2861_reg_1001 == 1'd0) & (1'b0 == ap_block_pp0_stage0) & (ap_enable_reg_pp0_iter2 == 1'b1)) | ((tmp_i_2861_reg_1001 == 1'd1) & (1'b0 == ap_block_pp0_stage0) & (ap_enable_reg_pp0_iter2 == 1'b1)))) begin
        in_V_V_blk_n = in_V_V_empty_n;
    end else begin
        in_V_V_blk_n = 1'b1;
    end
end

always @ (*) begin
    if ((((ap_predicate_op160_read_state5 == 1'b1) & (ap_enable_reg_pp0_iter2 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001)) | ((tmp_i_2861_reg_1001 == 1'd1) & (ap_enable_reg_pp0_iter2 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001)))) begin
        in_V_V_read = 1'b1;
    end else begin
        in_V_V_read = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0) & (ap_enable_reg_pp0_iter3 == 1'b1))) begin
        if (((tmp_i_2861_reg_1001_pp0_iter2_reg == 1'd1) & (tmp_2991_reg_1086 == 2'd0))) begin
            inputBuf_0_V_address1 = inputBuf_0_V_addr_reg_1090;
        end else if ((1'b1 == ap_condition_458)) begin
            inputBuf_0_V_address1 = inputBuf_0_V_addr_4_reg_1066;
        end else begin
            inputBuf_0_V_address1 = 'bx;
        end
    end else begin
        inputBuf_0_V_address1 = 'bx;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter3 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        inputBuf_0_V_ce0 = 1'b1;
    end else begin
        inputBuf_0_V_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((((tmp_i_2861_reg_1001_pp0_iter2_reg == 1'd1) & (tmp_2991_reg_1086 == 2'd0) & (ap_enable_reg_pp0_iter3 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001)) | ((tmp_i_2861_reg_1001_pp0_iter2_reg == 1'd0) & (or_cond_i_reg_1039_pp0_iter2_reg == 1'd1) & (tmp_2996_reg_1062 == 2'd0) & (ap_enable_reg_pp0_iter3 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001)))) begin
        inputBuf_0_V_ce1 = 1'b1;
    end else begin
        inputBuf_0_V_ce1 = 1'b0;
    end
end

always @ (*) begin
    if ((((tmp_i_2861_reg_1001_pp0_iter2_reg == 1'd1) & (tmp_2991_reg_1086 == 2'd0) & (ap_enable_reg_pp0_iter3 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001)) | ((tmp_i_2861_reg_1001_pp0_iter2_reg == 1'd0) & (or_cond_i_reg_1039_pp0_iter2_reg == 1'd1) & (tmp_2996_reg_1062 == 2'd0) & (ap_enable_reg_pp0_iter3 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001)))) begin
        inputBuf_0_V_we1 = 1'b1;
    end else begin
        inputBuf_0_V_we1 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0) & (ap_enable_reg_pp0_iter3 == 1'b1))) begin
        if (((tmp_i_2861_reg_1001_pp0_iter2_reg == 1'd1) & (tmp_2991_reg_1086 == 2'd1))) begin
            inputBuf_1_V_address1 = inputBuf_1_V_addr_reg_1095;
        end else if ((1'b1 == ap_condition_470)) begin
            inputBuf_1_V_address1 = inputBuf_1_V_addr_4_reg_1071;
        end else begin
            inputBuf_1_V_address1 = 'bx;
        end
    end else begin
        inputBuf_1_V_address1 = 'bx;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter3 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        inputBuf_1_V_ce0 = 1'b1;
    end else begin
        inputBuf_1_V_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((((tmp_i_2861_reg_1001_pp0_iter2_reg == 1'd1) & (tmp_2991_reg_1086 == 2'd1) & (ap_enable_reg_pp0_iter3 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001)) | ((tmp_i_2861_reg_1001_pp0_iter2_reg == 1'd0) & (or_cond_i_reg_1039_pp0_iter2_reg == 1'd1) & (tmp_2996_reg_1062 == 2'd1) & (ap_enable_reg_pp0_iter3 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001)))) begin
        inputBuf_1_V_ce1 = 1'b1;
    end else begin
        inputBuf_1_V_ce1 = 1'b0;
    end
end

always @ (*) begin
    if ((((tmp_i_2861_reg_1001_pp0_iter2_reg == 1'd1) & (tmp_2991_reg_1086 == 2'd1) & (ap_enable_reg_pp0_iter3 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001)) | ((tmp_i_2861_reg_1001_pp0_iter2_reg == 1'd0) & (or_cond_i_reg_1039_pp0_iter2_reg == 1'd1) & (tmp_2996_reg_1062 == 2'd1) & (ap_enable_reg_pp0_iter3 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001)))) begin
        inputBuf_1_V_we1 = 1'b1;
    end else begin
        inputBuf_1_V_we1 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0) & (ap_enable_reg_pp0_iter3 == 1'b1))) begin
        if (((tmp_i_2861_reg_1001_pp0_iter2_reg == 1'd1) & (tmp_2991_reg_1086 == 2'd2))) begin
            inputBuf_2_V_address1 = inputBuf_2_V_addr_reg_1100;
        end else if ((1'b1 == ap_condition_481)) begin
            inputBuf_2_V_address1 = inputBuf_2_V_addr_4_reg_1076;
        end else begin
            inputBuf_2_V_address1 = 'bx;
        end
    end else begin
        inputBuf_2_V_address1 = 'bx;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter3 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        inputBuf_2_V_ce0 = 1'b1;
    end else begin
        inputBuf_2_V_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((((tmp_i_2861_reg_1001_pp0_iter2_reg == 1'd1) & (tmp_2991_reg_1086 == 2'd2) & (ap_enable_reg_pp0_iter3 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001)) | ((tmp_i_2861_reg_1001_pp0_iter2_reg == 1'd0) & (or_cond_i_reg_1039_pp0_iter2_reg == 1'd1) & (tmp_2996_reg_1062 == 2'd2) & (ap_enable_reg_pp0_iter3 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001)))) begin
        inputBuf_2_V_ce1 = 1'b1;
    end else begin
        inputBuf_2_V_ce1 = 1'b0;
    end
end

always @ (*) begin
    if ((((tmp_i_2861_reg_1001_pp0_iter2_reg == 1'd1) & (tmp_2991_reg_1086 == 2'd2) & (ap_enable_reg_pp0_iter3 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001)) | ((tmp_i_2861_reg_1001_pp0_iter2_reg == 1'd0) & (or_cond_i_reg_1039_pp0_iter2_reg == 1'd1) & (tmp_2996_reg_1062 == 2'd2) & (ap_enable_reg_pp0_iter3 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001)))) begin
        inputBuf_2_V_we1 = 1'b1;
    end else begin
        inputBuf_2_V_we1 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0) & (ap_enable_reg_pp0_iter3 == 1'b1))) begin
        if (((tmp_i_2861_reg_1001_pp0_iter2_reg == 1'd1) & (tmp_2991_reg_1086 == 2'd3))) begin
            inputBuf_3_V_address1 = inputBuf_3_V_addr_reg_1105;
        end else if ((1'b1 == ap_condition_492)) begin
            inputBuf_3_V_address1 = inputBuf_3_V_addr_4_reg_1081;
        end else begin
            inputBuf_3_V_address1 = 'bx;
        end
    end else begin
        inputBuf_3_V_address1 = 'bx;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter3 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        inputBuf_3_V_ce0 = 1'b1;
    end else begin
        inputBuf_3_V_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((((tmp_i_2861_reg_1001_pp0_iter2_reg == 1'd1) & (tmp_2991_reg_1086 == 2'd3) & (ap_enable_reg_pp0_iter3 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001)) | ((tmp_i_2861_reg_1001_pp0_iter2_reg == 1'd0) & (or_cond_i_reg_1039_pp0_iter2_reg == 1'd1) & (tmp_2996_reg_1062 == 2'd3) & (ap_enable_reg_pp0_iter3 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001)))) begin
        inputBuf_3_V_ce1 = 1'b1;
    end else begin
        inputBuf_3_V_ce1 = 1'b0;
    end
end

always @ (*) begin
    if ((((tmp_i_2861_reg_1001_pp0_iter2_reg == 1'd1) & (tmp_2991_reg_1086 == 2'd3) & (ap_enable_reg_pp0_iter3 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001)) | ((tmp_i_2861_reg_1001_pp0_iter2_reg == 1'd0) & (or_cond_i_reg_1039_pp0_iter2_reg == 1'd1) & (tmp_2996_reg_1062 == 2'd3) & (ap_enable_reg_pp0_iter3 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001)))) begin
        inputBuf_3_V_we1 = 1'b1;
    end else begin
        inputBuf_3_V_we1 = 1'b0;
    end
end

always @ (*) begin
    if ((~((ap_start == 1'b0) | (ap_done_reg == 1'b1)) & (1'b1 == ap_CS_fsm_state1))) begin
        numReps_blk_n = numReps_empty_n;
    end else begin
        numReps_blk_n = 1'b1;
    end
end

always @ (*) begin
    if ((~((ap_start == 1'b0) | (ap_done_reg == 1'b1)) & (1'b1 == ap_CS_fsm_state1))) begin
        numReps_out_blk_n = numReps_out_full_n;
    end else begin
        numReps_out_blk_n = 1'b1;
    end
end

always @ (*) begin
    if ((~((ap_start == 1'b0) | (numReps_out_full_n == 1'b0) | (numReps_empty_n == 1'b0) | (ap_done_reg == 1'b1)) & (1'b1 == ap_CS_fsm_state1))) begin
        numReps_out_write = 1'b1;
    end else begin
        numReps_out_write = 1'b0;
    end
end

always @ (*) begin
    if ((~((ap_start == 1'b0) | (numReps_out_full_n == 1'b0) | (numReps_empty_n == 1'b0) | (ap_done_reg == 1'b1)) & (1'b1 == ap_CS_fsm_state1))) begin
        numReps_read = 1'b1;
    end else begin
        numReps_read = 1'b0;
    end
end

always @ (*) begin
    if (((tmp_i_2861_reg_1001_pp0_iter4_reg == 1'd0) & (tmp_128_i_reg_1005_pp0_iter4_reg == 1'd1) & (1'b0 == ap_block_pp0_stage0) & (ap_enable_reg_pp0_iter5 == 1'b1))) begin
        out_V_V_blk_n = out_V_V_full_n;
    end else begin
        out_V_V_blk_n = 1'b1;
    end
end

always @ (*) begin
    if (((ap_predicate_op224_write_state8 == 1'b1) & (ap_enable_reg_pp0_iter5 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        out_V_V_write = 1'b1;
    end else begin
        out_V_V_write = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_state1 : begin
            if ((~((ap_start == 1'b0) | (numReps_out_full_n == 1'b0) | (numReps_empty_n == 1'b0) | (ap_done_reg == 1'b1)) & (1'b1 == ap_CS_fsm_state1))) begin
                ap_NS_fsm = ap_ST_fsm_state2;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state1;
            end
        end
        ap_ST_fsm_state2 : begin
            ap_NS_fsm = ap_ST_fsm_pp0_stage0;
        end
        ap_ST_fsm_pp0_stage0 : begin
            if ((~((ap_enable_reg_pp0_iter1 == 1'b0) & (exitcond_flatten_fu_440_p2 == 1'd1) & (1'b0 == ap_block_pp0_stage0_subdone) & (ap_enable_reg_pp0_iter0 == 1'b1)) & ~((ap_enable_reg_pp0_iter4 == 1'b0) & (1'b0 == ap_block_pp0_stage0_subdone) & (ap_enable_reg_pp0_iter5 == 1'b1)))) begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage0;
            end else if ((((ap_enable_reg_pp0_iter4 == 1'b0) & (1'b0 == ap_block_pp0_stage0_subdone) & (ap_enable_reg_pp0_iter5 == 1'b1)) | ((ap_enable_reg_pp0_iter1 == 1'b0) & (exitcond_flatten_fu_440_p2 == 1'd1) & (1'b0 == ap_block_pp0_stage0_subdone) & (ap_enable_reg_pp0_iter0 == 1'b1)))) begin
                ap_NS_fsm = ap_ST_fsm_state9;
            end else begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage0;
            end
        end
        ap_ST_fsm_state9 : begin
            ap_NS_fsm = ap_ST_fsm_state1;
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign ap_CS_fsm_pp0_stage0 = ap_CS_fsm[32'd2];

assign ap_CS_fsm_state1 = ap_CS_fsm[32'd0];

assign ap_CS_fsm_state2 = ap_CS_fsm[32'd1];

assign ap_CS_fsm_state9 = ap_CS_fsm[32'd3];

assign ap_block_pp0_stage0 = ~(1'b1 == 1'b1);

always @ (*) begin
    ap_block_pp0_stage0_01001 = (((out_V_V_full_n == 1'b0) & (ap_predicate_op224_write_state8 == 1'b1) & (ap_enable_reg_pp0_iter5 == 1'b1)) | ((ap_enable_reg_pp0_iter2 == 1'b1) & (((in_V_V_empty_n == 1'b0) & (ap_predicate_op160_read_state5 == 1'b1)) | ((tmp_i_2861_reg_1001 == 1'd1) & (in_V_V_empty_n == 1'b0)))));
end

always @ (*) begin
    ap_block_pp0_stage0_11001 = (((out_V_V_full_n == 1'b0) & (ap_predicate_op224_write_state8 == 1'b1) & (ap_enable_reg_pp0_iter5 == 1'b1)) | ((ap_enable_reg_pp0_iter2 == 1'b1) & (((in_V_V_empty_n == 1'b0) & (ap_predicate_op160_read_state5 == 1'b1)) | ((tmp_i_2861_reg_1001 == 1'd1) & (in_V_V_empty_n == 1'b0)))));
end

always @ (*) begin
    ap_block_pp0_stage0_subdone = (((out_V_V_full_n == 1'b0) & (ap_predicate_op224_write_state8 == 1'b1) & (ap_enable_reg_pp0_iter5 == 1'b1)) | ((ap_enable_reg_pp0_iter2 == 1'b1) & (((in_V_V_empty_n == 1'b0) & (ap_predicate_op160_read_state5 == 1'b1)) | ((tmp_i_2861_reg_1001 == 1'd1) & (in_V_V_empty_n == 1'b0)))));
end

always @ (*) begin
    ap_block_state1 = ((ap_start == 1'b0) | (numReps_out_full_n == 1'b0) | (numReps_empty_n == 1'b0) | (ap_done_reg == 1'b1));
end

assign ap_block_state3_pp0_stage0_iter0 = ~(1'b1 == 1'b1);

assign ap_block_state4_pp0_stage0_iter1 = ~(1'b1 == 1'b1);

always @ (*) begin
    ap_block_state5_pp0_stage0_iter2 = (((in_V_V_empty_n == 1'b0) & (ap_predicate_op160_read_state5 == 1'b1)) | ((tmp_i_2861_reg_1001 == 1'd1) & (in_V_V_empty_n == 1'b0)));
end

assign ap_block_state6_pp0_stage0_iter3 = ~(1'b1 == 1'b1);

assign ap_block_state7_pp0_stage0_iter4 = ~(1'b1 == 1'b1);

always @ (*) begin
    ap_block_state8_pp0_stage0_iter5 = ((out_V_V_full_n == 1'b0) & (ap_predicate_op224_write_state8 == 1'b1));
end

always @ (*) begin
    ap_condition_458 = ((tmp_i_2861_reg_1001_pp0_iter2_reg == 1'd0) & (or_cond_i_reg_1039_pp0_iter2_reg == 1'd1) & (tmp_2996_reg_1062 == 2'd0));
end

always @ (*) begin
    ap_condition_470 = ((tmp_i_2861_reg_1001_pp0_iter2_reg == 1'd0) & (or_cond_i_reg_1039_pp0_iter2_reg == 1'd1) & (tmp_2996_reg_1062 == 2'd1));
end

always @ (*) begin
    ap_condition_481 = ((tmp_i_2861_reg_1001_pp0_iter2_reg == 1'd0) & (or_cond_i_reg_1039_pp0_iter2_reg == 1'd1) & (tmp_2996_reg_1062 == 2'd2));
end

always @ (*) begin
    ap_condition_492 = ((tmp_i_2861_reg_1001_pp0_iter2_reg == 1'd0) & (or_cond_i_reg_1039_pp0_iter2_reg == 1'd1) & (tmp_2996_reg_1062 == 2'd3));
end

assign ap_enable_pp0 = (ap_idle_pp0 ^ 1'b1);

always @ (*) begin
    ap_predicate_op160_read_state5 = ((or_cond_i_reg_1039 == 1'd1) & (tmp_i_2861_reg_1001 == 1'd0));
end

always @ (*) begin
    ap_predicate_op224_write_state8 = ((tmp_i_2861_reg_1001_pp0_iter4_reg == 1'd0) & (tmp_128_i_reg_1005_pp0_iter4_reg == 1'd1));
end

assign bound_fu_434_p2 = (p_shl_fu_419_p1 + p_shl2_fu_430_p1);

assign count_simd_fu_540_p2 = (32'd1 + count_simd_3_fu_120);

assign counter_internal_blo_12_fu_706_p2 = (counter_internal_blo_fu_132 + 32'd1);

assign current_block_read_9_fu_780_p2 = (tmp_fu_774_p2 + tmp_2992_reg_1014);

assign current_block_write_14_fu_800_p2 = (current_block_write_13_fu_124 + 32'd1);

assign current_block_write_15_fu_812_p3 = ((tmp_144_i_fu_806_p2[0:0] === 1'b1) ? 32'd0 : current_block_write_14_fu_800_p2);

assign current_block_write_16_fu_820_p3 = ((tmp_143_i_reg_1043[0:0] === 1'b1) ? current_block_write_15_fu_812_p3 : current_block_write_13_fu_124);

assign current_block_write_9_2858_fu_856_p3 = ((tmp_136_i_fu_850_p2[0:0] === 1'b1) ? 32'd0 : current_block_write_fu_844_p2);

assign current_block_write_fu_844_p2 = (current_block_write_13_fu_124 + 32'd1);

assign current_line_3_i_fu_673_p3 = ((tmp_143_i_fu_362_p2[0:0] === 1'b1) ? 32'd0 : grp_fu_356_p2);

assign current_line_in_bloc_fu_769_p2 = (tmp_131_i_fu_762_p3 + count_simd_3_load_reg_1009);

assign exitcond_flatten_fu_440_p2 = ((indvar_flatten_reg_291 == bound_reg_977) ? 1'b1 : 1'b0);

assign grp_fu_356_p2 = (current_line_4_fu_128 + 32'd1);

assign i_fu_463_p3 = ((tmp_i_fu_451_p2[0:0] === 1'b1) ? 8'd1 : i_i_op_fu_457_p2);

assign i_i_op_fu_457_p2 = (i_i_reg_302 + 8'd1);

assign indvar_flatten_next_fu_445_p2 = (indvar_flatten_reg_291 + 40'd1);

assign inp_fu_731_p2 = (inp_3_fu_112 + 32'd1);

assign inputBuf_0_V_address0 = tmp_132_i_fu_869_p1;

assign inputBuf_1_V_address0 = tmp_132_i_fu_869_p1;

assign inputBuf_2_V_address0 = tmp_132_i_fu_869_p1;

assign inputBuf_3_V_address0 = tmp_132_i_fu_869_p1;

assign k_x_fu_557_p2 = (k_x_3_fu_116 + 32'd1);

assign k_y_fu_520_p2 = (32'd1 + k_y_3_fu_108);

assign numReps_out_din = numReps_dout;

assign ofm_x_fu_588_p2 = (ofm_x_3_fu_104 + 32'd1);

assign ofm_y_fu_608_p2 = (ofm_y_1_i_fu_100 + 32'd1);

assign or_cond_i_fu_661_p2 = (tmp_141_i_fu_655_p2 & tmp_140_i_fu_649_p2);

assign out_V_V_din = outElem_V_reg_1130;

assign p_i_fu_718_p3 = ((tmp_145_i_fu_712_p2[0:0] === 1'b1) ? 32'd0 : counter_internal_blo_12_fu_706_p2);

assign p_inp_1_i_fu_620_p3 = ((tmp_139_i_fu_614_p2[0:0] === 1'b1) ? 32'd0 : inp_3_fu_112);

assign p_ofm_y_5_i_fu_628_p3 = ((tmp_139_i_fu_614_p2[0:0] === 1'b1) ? 32'd0 : ofm_y_fu_608_p2);

assign p_shl2_fu_430_p1 = tmp_16_fu_423_p3;

assign p_shl_fu_419_p1 = tmp_s_fu_412_p3;

assign read_block_1_i_mid2_fu_477_p3 = ((tmp_i_reg_991[0:0] === 1'b1) ? 32'd0 : read_block_4_fu_96);

assign read_block_3_cast_i_fu_689_p1 = read_block_3_fu_681_p3;

assign read_block_3_fu_681_p3 = ((tmp_143_i_fu_362_p2[0:0] === 1'b1) ? read_block_4_cast_fu_667_p2 : tmp_2990_fu_485_p1);

assign read_block_4_cast_fu_667_p2 = (tmp_2990_fu_485_p1 + 2'd1);

assign read_block_fu_747_p2 = (read_block_1_i_mid2_fu_477_p3 + 32'd1);

assign tmp_127_i_fu_832_p1 = reg_380;

assign tmp_128_i_fu_498_p2 = ((counter_internal_blo_fu_132 < 32'd71) ? 1'b1 : 1'b0);

assign tmp_129_i_fu_534_p2 = (tmp_2995_fu_530_p1 + tmp_2994_fu_526_p1);

assign tmp_131_i_fu_762_p3 = {{tmp_129_i_reg_1019}, {3'd0}};

assign tmp_132_i_fu_869_p1 = current_line_in_bloc_reg_1052;

assign tmp_133_i_fu_546_p2 = ((count_simd_fu_540_p2 == 32'd8) ? 1'b1 : 1'b0);

assign tmp_134_i_fu_368_p2 = ((grp_fu_356_p2 == 32'd24) ? 1'b1 : 1'b0);

assign tmp_135_i_fu_563_p2 = ((k_x_fu_557_p2 == 32'd3) ? 1'b1 : 1'b0);

assign tmp_136_i_fu_850_p2 = ((current_block_write_fu_844_p2 == 32'd4) ? 1'b1 : 1'b0);

assign tmp_137_i_fu_574_p2 = ((k_y_fu_520_p2 == 32'd3) ? 1'b1 : 1'b0);

assign tmp_138_i_fu_594_p2 = ((ofm_x_3_fu_104 == 32'd0) ? 1'b1 : 1'b0);

assign tmp_139_i_fu_614_p2 = ((ofm_y_1_i_fu_100 == 32'd0) ? 1'b1 : 1'b0);

assign tmp_140_i_fu_649_p2 = ((counter_internal_blo_fu_132 < 32'd23) ? 1'b1 : 1'b0);

assign tmp_141_i_fu_655_p2 = ((read_block_1_i_mid2_fu_477_p3 < 32'd3) ? 1'b1 : 1'b0);

assign tmp_142_i_fu_785_p1 = reg_380;

assign tmp_143_i_fu_362_p2 = ((grp_fu_356_p2 == 32'd24) ? 1'b1 : 1'b0);

assign tmp_144_i_fu_806_p2 = ((current_block_write_14_fu_800_p2 == 32'd4) ? 1'b1 : 1'b0);

assign tmp_145_i_fu_712_p2 = ((counter_internal_blo_12_fu_706_p2 == 32'd71) ? 1'b1 : 1'b0);

assign tmp_16_fu_423_p3 = {{numReps_read_reg_971}, {4'd0}};

assign tmp_2990_fu_485_p1 = read_block_1_i_mid2_fu_477_p3[1:0];

assign tmp_2991_fu_840_p1 = current_block_write_13_fu_124[1:0];

assign tmp_2992_fu_516_p1 = k_y_3_fu_108[1:0];

assign tmp_2993_fu_758_p1 = current_block_write_13_fu_124[1:0];

assign tmp_2994_fu_526_p1 = k_x_3_fu_116[28:0];

assign tmp_2995_fu_530_p1 = ofm_x_3_fu_104[28:0];

assign tmp_2996_fu_793_p1 = current_block_write_13_fu_124[1:0];

assign tmp_fu_774_p2 = (2'd1 + tmp_2993_fu_758_p1);

assign tmp_i_2861_fu_489_p2 = ((inp_3_fu_112 < 32'd72) ? 1'b1 : 1'b0);

assign tmp_i_fu_451_p2 = ((i_i_reg_302 == 8'd144) ? 1'b1 : 1'b0);

assign tmp_s_fu_412_p3 = {{numReps_read_reg_971}, {7'd0}};

always @ (posedge ap_clk) begin
    bound_reg_977[3:0] <= 4'b0000;
end

endmodule //ConvolutionInputGene_3
