#!/bin/bash -f
#*********************************************************************************************************
# Vivado (TM) v2022.2 (64-bit)
#
# Filename    : procsys.sh
# Simulator   : Synopsys Verilog Compiler Simulator
# Description : Simulation script for compiling, elaborating and verifying the project source files.
#               The script will automatically create the design libraries sub-directories in the run
#               directory, add the library logical mappings in the simulator setup file, create default
#               'do/prj' file, execute compilation, elaboration and simulation steps.
#
# Generated by Vivado on Thu Apr 13 16:25:17 -0500 2023
# SW Build 3671981 on Fri Oct 14 05:00:03 MDT 2022
#
# Tool Version Limit: 2022.10 
#
# usage: procsys.sh [-help]
# usage: procsys.sh [-lib_map_path]
# usage: procsys.sh [-noclean_files]
# usage: procsys.sh [-reset_run]
#
# Prerequisite:- To compile and run simulation, you must compile the Xilinx simulation libraries using the
# 'compile_simlib' TCL command. For more information about this command, run 'compile_simlib -help' in the
# Vivado Tcl Shell. Once the libraries have been compiled successfully, specify the -lib_map_path switch
# that points to these libraries and rerun export_simulation. For more information about this switch please
# type 'export_simulation -help' in the Tcl shell.
#
# You can also point to the simulation libraries by either replacing the <SPECIFY_COMPILED_LIB_PATH> in this
# script with the compiled library directory path or specify this path with the '-lib_map_path' switch when
# executing this script. Please type 'procsys.sh -help' for more information.
#
# Additional references - 'Xilinx Vivado Design Suite User Guide:Logic simulation (UG900)'
#
#*********************************************************************************************************

# Directory path for design sources and include directories (if any) wrt this path
ref_dir="."

# Override directory with 'export_sim_ref_dir' env path value if set in the shell
if [[ (! -z "$export_sim_ref_dir") && ($export_sim_ref_dir != "") ]]; then
  ref_dir="$export_sim_ref_dir"
fi

# Set vlogan compile options
vlogan_opts="-full64 "

# Set vhdlan compile options
vhdlan_opts="-full64 "

# Set vcs elaboration options
vcs_elab_opts="-full64 -debug_acc+pp+dmptf -t ps -licqueue -l elaborate.log "

# Set vcs simulation options
vcs_sim_opts="-ucli -licqueue -l simulate.log "

# Design libraries
design_libs=(xilinx_vip xpm axi_infrastructure_v1_1_0 axi_vip_v1_1_13 processing_system7_vip_v1_0_15 xil_defaultlib lib_cdc_v1_0_2 proc_sys_reset_v5_0_13 generic_baseblocks_v2_1_0 fifo_generator_v13_2_7 axi_data_fifo_v2_1_26 axi_register_slice_v2_1_27 axi_protocol_converter_v2_1_27)

# Simulation root library directory
sim_lib_dir="vcs_lib"

# Script info
echo -e "procsys.sh - Script generated by export_simulation (Vivado v2022.2 (64-bit)-id)\n"

# Main steps
run()
{
  check_args $# $1
  setup $1 $2
  compile
  elaborate
  simulate
}

# RUN_STEP: <compile>
compile()
{
  vlogan -work xilinx_vip $vlogan_opts -sverilog +incdir+"$ref_dir/../../../../cnvW1A1-pynqZ1-Z2.srcs/sources_1/bd/procsys/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../cnvW1A1-pynqZ1-Z2.srcs/sources_1/bd/procsys/ipshared/ee60/hdl" +incdir+"$ref_dir/../../../../cnvW1A1-pynqZ1-Z2.srcs/sources_1/bd/procsys/ip/procsys_BlackBoxJam_0_0/drivers/BlackBoxJam_v1_0/src" +incdir+"$ref_dir/../../../../cnvW1A1-pynqZ1-Z2.gen/sources_1/bd/procsys/ipshared/ec67/hdl" +incdir+"C:/Xilinx/Vivado/2022.2/data/xilinx_vip/include" \
    "C:/Xilinx/Vivado/2022.2/data/xilinx_vip/hdl/axi4stream_vip_axi4streampc.sv" \
    "C:/Xilinx/Vivado/2022.2/data/xilinx_vip/hdl/axi_vip_axi4pc.sv" \
    "C:/Xilinx/Vivado/2022.2/data/xilinx_vip/hdl/xil_common_vip_pkg.sv" \
    "C:/Xilinx/Vivado/2022.2/data/xilinx_vip/hdl/axi4stream_vip_pkg.sv" \
    "C:/Xilinx/Vivado/2022.2/data/xilinx_vip/hdl/axi_vip_pkg.sv" \
    "C:/Xilinx/Vivado/2022.2/data/xilinx_vip/hdl/axi4stream_vip_if.sv" \
    "C:/Xilinx/Vivado/2022.2/data/xilinx_vip/hdl/axi_vip_if.sv" \
    "C:/Xilinx/Vivado/2022.2/data/xilinx_vip/hdl/clk_vip_if.sv" \
    "C:/Xilinx/Vivado/2022.2/data/xilinx_vip/hdl/rst_vip_if.sv" \
  2>&1 | tee -a vlogan.log

  vlogan -work xpm $vlogan_opts -sverilog +incdir+"$ref_dir/../../../../cnvW1A1-pynqZ1-Z2.srcs/sources_1/bd/procsys/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../cnvW1A1-pynqZ1-Z2.srcs/sources_1/bd/procsys/ipshared/ee60/hdl" +incdir+"$ref_dir/../../../../cnvW1A1-pynqZ1-Z2.srcs/sources_1/bd/procsys/ip/procsys_BlackBoxJam_0_0/drivers/BlackBoxJam_v1_0/src" +incdir+"$ref_dir/../../../../cnvW1A1-pynqZ1-Z2.gen/sources_1/bd/procsys/ipshared/ec67/hdl" +incdir+"C:/Xilinx/Vivado/2022.2/data/xilinx_vip/include" \
    "C:/Xilinx/Vivado/2022.2/data/ip/xpm/xpm_cdc/hdl/xpm_cdc.sv" \
    "C:/Xilinx/Vivado/2022.2/data/ip/xpm/xpm_fifo/hdl/xpm_fifo.sv" \
    "C:/Xilinx/Vivado/2022.2/data/ip/xpm/xpm_memory/hdl/xpm_memory.sv" \
  2>&1 | tee -a vlogan.log

  vhdlan -work xpm $vhdlan_opts \
    "C:/Xilinx/Vivado/2022.2/data/ip/xpm/xpm_VCOMP.vhd" \
  2>&1 | tee -a vhdlan.log

  vlogan -work axi_infrastructure_v1_1_0 $vlogan_opts +v2k +incdir+"$ref_dir/../../../../cnvW1A1-pynqZ1-Z2.srcs/sources_1/bd/procsys/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../cnvW1A1-pynqZ1-Z2.srcs/sources_1/bd/procsys/ipshared/ee60/hdl" +incdir+"$ref_dir/../../../../cnvW1A1-pynqZ1-Z2.srcs/sources_1/bd/procsys/ip/procsys_BlackBoxJam_0_0/drivers/BlackBoxJam_v1_0/src" +incdir+"$ref_dir/../../../../cnvW1A1-pynqZ1-Z2.gen/sources_1/bd/procsys/ipshared/ec67/hdl" +incdir+"C:/Xilinx/Vivado/2022.2/data/xilinx_vip/include" \
    "$ref_dir/../../../../cnvW1A1-pynqZ1-Z2.srcs/sources_1/bd/procsys/ipshared/ec67/hdl/axi_infrastructure_v1_1_vl_rfs.v" \
  2>&1 | tee -a vlogan.log

  vlogan -work axi_vip_v1_1_13 $vlogan_opts -sverilog +incdir+"$ref_dir/../../../../cnvW1A1-pynqZ1-Z2.srcs/sources_1/bd/procsys/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../cnvW1A1-pynqZ1-Z2.srcs/sources_1/bd/procsys/ipshared/ee60/hdl" +incdir+"$ref_dir/../../../../cnvW1A1-pynqZ1-Z2.srcs/sources_1/bd/procsys/ip/procsys_BlackBoxJam_0_0/drivers/BlackBoxJam_v1_0/src" +incdir+"$ref_dir/../../../../cnvW1A1-pynqZ1-Z2.gen/sources_1/bd/procsys/ipshared/ec67/hdl" +incdir+"C:/Xilinx/Vivado/2022.2/data/xilinx_vip/include" \
    "$ref_dir/../../../../cnvW1A1-pynqZ1-Z2.srcs/sources_1/bd/procsys/ipshared/ffc2/hdl/axi_vip_v1_1_vl_rfs.sv" \
  2>&1 | tee -a vlogan.log

  vlogan -work processing_system7_vip_v1_0_15 $vlogan_opts -sverilog +incdir+"$ref_dir/../../../../cnvW1A1-pynqZ1-Z2.srcs/sources_1/bd/procsys/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../cnvW1A1-pynqZ1-Z2.srcs/sources_1/bd/procsys/ipshared/ee60/hdl" +incdir+"$ref_dir/../../../../cnvW1A1-pynqZ1-Z2.srcs/sources_1/bd/procsys/ip/procsys_BlackBoxJam_0_0/drivers/BlackBoxJam_v1_0/src" +incdir+"$ref_dir/../../../../cnvW1A1-pynqZ1-Z2.gen/sources_1/bd/procsys/ipshared/ec67/hdl" +incdir+"C:/Xilinx/Vivado/2022.2/data/xilinx_vip/include" \
    "$ref_dir/../../../../cnvW1A1-pynqZ1-Z2.srcs/sources_1/bd/procsys/ipshared/ee60/hdl/processing_system7_vip_v1_0_vl_rfs.sv" \
  2>&1 | tee -a vlogan.log

  vlogan -work xil_defaultlib $vlogan_opts +v2k +incdir+"$ref_dir/../../../../cnvW1A1-pynqZ1-Z2.srcs/sources_1/bd/procsys/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../cnvW1A1-pynqZ1-Z2.srcs/sources_1/bd/procsys/ipshared/ee60/hdl" +incdir+"$ref_dir/../../../../cnvW1A1-pynqZ1-Z2.srcs/sources_1/bd/procsys/ip/procsys_BlackBoxJam_0_0/drivers/BlackBoxJam_v1_0/src" +incdir+"$ref_dir/../../../../cnvW1A1-pynqZ1-Z2.gen/sources_1/bd/procsys/ipshared/ec67/hdl" +incdir+"C:/Xilinx/Vivado/2022.2/data/xilinx_vip/include" \
    "$ref_dir/../../../bd/procsys/ip/procsys_ps7_0/sim/procsys_ps7_0.v" \
    "$ref_dir/../../../../cnvW1A1-pynqZ1-Z2.srcs/sources_1/bd/procsys/ipshared/4e48/hdl/verilog/BlackBoxJam_control_s_axi.v" \
    "$ref_dir/../../../../cnvW1A1-pynqZ1-Z2.srcs/sources_1/bd/procsys/ipshared/4e48/hdl/verilog/BlackBoxJam_hostmem_m_axi.v" \
    "$ref_dir/../../../../cnvW1A1-pynqZ1-Z2.srcs/sources_1/bd/procsys/ipshared/4e48/hdl/verilog/BlackBoxJam_mul_3CeG.v" \
    "$ref_dir/../../../../cnvW1A1-pynqZ1-Z2.srcs/sources_1/bd/procsys/ipshared/4e48/hdl/verilog/BlackBoxJam_mul_3g8j.v" \
    "$ref_dir/../../../../cnvW1A1-pynqZ1-Z2.srcs/sources_1/bd/procsys/ipshared/4e48/hdl/verilog/BlackBoxJam_mul_3ibs.v" \
    "$ref_dir/../../../../cnvW1A1-pynqZ1-Z2.srcs/sources_1/bd/procsys/ipshared/4e48/hdl/verilog/BlackBoxJam_mul_3jbC.v" \
    "$ref_dir/../../../../cnvW1A1-pynqZ1-Z2.srcs/sources_1/bd/procsys/ipshared/4e48/hdl/verilog/BlackBoxJam_mul_3ocq.v" \
    "$ref_dir/../../../../cnvW1A1-pynqZ1-Z2.srcs/sources_1/bd/procsys/ipshared/4e48/hdl/verilog/BlackBoxJam_mul_3sc4.v" \
    "$ref_dir/../../../../cnvW1A1-pynqZ1-Z2.srcs/sources_1/bd/procsys/ipshared/4e48/hdl/verilog/BlackBoxJam_mul_3xdS.v" \
    "$ref_dir/../../../../cnvW1A1-pynqZ1-Z2.srcs/sources_1/bd/procsys/ipshared/4e48/hdl/verilog/BlackBoxJam_mux_1qcK.v" \
    "$ref_dir/../../../../cnvW1A1-pynqZ1-Z2.srcs/sources_1/bd/procsys/ipshared/4e48/hdl/verilog/BlackBoxJam_mux_3DeQ.v" \
    "$ref_dir/../../../../cnvW1A1-pynqZ1-Z2.srcs/sources_1/bd/procsys/ipshared/4e48/hdl/verilog/BlackBoxJam_mux_4fYi.v" \
    "$ref_dir/../../../../cnvW1A1-pynqZ1-Z2.srcs/sources_1/bd/procsys/ipshared/4e48/hdl/verilog/BlackBoxJam_mux_4pcA.v" \
    "$ref_dir/../../../../cnvW1A1-pynqZ1-Z2.srcs/sources_1/bd/procsys/ipshared/4e48/hdl/verilog/BlackBoxJam_mux_5QgW.v" \
    "$ref_dir/../../../../cnvW1A1-pynqZ1-Z2.srcs/sources_1/bd/procsys/ipshared/4e48/hdl/verilog/BlackBoxJam_mux_6OgC.v" \
    "$ref_dir/../../../../cnvW1A1-pynqZ1-Z2.srcs/sources_1/bd/procsys/ipshared/4e48/hdl/verilog/BlackBoxJam_mux_6PgM.v" \
    "$ref_dir/../../../../cnvW1A1-pynqZ1-Z2.srcs/sources_1/bd/procsys/ipshared/4e48/hdl/verilog/BlackBoxJam_mux_7Ngs.v" \
    "$ref_dir/../../../../cnvW1A1-pynqZ1-Z2.srcs/sources_1/bd/procsys/ipshared/4e48/hdl/verilog/BlackBoxJam_mux_9hbi.v" \
    "$ref_dir/../../../../cnvW1A1-pynqZ1-Z2.srcs/sources_1/bd/procsys/ipshared/4e48/hdl/verilog/BlackBoxJam_thresbom.v" \
    "$ref_dir/../../../../cnvW1A1-pynqZ1-Z2.srcs/sources_1/bd/procsys/ipshared/4e48/hdl/verilog/BlackBoxJam_thresbqm.v" \
    "$ref_dir/../../../../cnvW1A1-pynqZ1-Z2.srcs/sources_1/bd/procsys/ipshared/4e48/hdl/verilog/BlackBoxJam_thresc9D.v" \
    "$ref_dir/../../../../cnvW1A1-pynqZ1-Z2.srcs/sources_1/bd/procsys/ipshared/4e48/hdl/verilog/BlackBoxJam_threscTB.v" \
    "$ref_dir/../../../../cnvW1A1-pynqZ1-Z2.srcs/sources_1/bd/procsys/ipshared/4e48/hdl/verilog/BlackBoxJam_thresdFJ.v" \
    "$ref_dir/../../../../cnvW1A1-pynqZ1-Z2.srcs/sources_1/bd/procsys/ipshared/4e48/hdl/verilog/BlackBoxJam_thresebO.v" \
    "$ref_dir/../../../../cnvW1A1-pynqZ1-Z2.srcs/sources_1/bd/procsys/ipshared/4e48/hdl/verilog/BlackBoxJam_weighbJp.v" \
    "$ref_dir/../../../../cnvW1A1-pynqZ1-Z2.srcs/sources_1/bd/procsys/ipshared/4e48/hdl/verilog/BlackBoxJam_weighbnm.v" \
    "$ref_dir/../../../../cnvW1A1-pynqZ1-Z2.srcs/sources_1/bd/procsys/ipshared/4e48/hdl/verilog/BlackBoxJam_weighbpm.v" \
    "$ref_dir/../../../../cnvW1A1-pynqZ1-Z2.srcs/sources_1/bd/procsys/ipshared/4e48/hdl/verilog/BlackBoxJam_weighbrm.v" \
    "$ref_dir/../../../../cnvW1A1-pynqZ1-Z2.srcs/sources_1/bd/procsys/ipshared/4e48/hdl/verilog/BlackBoxJam_weighbtn.v" \
    "$ref_dir/../../../../cnvW1A1-pynqZ1-Z2.srcs/sources_1/bd/procsys/ipshared/4e48/hdl/verilog/BlackBoxJam_weighcfu.v" \
    "$ref_dir/../../../../cnvW1A1-pynqZ1-Z2.srcs/sources_1/bd/procsys/ipshared/4e48/hdl/verilog/BlackBoxJam_weighcLz.v" \
    "$ref_dir/../../../../cnvW1A1-pynqZ1-Z2.srcs/sources_1/bd/procsys/ipshared/4e48/hdl/verilog/BlackBoxJam_weighcPA.v" \
    "$ref_dir/../../../../cnvW1A1-pynqZ1-Z2.srcs/sources_1/bd/procsys/ipshared/4e48/hdl/verilog/BlackBoxJam_weighcvx.v" \
    "$ref_dir/../../../../cnvW1A1-pynqZ1-Z2.srcs/sources_1/bd/procsys/ipshared/4e48/hdl/verilog/ConvolutionInputGbkb.v" \
    "$ref_dir/../../../../cnvW1A1-pynqZ1-Z2.srcs/sources_1/bd/procsys/ipshared/4e48/hdl/verilog/ConvolutionInputGene.v" \
    "$ref_dir/../../../../cnvW1A1-pynqZ1-Z2.srcs/sources_1/bd/procsys/ipshared/4e48/hdl/verilog/ConvolutionInputGene_1.v" \
    "$ref_dir/../../../../cnvW1A1-pynqZ1-Z2.srcs/sources_1/bd/procsys/ipshared/4e48/hdl/verilog/ConvolutionInputGene_2.v" \
    "$ref_dir/../../../../cnvW1A1-pynqZ1-Z2.srcs/sources_1/bd/procsys/ipshared/4e48/hdl/verilog/ConvolutionInputGene_3.v" \
    "$ref_dir/../../../../cnvW1A1-pynqZ1-Z2.srcs/sources_1/bd/procsys/ipshared/4e48/hdl/verilog/ConvolutionInputGene_4.v" \
    "$ref_dir/../../../../cnvW1A1-pynqZ1-Z2.srcs/sources_1/bd/procsys/ipshared/4e48/hdl/verilog/ConvolutionInputGene_5.v" \
    "$ref_dir/../../../../cnvW1A1-pynqZ1-Z2.srcs/sources_1/bd/procsys/ipshared/4e48/hdl/verilog/ConvolutionInputGFfa.v" \
    "$ref_dir/../../../../cnvW1A1-pynqZ1-Z2.srcs/sources_1/bd/procsys/ipshared/4e48/hdl/verilog/ConvolutionInputGJfO.v" \
    "$ref_dir/../../../../cnvW1A1-pynqZ1-Z2.srcs/sources_1/bd/procsys/ipshared/4e48/hdl/verilog/ConvolutionInputGkbM.v" \
    "$ref_dir/../../../../cnvW1A1-pynqZ1-Z2.srcs/sources_1/bd/procsys/ipshared/4e48/hdl/verilog/ConvolutionInputGtde.v" \
    "$ref_dir/../../../../cnvW1A1-pynqZ1-Z2.srcs/sources_1/bd/procsys/ipshared/4e48/hdl/verilog/ConvolutionInputGyd2.v" \
    "$ref_dir/../../../../cnvW1A1-pynqZ1-Z2.srcs/sources_1/bd/procsys/ipshared/4e48/hdl/verilog/DoCompute.v" \
    "$ref_dir/../../../../cnvW1A1-pynqZ1-Z2.srcs/sources_1/bd/procsys/ipshared/4e48/hdl/verilog/DoCompute_Block_pro.v" \
    "$ref_dir/../../../../cnvW1A1-pynqZ1-Z2.srcs/sources_1/bd/procsys/ipshared/4e48/hdl/verilog/DoCompute_Block_pro_1.v" \
    "$ref_dir/../../../../cnvW1A1-pynqZ1-Z2.srcs/sources_1/bd/procsys/ipshared/4e48/hdl/verilog/DoCompute_Block_pro_2.v" \
    "$ref_dir/../../../../cnvW1A1-pynqZ1-Z2.srcs/sources_1/bd/procsys/ipshared/4e48/hdl/verilog/DoCompute_Block_pro_3.v" \
    "$ref_dir/../../../../cnvW1A1-pynqZ1-Z2.srcs/sources_1/bd/procsys/ipshared/4e48/hdl/verilog/DoCompute_Block_pro_4.v" \
    "$ref_dir/../../../../cnvW1A1-pynqZ1-Z2.srcs/sources_1/bd/procsys/ipshared/4e48/hdl/verilog/DoCompute_entry33612.v" \
    "$ref_dir/../../../../cnvW1A1-pynqZ1-Z2.srcs/sources_1/bd/procsys/ipshared/4e48/hdl/verilog/DoMemInit.v" \
    "$ref_dir/../../../../cnvW1A1-pynqZ1-Z2.srcs/sources_1/bd/procsys/ipshared/4e48/hdl/verilog/fifo_w1_d2_A.v" \
    "$ref_dir/../../../../cnvW1A1-pynqZ1-Z2.srcs/sources_1/bd/procsys/ipshared/4e48/hdl/verilog/fifo_w4_d2_A.v" \
    "$ref_dir/../../../../cnvW1A1-pynqZ1-Z2.srcs/sources_1/bd/procsys/ipshared/4e48/hdl/verilog/fifo_w8_d2_A.v" \
    "$ref_dir/../../../../cnvW1A1-pynqZ1-Z2.srcs/sources_1/bd/procsys/ipshared/4e48/hdl/verilog/fifo_w16_d2_A.v" \
    "$ref_dir/../../../../cnvW1A1-pynqZ1-Z2.srcs/sources_1/bd/procsys/ipshared/4e48/hdl/verilog/fifo_w24_d2_A.v" \
    "$ref_dir/../../../../cnvW1A1-pynqZ1-Z2.srcs/sources_1/bd/procsys/ipshared/4e48/hdl/verilog/fifo_w24_d128_A.v" \
    "$ref_dir/../../../../cnvW1A1-pynqZ1-Z2.srcs/sources_1/bd/procsys/ipshared/4e48/hdl/verilog/fifo_w32_d2_A.v" \
    "$ref_dir/../../../../cnvW1A1-pynqZ1-Z2.srcs/sources_1/bd/procsys/ipshared/4e48/hdl/verilog/fifo_w32_d3_A.v" \
    "$ref_dir/../../../../cnvW1A1-pynqZ1-Z2.srcs/sources_1/bd/procsys/ipshared/4e48/hdl/verilog/fifo_w32_d5_A.v" \
    "$ref_dir/../../../../cnvW1A1-pynqZ1-Z2.srcs/sources_1/bd/procsys/ipshared/4e48/hdl/verilog/fifo_w32_d9_A.v" \
    "$ref_dir/../../../../cnvW1A1-pynqZ1-Z2.srcs/sources_1/bd/procsys/ipshared/4e48/hdl/verilog/fifo_w32_d14_A.v" \
    "$ref_dir/../../../../cnvW1A1-pynqZ1-Z2.srcs/sources_1/bd/procsys/ipshared/4e48/hdl/verilog/fifo_w32_d18_A.v" \
    "$ref_dir/../../../../cnvW1A1-pynqZ1-Z2.srcs/sources_1/bd/procsys/ipshared/4e48/hdl/verilog/fifo_w32_d23_A.v" \
    "$ref_dir/../../../../cnvW1A1-pynqZ1-Z2.srcs/sources_1/bd/procsys/ipshared/4e48/hdl/verilog/fifo_w61_d2_A.v" \
    "$ref_dir/../../../../cnvW1A1-pynqZ1-Z2.srcs/sources_1/bd/procsys/ipshared/4e48/hdl/verilog/fifo_w61_d38_A.v" \
    "$ref_dir/../../../../cnvW1A1-pynqZ1-Z2.srcs/sources_1/bd/procsys/ipshared/4e48/hdl/verilog/fifo_w64_d2_A.v" \
    "$ref_dir/../../../../cnvW1A1-pynqZ1-Z2.srcs/sources_1/bd/procsys/ipshared/4e48/hdl/verilog/fifo_w64_d3_A.v" \
    "$ref_dir/../../../../cnvW1A1-pynqZ1-Z2.srcs/sources_1/bd/procsys/ipshared/4e48/hdl/verilog/fifo_w64_d128_A.v" \
    "$ref_dir/../../../../cnvW1A1-pynqZ1-Z2.srcs/sources_1/bd/procsys/ipshared/4e48/hdl/verilog/fifo_w128_d2_A.v" \
    "$ref_dir/../../../../cnvW1A1-pynqZ1-Z2.srcs/sources_1/bd/procsys/ipshared/4e48/hdl/verilog/fifo_w128_d81_A.v" \
    "$ref_dir/../../../../cnvW1A1-pynqZ1-Z2.srcs/sources_1/bd/procsys/ipshared/4e48/hdl/verilog/fifo_w128_d128_A.v" \
    "$ref_dir/../../../../cnvW1A1-pynqZ1-Z2.srcs/sources_1/bd/procsys/ipshared/4e48/hdl/verilog/fifo_w192_d2_A.v" \
    "$ref_dir/../../../../cnvW1A1-pynqZ1-Z2.srcs/sources_1/bd/procsys/ipshared/4e48/hdl/verilog/fifo_w256_d1_A.v" \
    "$ref_dir/../../../../cnvW1A1-pynqZ1-Z2.srcs/sources_1/bd/procsys/ipshared/4e48/hdl/verilog/Matrix_Vector_Activa.v" \
    "$ref_dir/../../../../cnvW1A1-pynqZ1-Z2.srcs/sources_1/bd/procsys/ipshared/4e48/hdl/verilog/Matrix_Vector_Activa_1.v" \
    "$ref_dir/../../../../cnvW1A1-pynqZ1-Z2.srcs/sources_1/bd/procsys/ipshared/4e48/hdl/verilog/Matrix_Vector_Activa_2.v" \
    "$ref_dir/../../../../cnvW1A1-pynqZ1-Z2.srcs/sources_1/bd/procsys/ipshared/4e48/hdl/verilog/Matrix_Vector_Activa_3.v" \
    "$ref_dir/../../../../cnvW1A1-pynqZ1-Z2.srcs/sources_1/bd/procsys/ipshared/4e48/hdl/verilog/Matrix_Vector_Activa_4.v" \
    "$ref_dir/../../../../cnvW1A1-pynqZ1-Z2.srcs/sources_1/bd/procsys/ipshared/4e48/hdl/verilog/Matrix_Vector_Activa_5.v" \
    "$ref_dir/../../../../cnvW1A1-pynqZ1-Z2.srcs/sources_1/bd/procsys/ipshared/4e48/hdl/verilog/Matrix_Vector_Activa_6.v" \
    "$ref_dir/../../../../cnvW1A1-pynqZ1-Z2.srcs/sources_1/bd/procsys/ipshared/4e48/hdl/verilog/Matrix_Vector_Activa_7.v" \
    "$ref_dir/../../../../cnvW1A1-pynqZ1-Z2.srcs/sources_1/bd/procsys/ipshared/4e48/hdl/verilog/Matrix_Vector_Activa_8.v" \
    "$ref_dir/../../../../cnvW1A1-pynqZ1-Z2.srcs/sources_1/bd/procsys/ipshared/4e48/hdl/verilog/Mem2Stream.v" \
    "$ref_dir/../../../../cnvW1A1-pynqZ1-Z2.srcs/sources_1/bd/procsys/ipshared/4e48/hdl/verilog/Mem2Stream_1.v" \
    "$ref_dir/../../../../cnvW1A1-pynqZ1-Z2.srcs/sources_1/bd/procsys/ipshared/4e48/hdl/verilog/Mem2Stream_Batch.v" \
    "$ref_dir/../../../../cnvW1A1-pynqZ1-Z2.srcs/sources_1/bd/procsys/ipshared/4e48/hdl/verilog/start_for_Convolu2iS.v" \
    "$ref_dir/../../../../cnvW1A1-pynqZ1-Z2.srcs/sources_1/bd/procsys/ipshared/4e48/hdl/verilog/start_for_Convolu6jw.v" \
    "$ref_dir/../../../../cnvW1A1-pynqZ1-Z2.srcs/sources_1/bd/procsys/ipshared/4e48/hdl/verilog/start_for_Convolu9j0.v" \
    "$ref_dir/../../../../cnvW1A1-pynqZ1-Z2.srcs/sources_1/bd/procsys/ipshared/4e48/hdl/verilog/start_for_Convolubdk.v" \
    "$ref_dir/../../../../cnvW1A1-pynqZ1-Z2.srcs/sources_1/bd/procsys/ipshared/4e48/hdl/verilog/start_for_Convolubgk.v" \
    "$ref_dir/../../../../cnvW1A1-pynqZ1-Z2.srcs/sources_1/bd/procsys/ipshared/4e48/hdl/verilog/start_for_ConvoluZio.v" \
    "$ref_dir/../../../../cnvW1A1-pynqZ1-Z2.srcs/sources_1/bd/procsys/ipshared/4e48/hdl/verilog/start_for_DoCompuRg6.v" \
    "$ref_dir/../../../../cnvW1A1-pynqZ1-Z2.srcs/sources_1/bd/procsys/ipshared/4e48/hdl/verilog/start_for_DoCompuShg.v" \
    "$ref_dir/../../../../cnvW1A1-pynqZ1-Z2.srcs/sources_1/bd/procsys/ipshared/4e48/hdl/verilog/start_for_DoCompuThq.v" \
    "$ref_dir/../../../../cnvW1A1-pynqZ1-Z2.srcs/sources_1/bd/procsys/ipshared/4e48/hdl/verilog/start_for_DoCompuUhA.v" \
    "$ref_dir/../../../../cnvW1A1-pynqZ1-Z2.srcs/sources_1/bd/procsys/ipshared/4e48/hdl/verilog/start_for_DoCompuVhK.v" \
    "$ref_dir/../../../../cnvW1A1-pynqZ1-Z2.srcs/sources_1/bd/procsys/ipshared/4e48/hdl/verilog/start_for_Stream2WhU.v" \
    "$ref_dir/../../../../cnvW1A1-pynqZ1-Z2.srcs/sources_1/bd/procsys/ipshared/4e48/hdl/verilog/start_for_Streami0iy.v" \
    "$ref_dir/../../../../cnvW1A1-pynqZ1-Z2.srcs/sources_1/bd/procsys/ipshared/4e48/hdl/verilog/start_for_Streami1iI.v" \
    "$ref_dir/../../../../cnvW1A1-pynqZ1-Z2.srcs/sources_1/bd/procsys/ipshared/4e48/hdl/verilog/start_for_Streami3i2.v" \
    "$ref_dir/../../../../cnvW1A1-pynqZ1-Z2.srcs/sources_1/bd/procsys/ipshared/4e48/hdl/verilog/start_for_Streami4jc.v" \
    "$ref_dir/../../../../cnvW1A1-pynqZ1-Z2.srcs/sources_1/bd/procsys/ipshared/4e48/hdl/verilog/start_for_Streami5jm.v" \
    "$ref_dir/../../../../cnvW1A1-pynqZ1-Z2.srcs/sources_1/bd/procsys/ipshared/4e48/hdl/verilog/start_for_Streami7jG.v" \
    "$ref_dir/../../../../cnvW1A1-pynqZ1-Z2.srcs/sources_1/bd/procsys/ipshared/4e48/hdl/verilog/start_for_Streami8jQ.v" \
    "$ref_dir/../../../../cnvW1A1-pynqZ1-Z2.srcs/sources_1/bd/procsys/ipshared/4e48/hdl/verilog/start_for_Streamibak.v" \
    "$ref_dir/../../../../cnvW1A1-pynqZ1-Z2.srcs/sources_1/bd/procsys/ipshared/4e48/hdl/verilog/start_for_Streamibbk.v" \
    "$ref_dir/../../../../cnvW1A1-pynqZ1-Z2.srcs/sources_1/bd/procsys/ipshared/4e48/hdl/verilog/start_for_Streamibck.v" \
    "$ref_dir/../../../../cnvW1A1-pynqZ1-Z2.srcs/sources_1/bd/procsys/ipshared/4e48/hdl/verilog/start_for_Streamibek.v" \
    "$ref_dir/../../../../cnvW1A1-pynqZ1-Z2.srcs/sources_1/bd/procsys/ipshared/4e48/hdl/verilog/start_for_Streamibfk.v" \
    "$ref_dir/../../../../cnvW1A1-pynqZ1-Z2.srcs/sources_1/bd/procsys/ipshared/4e48/hdl/verilog/start_for_Streamibhl.v" \
    "$ref_dir/../../../../cnvW1A1-pynqZ1-Z2.srcs/sources_1/bd/procsys/ipshared/4e48/hdl/verilog/start_for_Streamibil.v" \
    "$ref_dir/../../../../cnvW1A1-pynqZ1-Z2.srcs/sources_1/bd/procsys/ipshared/4e48/hdl/verilog/start_for_Streamibjl.v" \
    "$ref_dir/../../../../cnvW1A1-pynqZ1-Z2.srcs/sources_1/bd/procsys/ipshared/4e48/hdl/verilog/start_for_Streamibkl.v" \
    "$ref_dir/../../../../cnvW1A1-pynqZ1-Z2.srcs/sources_1/bd/procsys/ipshared/4e48/hdl/verilog/start_for_Streamibll.v" \
    "$ref_dir/../../../../cnvW1A1-pynqZ1-Z2.srcs/sources_1/bd/procsys/ipshared/4e48/hdl/verilog/start_for_Streamibml.v" \
    "$ref_dir/../../../../cnvW1A1-pynqZ1-Z2.srcs/sources_1/bd/procsys/ipshared/4e48/hdl/verilog/start_for_StreamiXh4.v" \
    "$ref_dir/../../../../cnvW1A1-pynqZ1-Z2.srcs/sources_1/bd/procsys/ipshared/4e48/hdl/verilog/start_for_StreamiYie.v" \
    "$ref_dir/../../../../cnvW1A1-pynqZ1-Z2.srcs/sources_1/bd/procsys/ipshared/4e48/hdl/verilog/Stream2Mem.v" \
    "$ref_dir/../../../../cnvW1A1-pynqZ1-Z2.srcs/sources_1/bd/procsys/ipshared/4e48/hdl/verilog/Stream2Mem_1.v" \
    "$ref_dir/../../../../cnvW1A1-pynqZ1-Z2.srcs/sources_1/bd/procsys/ipshared/4e48/hdl/verilog/Stream2Mem_Batch.v" \
    "$ref_dir/../../../../cnvW1A1-pynqZ1-Z2.srcs/sources_1/bd/procsys/ipshared/4e48/hdl/verilog/StreamingDataWidthCo.v" \
    "$ref_dir/../../../../cnvW1A1-pynqZ1-Z2.srcs/sources_1/bd/procsys/ipshared/4e48/hdl/verilog/StreamingDataWidthCo_1.v" \
    "$ref_dir/../../../../cnvW1A1-pynqZ1-Z2.srcs/sources_1/bd/procsys/ipshared/4e48/hdl/verilog/StreamingDataWidthCo_2.v" \
    "$ref_dir/../../../../cnvW1A1-pynqZ1-Z2.srcs/sources_1/bd/procsys/ipshared/4e48/hdl/verilog/StreamingDataWidthCo_3.v" \
    "$ref_dir/../../../../cnvW1A1-pynqZ1-Z2.srcs/sources_1/bd/procsys/ipshared/4e48/hdl/verilog/StreamingDataWidthCo_4.v" \
    "$ref_dir/../../../../cnvW1A1-pynqZ1-Z2.srcs/sources_1/bd/procsys/ipshared/4e48/hdl/verilog/StreamingDataWidthCo_5.v" \
    "$ref_dir/../../../../cnvW1A1-pynqZ1-Z2.srcs/sources_1/bd/procsys/ipshared/4e48/hdl/verilog/StreamingDataWidthCo_6.v" \
    "$ref_dir/../../../../cnvW1A1-pynqZ1-Z2.srcs/sources_1/bd/procsys/ipshared/4e48/hdl/verilog/StreamingDataWidthCo_7.v" \
    "$ref_dir/../../../../cnvW1A1-pynqZ1-Z2.srcs/sources_1/bd/procsys/ipshared/4e48/hdl/verilog/StreamingDataWidthCo_8.v" \
    "$ref_dir/../../../../cnvW1A1-pynqZ1-Z2.srcs/sources_1/bd/procsys/ipshared/4e48/hdl/verilog/StreamingDataWidthCo_9.v" \
    "$ref_dir/../../../../cnvW1A1-pynqZ1-Z2.srcs/sources_1/bd/procsys/ipshared/4e48/hdl/verilog/StreamingDataWidthCo_10.v" \
    "$ref_dir/../../../../cnvW1A1-pynqZ1-Z2.srcs/sources_1/bd/procsys/ipshared/4e48/hdl/verilog/StreamingDataWidthCo_11.v" \
    "$ref_dir/../../../../cnvW1A1-pynqZ1-Z2.srcs/sources_1/bd/procsys/ipshared/4e48/hdl/verilog/StreamingDataWidthCo_12.v" \
    "$ref_dir/../../../../cnvW1A1-pynqZ1-Z2.srcs/sources_1/bd/procsys/ipshared/4e48/hdl/verilog/StreamingDataWidthCo_13.v" \
    "$ref_dir/../../../../cnvW1A1-pynqZ1-Z2.srcs/sources_1/bd/procsys/ipshared/4e48/hdl/verilog/StreamingDataWidthCo_14.v" \
    "$ref_dir/../../../../cnvW1A1-pynqZ1-Z2.srcs/sources_1/bd/procsys/ipshared/4e48/hdl/verilog/StreamingDataWidthCo_15.v" \
    "$ref_dir/../../../../cnvW1A1-pynqZ1-Z2.srcs/sources_1/bd/procsys/ipshared/4e48/hdl/verilog/StreamingDataWidthCo_16.v" \
    "$ref_dir/../../../../cnvW1A1-pynqZ1-Z2.srcs/sources_1/bd/procsys/ipshared/4e48/hdl/verilog/StreamingDataWidthCo_17.v" \
    "$ref_dir/../../../../cnvW1A1-pynqZ1-Z2.srcs/sources_1/bd/procsys/ipshared/4e48/hdl/verilog/StreamingMaxPool.v" \
    "$ref_dir/../../../../cnvW1A1-pynqZ1-Z2.srcs/sources_1/bd/procsys/ipshared/4e48/hdl/verilog/StreamingMaxPool_1.v" \
    "$ref_dir/../../../../cnvW1A1-pynqZ1-Z2.srcs/sources_1/bd/procsys/ipshared/4e48/hdl/verilog/StreamingMaxPool_Bat.v" \
    "$ref_dir/../../../../cnvW1A1-pynqZ1-Z2.srcs/sources_1/bd/procsys/ipshared/4e48/hdl/verilog/StreamingMaxPool_Bat_1.v" \
    "$ref_dir/../../../../cnvW1A1-pynqZ1-Z2.srcs/sources_1/bd/procsys/ipshared/4e48/hdl/verilog/StreamingMaxPool_Ee0.v" \
    "$ref_dir/../../../../cnvW1A1-pynqZ1-Z2.srcs/sources_1/bd/procsys/ipshared/4e48/hdl/verilog/StreamingMaxPool_rcU.v" \
    "$ref_dir/../../../../cnvW1A1-pynqZ1-Z2.srcs/sources_1/bd/procsys/ipshared/4e48/hdl/verilog/BlackBoxJam.v" \
    "$ref_dir/../../../bd/procsys/ip/procsys_BlackBoxJam_0_0/sim/procsys_BlackBoxJam_0_0.v" \
  2>&1 | tee -a vlogan.log

  vhdlan -work lib_cdc_v1_0_2 $vhdlan_opts \
    "$ref_dir/../../../../cnvW1A1-pynqZ1-Z2.srcs/sources_1/bd/procsys/ipshared/ef1e/hdl/lib_cdc_v1_0_rfs.vhd" \
  2>&1 | tee -a vhdlan.log

  vhdlan -work proc_sys_reset_v5_0_13 $vhdlan_opts \
    "$ref_dir/../../../../cnvW1A1-pynqZ1-Z2.srcs/sources_1/bd/procsys/ipshared/8842/hdl/proc_sys_reset_v5_0_vh_rfs.vhd" \
  2>&1 | tee -a vhdlan.log

  vhdlan -work xil_defaultlib $vhdlan_opts \
    "$ref_dir/../../../bd/procsys/ip/procsys_rst_ps7_100M_0/sim/procsys_rst_ps7_100M_0.vhd" \
  2>&1 | tee -a vhdlan.log

  vlogan -work generic_baseblocks_v2_1_0 $vlogan_opts +v2k +incdir+"$ref_dir/../../../../cnvW1A1-pynqZ1-Z2.srcs/sources_1/bd/procsys/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../cnvW1A1-pynqZ1-Z2.srcs/sources_1/bd/procsys/ipshared/ee60/hdl" +incdir+"$ref_dir/../../../../cnvW1A1-pynqZ1-Z2.srcs/sources_1/bd/procsys/ip/procsys_BlackBoxJam_0_0/drivers/BlackBoxJam_v1_0/src" +incdir+"$ref_dir/../../../../cnvW1A1-pynqZ1-Z2.gen/sources_1/bd/procsys/ipshared/ec67/hdl" +incdir+"C:/Xilinx/Vivado/2022.2/data/xilinx_vip/include" \
    "$ref_dir/../../../../cnvW1A1-pynqZ1-Z2.gen/sources_1/bd/procsys/ipshared/b752/hdl/generic_baseblocks_v2_1_vl_rfs.v" \
  2>&1 | tee -a vlogan.log

  vlogan -work fifo_generator_v13_2_7 $vlogan_opts +v2k +incdir+"$ref_dir/../../../../cnvW1A1-pynqZ1-Z2.srcs/sources_1/bd/procsys/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../cnvW1A1-pynqZ1-Z2.srcs/sources_1/bd/procsys/ipshared/ee60/hdl" +incdir+"$ref_dir/../../../../cnvW1A1-pynqZ1-Z2.srcs/sources_1/bd/procsys/ip/procsys_BlackBoxJam_0_0/drivers/BlackBoxJam_v1_0/src" +incdir+"$ref_dir/../../../../cnvW1A1-pynqZ1-Z2.gen/sources_1/bd/procsys/ipshared/ec67/hdl" +incdir+"C:/Xilinx/Vivado/2022.2/data/xilinx_vip/include" \
    "$ref_dir/../../../../cnvW1A1-pynqZ1-Z2.gen/sources_1/bd/procsys/ipshared/83df/simulation/fifo_generator_vlog_beh.v" \
  2>&1 | tee -a vlogan.log

  vhdlan -work fifo_generator_v13_2_7 $vhdlan_opts \
    "$ref_dir/../../../../cnvW1A1-pynqZ1-Z2.gen/sources_1/bd/procsys/ipshared/83df/hdl/fifo_generator_v13_2_rfs.vhd" \
  2>&1 | tee -a vhdlan.log

  vlogan -work fifo_generator_v13_2_7 $vlogan_opts +v2k +incdir+"$ref_dir/../../../../cnvW1A1-pynqZ1-Z2.srcs/sources_1/bd/procsys/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../cnvW1A1-pynqZ1-Z2.srcs/sources_1/bd/procsys/ipshared/ee60/hdl" +incdir+"$ref_dir/../../../../cnvW1A1-pynqZ1-Z2.srcs/sources_1/bd/procsys/ip/procsys_BlackBoxJam_0_0/drivers/BlackBoxJam_v1_0/src" +incdir+"$ref_dir/../../../../cnvW1A1-pynqZ1-Z2.gen/sources_1/bd/procsys/ipshared/ec67/hdl" +incdir+"C:/Xilinx/Vivado/2022.2/data/xilinx_vip/include" \
    "$ref_dir/../../../../cnvW1A1-pynqZ1-Z2.gen/sources_1/bd/procsys/ipshared/83df/hdl/fifo_generator_v13_2_rfs.v" \
  2>&1 | tee -a vlogan.log

  vlogan -work axi_data_fifo_v2_1_26 $vlogan_opts +v2k +incdir+"$ref_dir/../../../../cnvW1A1-pynqZ1-Z2.srcs/sources_1/bd/procsys/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../cnvW1A1-pynqZ1-Z2.srcs/sources_1/bd/procsys/ipshared/ee60/hdl" +incdir+"$ref_dir/../../../../cnvW1A1-pynqZ1-Z2.srcs/sources_1/bd/procsys/ip/procsys_BlackBoxJam_0_0/drivers/BlackBoxJam_v1_0/src" +incdir+"$ref_dir/../../../../cnvW1A1-pynqZ1-Z2.gen/sources_1/bd/procsys/ipshared/ec67/hdl" +incdir+"C:/Xilinx/Vivado/2022.2/data/xilinx_vip/include" \
    "$ref_dir/../../../../cnvW1A1-pynqZ1-Z2.gen/sources_1/bd/procsys/ipshared/3111/hdl/axi_data_fifo_v2_1_vl_rfs.v" \
  2>&1 | tee -a vlogan.log

  vlogan -work axi_register_slice_v2_1_27 $vlogan_opts +v2k +incdir+"$ref_dir/../../../../cnvW1A1-pynqZ1-Z2.srcs/sources_1/bd/procsys/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../cnvW1A1-pynqZ1-Z2.srcs/sources_1/bd/procsys/ipshared/ee60/hdl" +incdir+"$ref_dir/../../../../cnvW1A1-pynqZ1-Z2.srcs/sources_1/bd/procsys/ip/procsys_BlackBoxJam_0_0/drivers/BlackBoxJam_v1_0/src" +incdir+"$ref_dir/../../../../cnvW1A1-pynqZ1-Z2.gen/sources_1/bd/procsys/ipshared/ec67/hdl" +incdir+"C:/Xilinx/Vivado/2022.2/data/xilinx_vip/include" \
    "$ref_dir/../../../../cnvW1A1-pynqZ1-Z2.gen/sources_1/bd/procsys/ipshared/f0b4/hdl/axi_register_slice_v2_1_vl_rfs.v" \
  2>&1 | tee -a vlogan.log

  vlogan -work axi_protocol_converter_v2_1_27 $vlogan_opts +v2k +incdir+"$ref_dir/../../../../cnvW1A1-pynqZ1-Z2.srcs/sources_1/bd/procsys/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../cnvW1A1-pynqZ1-Z2.srcs/sources_1/bd/procsys/ipshared/ee60/hdl" +incdir+"$ref_dir/../../../../cnvW1A1-pynqZ1-Z2.srcs/sources_1/bd/procsys/ip/procsys_BlackBoxJam_0_0/drivers/BlackBoxJam_v1_0/src" +incdir+"$ref_dir/../../../../cnvW1A1-pynqZ1-Z2.gen/sources_1/bd/procsys/ipshared/ec67/hdl" +incdir+"C:/Xilinx/Vivado/2022.2/data/xilinx_vip/include" \
    "$ref_dir/../../../../cnvW1A1-pynqZ1-Z2.gen/sources_1/bd/procsys/ipshared/aeb3/hdl/axi_protocol_converter_v2_1_vl_rfs.v" \
  2>&1 | tee -a vlogan.log

  vlogan -work xil_defaultlib $vlogan_opts +v2k +incdir+"$ref_dir/../../../../cnvW1A1-pynqZ1-Z2.srcs/sources_1/bd/procsys/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../cnvW1A1-pynqZ1-Z2.srcs/sources_1/bd/procsys/ipshared/ee60/hdl" +incdir+"$ref_dir/../../../../cnvW1A1-pynqZ1-Z2.srcs/sources_1/bd/procsys/ip/procsys_BlackBoxJam_0_0/drivers/BlackBoxJam_v1_0/src" +incdir+"$ref_dir/../../../../cnvW1A1-pynqZ1-Z2.gen/sources_1/bd/procsys/ipshared/ec67/hdl" +incdir+"C:/Xilinx/Vivado/2022.2/data/xilinx_vip/include" \
    "$ref_dir/../../../bd/procsys/ip/procsys_auto_pc_0/sim/procsys_auto_pc_0.v" \
    "$ref_dir/../../../bd/procsys/ip/procsys_auto_pc_1/sim/procsys_auto_pc_1.v" \
    "$ref_dir/../../../bd/procsys/sim/procsys.v" \
  2>&1 | tee -a vlogan.log


  vlogan -work xil_defaultlib $vlogan_opts +v2k \
    glbl.v \
  2>&1 | tee -a vlogan.log
}

# RUN_STEP: <elaborate>
elaborate()
{
  vcs $vcs_elab_opts xil_defaultlib.procsys xil_defaultlib.glbl -o procsys_simv
}

# RUN_STEP: <simulate>
simulate()
{
  ./procsys_simv $vcs_sim_opts -do simulate.do
}

# STEP: setup
setup()
{
  case $1 in
    "-lib_map_path" )
      if [[ ($2 == "") ]]; then
        echo -e "ERROR: Simulation library directory path not specified (type \"./procsys.sh -help\" for more information)\n"
        exit 1
      fi
      create_lib_mappings $2
    ;;
    "-reset_run" )
      reset_run
      echo -e "INFO: Simulation run files deleted.\n"
      exit 0
    ;;
    "-noclean_files" )
      # do not remove previous data
    ;;
    * )
      create_lib_mappings $2
  esac

  create_lib_dir

  # Add any setup/initialization commands here:-

  # <user specific commands>

}

# Define design library mappings
create_lib_mappings()
{
  file="synopsys_sim.setup"
  if [[ -e $file ]]; then
    if [[ ($1 == "") ]]; then
      return
    else
      rm -rf $file
    fi
  fi

  touch $file

  lib_map_path=""
  if [[ ($1 != "") ]]; then
    lib_map_path="$1"
  fi

  for (( i=0; i<${#design_libs[*]}; i++ )); do
    lib="${design_libs[i]}"
    mapping="$lib:$sim_lib_dir/$lib"
    echo $mapping >> $file
  done

  if [[ ($lib_map_path != "") ]]; then
    incl_ref="OTHERS=$lib_map_path/synopsys_sim.setup"
    echo $incl_ref >> $file
  fi
}

# Create design library directory paths
create_lib_dir()
{
  if [[ -e $sim_lib_dir ]]; then
    rm -rf $sim_lib_dir
  fi

  for (( i=0; i<${#design_libs[*]}; i++ )); do
    lib="${design_libs[i]}"
    lib_dir="$sim_lib_dir/$lib"
    if [[ ! -e $lib_dir ]]; then
      mkdir -p $lib_dir
    fi
  done
}

# Delete generated data from the previous run
reset_run()
{
  files_to_remove=(ucli.key procsys_simv vlogan.log vhdlan.log compile.log elaborate.log simulate.log .vlogansetup.env .vlogansetup.args .vcs_lib_lock scirocco_command.log 64 AN.DB csrc procsys_simv.daidir)
  for (( i=0; i<${#files_to_remove[*]}; i++ )); do
    file="${files_to_remove[i]}"
    if [[ -e $file ]]; then
      rm -rf $file
    fi
  done

  create_lib_dir
}

# Check command line arguments
check_args()
{
  if [[ ($1 == 1 ) && ($2 != "-lib_map_path" && $2 != "-noclean_files" && $2 != "-reset_run" && $2 != "-help" && $2 != "-h") ]]; then
    echo -e "ERROR: Unknown option specified '$2' (type \"./procsys.sh -help\" for more information)\n"
    exit 1
  fi

  if [[ ($2 == "-help" || $2 == "-h") ]]; then
    usage
  fi
}

# Script usage
usage()
{
  msg="Usage: procsys.sh [-help]\n\
Usage: procsys.sh [-lib_map_path]\n\
Usage: procsys.sh [-reset_run]\n\
Usage: procsys.sh [-noclean_files]\n\n\
[-help] -- Print help information for this script\n\n\
[-lib_map_path <path>] -- Compiled simulation library directory path. The simulation library is compiled\n\
using the compile_simlib tcl command. Please see 'compile_simlib -help' for more information.\n\n\
[-reset_run] -- Recreate simulator setup files and library mappings for a clean run. The generated files\n\
from the previous run will be removed. If you don't want to remove the simulator generated files, use the\n\
-noclean_files switch.\n\n\
[-noclean_files] -- Reset previous run, but do not remove simulator generated files from the previous run.\n\n"
  echo -e $msg
  exit 1
}

# Launch script
run $1 $2
