// ==============================================================
// RTL generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
// Version: 2018.2
// Copyright (C) 1986-2018 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

`timescale 1 ns / 1 ps 

module ConvolutionInputGene_4 (
        ap_clk,
        ap_rst,
        ap_start,
        ap_done,
        ap_continue,
        ap_idle,
        ap_ready,
        in_V_V_dout,
        in_V_V_empty_n,
        in_V_V_read,
        out_V_V_din,
        out_V_V_full_n,
        out_V_V_write,
        numReps_dout,
        numReps_empty_n,
        numReps_read,
        numReps_out_din,
        numReps_out_full_n,
        numReps_out_write
);

parameter    ap_ST_fsm_state1 = 4'd1;
parameter    ap_ST_fsm_state2 = 4'd2;
parameter    ap_ST_fsm_pp0_stage0 = 4'd4;
parameter    ap_ST_fsm_state9 = 4'd8;

input   ap_clk;
input   ap_rst;
input   ap_start;
output   ap_done;
input   ap_continue;
output   ap_idle;
output   ap_ready;
input  [31:0] in_V_V_dout;
input   in_V_V_empty_n;
output   in_V_V_read;
output  [31:0] out_V_V_din;
input   out_V_V_full_n;
output   out_V_V_write;
input  [31:0] numReps_dout;
input   numReps_empty_n;
output   numReps_read;
output  [31:0] numReps_out_din;
input   numReps_out_full_n;
output   numReps_out_write;

reg ap_done;
reg ap_idle;
reg ap_ready;
reg in_V_V_read;
reg out_V_V_write;
reg numReps_read;
reg numReps_out_write;

reg    ap_done_reg;
(* fsm_encoding = "none" *) reg   [3:0] ap_CS_fsm;
wire    ap_CS_fsm_state1;
reg    in_V_V_blk_n;
reg    ap_enable_reg_pp0_iter2;
wire    ap_block_pp0_stage0;
reg   [0:0] tmp_i_2857_reg_995;
reg   [0:0] or_cond_i_reg_1034;
reg    out_V_V_blk_n;
reg    ap_enable_reg_pp0_iter5;
reg   [0:0] tmp_i_2857_reg_995_pp0_iter4_reg;
reg   [0:0] tmp_147_i_reg_999;
reg   [0:0] tmp_147_i_reg_999_pp0_iter4_reg;
reg    numReps_blk_n;
reg    numReps_out_blk_n;
reg   [40:0] indvar_flatten_reg_289;
reg   [8:0] i_i_reg_300;
reg   [31:0] reg_378;
wire    ap_CS_fsm_pp0_stage0;
reg    ap_enable_reg_pp0_iter1;
wire    ap_block_state3_pp0_stage0_iter0;
wire    ap_block_state4_pp0_stage0_iter1;
reg    ap_predicate_op159_read_state5;
reg    ap_block_state5_pp0_stage0_iter2;
wire    ap_block_state6_pp0_stage0_iter3;
wire    ap_block_state7_pp0_stage0_iter4;
reg    ap_predicate_op223_write_state8;
reg    ap_block_state8_pp0_stage0_iter5;
reg    ap_block_pp0_stage0_11001;
wire   [0:0] tmp_i_2857_fu_483_p2;
wire   [0:0] or_cond_i_fu_655_p2;
reg   [31:0] reg_382;
reg   [31:0] numReps_read_reg_965;
reg    ap_block_state1;
wire   [40:0] bound_fu_428_p2;
reg   [40:0] bound_reg_971;
wire    ap_CS_fsm_state2;
wire   [0:0] exitcond_flatten_fu_434_p2;
reg   [0:0] exitcond_flatten_reg_976;
wire   [40:0] indvar_flatten_next_fu_439_p2;
reg    ap_enable_reg_pp0_iter0;
wire   [0:0] tmp_i_fu_445_p2;
reg   [0:0] tmp_i_reg_985;
wire   [8:0] i_fu_457_p3;
reg   [0:0] tmp_i_2857_reg_995_pp0_iter2_reg;
reg   [0:0] tmp_i_2857_reg_995_pp0_iter3_reg;
wire   [0:0] tmp_147_i_fu_492_p2;
reg   [0:0] tmp_147_i_reg_999_pp0_iter2_reg;
reg   [0:0] tmp_147_i_reg_999_pp0_iter3_reg;
reg   [31:0] count_simd_2_load_reg_1003;
wire   [1:0] tmp_2985_fu_510_p1;
reg   [1:0] tmp_2985_reg_1008;
wire   [29:0] tmp_148_i_fu_528_p2;
reg   [29:0] tmp_148_i_reg_1013;
wire   [0:0] tmp_152_i_fu_540_p2;
wire   [0:0] tmp_154_i_fu_557_p2;
wire   [0:0] tmp_156_i_fu_568_p2;
wire   [0:0] tmp_157_i_fu_588_p2;
reg   [0:0] or_cond_i_reg_1034_pp0_iter2_reg;
wire   [0:0] tmp_162_i_fu_360_p2;
reg   [0:0] tmp_162_i_reg_1038;
wire   [0:0] tmp_153_i_fu_366_p2;
reg   [0:0] tmp_153_i_reg_1043;
wire   [31:0] current_line_in_bloc_fu_763_p2;
reg   [31:0] current_line_in_bloc_reg_1047;
wire   [1:0] current_block_read_fu_774_p2;
reg   [1:0] current_block_read_reg_1052;
reg   [1:0] current_block_read_reg_1052_pp0_iter3_reg;
wire   [1:0] tmp_2989_fu_787_p1;
reg   [1:0] tmp_2989_reg_1057;
reg   [4:0] inputBuf_0_V_addr_4_reg_1061;
reg   [4:0] inputBuf_1_V_addr_4_reg_1066;
reg   [4:0] inputBuf_2_V_addr_4_reg_1071;
reg   [4:0] inputBuf_3_V_addr_4_reg_1076;
wire   [1:0] tmp_2984_fu_834_p1;
reg   [1:0] tmp_2984_reg_1081;
reg   [4:0] inputBuf_0_V_addr_reg_1085;
reg   [4:0] inputBuf_1_V_addr_reg_1090;
reg   [4:0] inputBuf_2_V_addr_reg_1095;
reg   [4:0] inputBuf_3_V_addr_reg_1100;
wire   [31:0] outElem_V_fu_870_p6;
reg   [31:0] outElem_V_reg_1125;
reg    ap_block_pp0_stage0_subdone;
reg    ap_condition_pp0_exit_iter0_state3;
reg    ap_enable_reg_pp0_iter3;
reg    ap_enable_reg_pp0_iter4;
wire   [4:0] inputBuf_0_V_address0;
reg    inputBuf_0_V_ce0;
wire   [31:0] inputBuf_0_V_q0;
reg   [4:0] inputBuf_0_V_address1;
reg    inputBuf_0_V_ce1;
reg    inputBuf_0_V_we1;
wire   [4:0] inputBuf_1_V_address0;
reg    inputBuf_1_V_ce0;
wire   [31:0] inputBuf_1_V_q0;
reg   [4:0] inputBuf_1_V_address1;
reg    inputBuf_1_V_ce1;
reg    inputBuf_1_V_we1;
wire   [4:0] inputBuf_2_V_address0;
reg    inputBuf_2_V_ce0;
wire   [31:0] inputBuf_2_V_q0;
reg   [4:0] inputBuf_2_V_address1;
reg    inputBuf_2_V_ce1;
reg    inputBuf_2_V_we1;
wire   [4:0] inputBuf_3_V_address0;
reg    inputBuf_3_V_ce0;
wire   [31:0] inputBuf_3_V_q0;
reg   [4:0] inputBuf_3_V_address1;
reg    inputBuf_3_V_ce1;
reg    inputBuf_3_V_we1;
wire   [63:0] tmp_161_i_fu_779_p1;
wire   [63:0] tmp_146_i_fu_826_p1;
wire   [63:0] tmp_151_i_fu_863_p1;
reg    ap_block_pp0_stage0_01001;
reg   [31:0] read_block_3_fu_94;
wire   [31:0] read_block_1_i_mid2_fu_471_p3;
wire   [31:0] read_block_3_cast_i_fu_683_p1;
wire   [31:0] read_block_fu_741_p2;
reg   [31:0] ofm_y_1_i_fu_98;
wire   [31:0] p_ofm_y_6_i_fu_622_p3;
reg   [31:0] ofm_x_2_fu_102;
wire   [31:0] ofm_x_fu_582_p2;
reg   [31:0] k_y_2_fu_106;
wire   [31:0] k_y_fu_514_p2;
reg   [31:0] inp_2_fu_110;
wire   [31:0] p_inp_1_i_fu_614_p3;
wire   [31:0] inp_fu_725_p2;
reg   [31:0] k_x_2_fu_114;
wire   [31:0] k_x_fu_551_p2;
reg   [31:0] count_simd_2_fu_118;
wire   [31:0] count_simd_fu_534_p2;
reg   [31:0] current_block_write_9_fu_122;
wire   [31:0] current_block_write_8_2854_fu_814_p3;
wire   [31:0] current_block_write_5_2851_fu_850_p3;
reg   [31:0] current_line_3_fu_126;
wire   [31:0] current_line_3_i_fu_667_p3;
wire   [31:0] grp_fu_354_p2;
reg   [31:0] counter_internal_blo_fu_130;
wire   [31:0] p_i_fu_712_p3;
wire   [38:0] tmp_s_fu_417_p3;
wire   [40:0] p_shl_fu_410_p3;
wire   [40:0] p_shl2_fu_424_p1;
wire   [8:0] i_i_op_fu_451_p2;
wire   [29:0] tmp_2988_fu_524_p1;
wire   [29:0] tmp_2987_fu_520_p1;
wire   [31:0] ofm_y_fu_602_p2;
wire   [0:0] tmp_158_i_fu_608_p2;
wire   [0:0] tmp_159_i_fu_643_p2;
wire   [0:0] tmp_160_i_fu_649_p2;
wire   [2:0] tmp_2983_fu_479_p1;
wire   [2:0] read_block_5_cast_fu_661_p2;
wire   [2:0] read_block_2_fu_675_p3;
wire   [31:0] counter_internal_blo_8_fu_700_p2;
wire   [0:0] tmp_164_i_fu_706_p2;
wire   [31:0] tmp_150_i_fu_756_p3;
wire   [1:0] tmp_2986_fu_752_p1;
wire   [1:0] tmp_fu_768_p2;
wire   [31:0] current_block_write_6_2852_fu_794_p2;
wire   [0:0] tmp_163_i_fu_800_p2;
wire   [31:0] current_block_write_7_2853_fu_806_p3;
wire   [31:0] current_block_write_fu_838_p2;
wire   [0:0] tmp_155_i_fu_844_p2;
wire    ap_CS_fsm_state9;
reg   [3:0] ap_NS_fsm;
reg    ap_idle_pp0;
wire    ap_enable_pp0;
reg    ap_condition_460;
reg    ap_condition_472;
reg    ap_condition_483;
reg    ap_condition_494;

// power-on initialization
initial begin
#0 ap_done_reg = 1'b0;
#0 ap_CS_fsm = 4'd1;
#0 ap_enable_reg_pp0_iter2 = 1'b0;
#0 ap_enable_reg_pp0_iter5 = 1'b0;
#0 ap_enable_reg_pp0_iter1 = 1'b0;
#0 ap_enable_reg_pp0_iter0 = 1'b0;
#0 ap_enable_reg_pp0_iter3 = 1'b0;
#0 ap_enable_reg_pp0_iter4 = 1'b0;
end

ConvolutionInputGFfa #(
    .DataWidth( 32 ),
    .AddressRange( 20 ),
    .AddressWidth( 5 ))
inputBuf_0_V_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(inputBuf_0_V_address0),
    .ce0(inputBuf_0_V_ce0),
    .q0(inputBuf_0_V_q0),
    .address1(inputBuf_0_V_address1),
    .ce1(inputBuf_0_V_ce1),
    .we1(inputBuf_0_V_we1),
    .d1(reg_382)
);

ConvolutionInputGFfa #(
    .DataWidth( 32 ),
    .AddressRange( 20 ),
    .AddressWidth( 5 ))
inputBuf_1_V_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(inputBuf_1_V_address0),
    .ce0(inputBuf_1_V_ce0),
    .q0(inputBuf_1_V_q0),
    .address1(inputBuf_1_V_address1),
    .ce1(inputBuf_1_V_ce1),
    .we1(inputBuf_1_V_we1),
    .d1(reg_382)
);

ConvolutionInputGFfa #(
    .DataWidth( 32 ),
    .AddressRange( 20 ),
    .AddressWidth( 5 ))
inputBuf_2_V_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(inputBuf_2_V_address0),
    .ce0(inputBuf_2_V_ce0),
    .q0(inputBuf_2_V_q0),
    .address1(inputBuf_2_V_address1),
    .ce1(inputBuf_2_V_ce1),
    .we1(inputBuf_2_V_we1),
    .d1(reg_382)
);

ConvolutionInputGFfa #(
    .DataWidth( 32 ),
    .AddressRange( 20 ),
    .AddressWidth( 5 ))
inputBuf_3_V_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(inputBuf_3_V_address0),
    .ce0(inputBuf_3_V_ce0),
    .q0(inputBuf_3_V_q0),
    .address1(inputBuf_3_V_address1),
    .ce1(inputBuf_3_V_ce1),
    .we1(inputBuf_3_V_we1),
    .d1(reg_382)
);

BlackBoxJam_mux_4pcA #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 32 ),
    .din1_WIDTH( 32 ),
    .din2_WIDTH( 32 ),
    .din3_WIDTH( 32 ),
    .din4_WIDTH( 2 ),
    .dout_WIDTH( 32 ))
BlackBoxJam_mux_4pcA_U311(
    .din0(inputBuf_0_V_q0),
    .din1(inputBuf_1_V_q0),
    .din2(inputBuf_2_V_q0),
    .din3(inputBuf_3_V_q0),
    .din4(current_block_read_reg_1052_pp0_iter3_reg),
    .dout(outElem_V_fu_870_p6)
);

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_state1;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_done_reg <= 1'b0;
    end else begin
        if ((ap_continue == 1'b1)) begin
            ap_done_reg <= 1'b0;
        end else if ((1'b1 == ap_CS_fsm_state9)) begin
            ap_done_reg <= 1'b1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter0 <= 1'b0;
    end else begin
        if (((1'b0 == ap_block_pp0_stage0_subdone) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b1 == ap_condition_pp0_exit_iter0_state3))) begin
            ap_enable_reg_pp0_iter0 <= 1'b0;
        end else if ((1'b1 == ap_CS_fsm_state2)) begin
            ap_enable_reg_pp0_iter0 <= 1'b1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter1 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            if ((1'b1 == ap_condition_pp0_exit_iter0_state3)) begin
                ap_enable_reg_pp0_iter1 <= (1'b1 ^ ap_condition_pp0_exit_iter0_state3);
            end else if ((1'b1 == 1'b1)) begin
                ap_enable_reg_pp0_iter1 <= ap_enable_reg_pp0_iter0;
            end
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter2 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter2 <= ap_enable_reg_pp0_iter1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter3 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter3 <= ap_enable_reg_pp0_iter2;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter4 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter4 <= ap_enable_reg_pp0_iter3;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter5 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter5 <= ap_enable_reg_pp0_iter4;
        end else if ((1'b1 == ap_CS_fsm_state2)) begin
            ap_enable_reg_pp0_iter5 <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((tmp_152_i_fu_540_p2 == 1'd0) & (tmp_i_2857_fu_483_p2 == 1'd0) & (tmp_147_i_fu_492_p2 == 1'd1) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        count_simd_2_fu_118 <= count_simd_fu_534_p2;
    end else if ((((tmp_154_i_fu_557_p2 == 1'd0) & (tmp_i_2857_fu_483_p2 == 1'd0) & (tmp_152_i_fu_540_p2 == 1'd1) & (tmp_147_i_fu_492_p2 == 1'd1) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001)) | ((tmp_156_i_fu_568_p2 == 1'd0) & (tmp_i_2857_fu_483_p2 == 1'd0) & (tmp_154_i_fu_557_p2 == 1'd1) & (tmp_152_i_fu_540_p2 == 1'd1) & (tmp_147_i_fu_492_p2 == 1'd1) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001)) | ((tmp_157_i_fu_588_p2 == 1'd0) & (tmp_i_2857_fu_483_p2 == 1'd0) & (tmp_156_i_fu_568_p2 == 1'd1) & (tmp_154_i_fu_557_p2 == 1'd1) & (tmp_152_i_fu_540_p2 == 1'd1) & (tmp_147_i_fu_492_p2 == 1'd1) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001)) | ((tmp_i_2857_fu_483_p2 == 1'd0) & (tmp_157_i_fu_588_p2 == 1'd1) & (tmp_156_i_fu_568_p2 == 1'd1) & (tmp_154_i_fu_557_p2 == 1'd1) & (tmp_152_i_fu_540_p2 == 1'd1) & (tmp_147_i_fu_492_p2 == 1'd1) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001)) | (~((ap_start == 1'b0) | (numReps_out_full_n == 1'b0) | (numReps_empty_n == 1'b0) | (ap_done_reg == 1'b1)) & (1'b1 == ap_CS_fsm_state1)))) begin
        count_simd_2_fu_118 <= 32'd0;
    end
end

always @ (posedge ap_clk) begin
    if (((tmp_i_2857_fu_483_p2 == 1'd0) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        counter_internal_blo_fu_130 <= p_i_fu_712_p3;
    end else if ((((tmp_153_i_fu_366_p2 == 1'd1) & (tmp_i_2857_fu_483_p2 == 1'd1) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001)) | (~((ap_start == 1'b0) | (numReps_out_full_n == 1'b0) | (numReps_empty_n == 1'b0) | (ap_done_reg == 1'b1)) & (1'b1 == ap_CS_fsm_state1)))) begin
        counter_internal_blo_fu_130 <= 32'd0;
    end
end

always @ (posedge ap_clk) begin
    if (((tmp_153_i_reg_1043 == 1'd1) & (tmp_i_2857_reg_995 == 1'd1) & (ap_enable_reg_pp0_iter2 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        current_block_write_9_fu_122 <= current_block_write_5_2851_fu_850_p3;
    end else if (((or_cond_i_reg_1034 == 1'd1) & (tmp_i_2857_reg_995 == 1'd0) & (ap_enable_reg_pp0_iter2 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        current_block_write_9_fu_122 <= current_block_write_8_2854_fu_814_p3;
    end else if ((~((ap_start == 1'b0) | (numReps_out_full_n == 1'b0) | (numReps_empty_n == 1'b0) | (ap_done_reg == 1'b1)) & (1'b1 == ap_CS_fsm_state1))) begin
        current_block_write_9_fu_122 <= 32'd0;
    end
end

always @ (posedge ap_clk) begin
    if (((tmp_153_i_fu_366_p2 == 1'd0) & (tmp_i_2857_fu_483_p2 == 1'd1) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        current_line_3_fu_126 <= grp_fu_354_p2;
    end else if (((tmp_i_2857_fu_483_p2 == 1'd0) & (or_cond_i_fu_655_p2 == 1'd1) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        current_line_3_fu_126 <= current_line_3_i_fu_667_p3;
    end else if ((((tmp_153_i_fu_366_p2 == 1'd1) & (tmp_i_2857_fu_483_p2 == 1'd1) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001)) | (~((ap_start == 1'b0) | (numReps_out_full_n == 1'b0) | (numReps_empty_n == 1'b0) | (ap_done_reg == 1'b1)) & (1'b1 == ap_CS_fsm_state1)))) begin
        current_line_3_fu_126 <= 32'd0;
    end
end

always @ (posedge ap_clk) begin
    if (((exitcond_flatten_fu_434_p2 == 1'd0) & (1'b1 == ap_CS_fsm_pp0_stage0) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        i_i_reg_300 <= i_fu_457_p3;
    end else if ((1'b1 == ap_CS_fsm_state2)) begin
        i_i_reg_300 <= 9'd0;
    end
end

always @ (posedge ap_clk) begin
    if (((exitcond_flatten_fu_434_p2 == 1'd0) & (1'b1 == ap_CS_fsm_pp0_stage0) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        indvar_flatten_reg_289 <= indvar_flatten_next_fu_439_p2;
    end else if ((1'b1 == ap_CS_fsm_state2)) begin
        indvar_flatten_reg_289 <= 41'd0;
    end
end

always @ (posedge ap_clk) begin
    if (((tmp_i_2857_fu_483_p2 == 1'd1) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        inp_2_fu_110 <= inp_fu_725_p2;
    end else if (((tmp_i_2857_fu_483_p2 == 1'd0) & (tmp_157_i_fu_588_p2 == 1'd1) & (tmp_156_i_fu_568_p2 == 1'd1) & (tmp_154_i_fu_557_p2 == 1'd1) & (tmp_152_i_fu_540_p2 == 1'd1) & (tmp_147_i_fu_492_p2 == 1'd1) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        inp_2_fu_110 <= p_inp_1_i_fu_614_p3;
    end else if ((~((ap_start == 1'b0) | (numReps_out_full_n == 1'b0) | (numReps_empty_n == 1'b0) | (ap_done_reg == 1'b1)) & (1'b1 == ap_CS_fsm_state1))) begin
        inp_2_fu_110 <= 32'd0;
    end
end

always @ (posedge ap_clk) begin
    if (((tmp_154_i_fu_557_p2 == 1'd0) & (tmp_i_2857_fu_483_p2 == 1'd0) & (tmp_152_i_fu_540_p2 == 1'd1) & (tmp_147_i_fu_492_p2 == 1'd1) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        k_x_2_fu_114 <= k_x_fu_551_p2;
    end else if ((((tmp_156_i_fu_568_p2 == 1'd0) & (tmp_i_2857_fu_483_p2 == 1'd0) & (tmp_154_i_fu_557_p2 == 1'd1) & (tmp_152_i_fu_540_p2 == 1'd1) & (tmp_147_i_fu_492_p2 == 1'd1) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001)) | ((tmp_157_i_fu_588_p2 == 1'd0) & (tmp_i_2857_fu_483_p2 == 1'd0) & (tmp_156_i_fu_568_p2 == 1'd1) & (tmp_154_i_fu_557_p2 == 1'd1) & (tmp_152_i_fu_540_p2 == 1'd1) & (tmp_147_i_fu_492_p2 == 1'd1) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001)) | ((tmp_i_2857_fu_483_p2 == 1'd0) & (tmp_157_i_fu_588_p2 == 1'd1) & (tmp_156_i_fu_568_p2 == 1'd1) & (tmp_154_i_fu_557_p2 == 1'd1) & (tmp_152_i_fu_540_p2 == 1'd1) & (tmp_147_i_fu_492_p2 == 1'd1) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001)) | (~((ap_start == 1'b0) | (numReps_out_full_n == 1'b0) | (numReps_empty_n == 1'b0) | (ap_done_reg == 1'b1)) & (1'b1 == ap_CS_fsm_state1)))) begin
        k_x_2_fu_114 <= 32'd0;
    end
end

always @ (posedge ap_clk) begin
    if (((tmp_156_i_fu_568_p2 == 1'd0) & (tmp_i_2857_fu_483_p2 == 1'd0) & (tmp_154_i_fu_557_p2 == 1'd1) & (tmp_152_i_fu_540_p2 == 1'd1) & (tmp_147_i_fu_492_p2 == 1'd1) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        k_y_2_fu_106 <= k_y_fu_514_p2;
    end else if ((((tmp_i_2857_fu_483_p2 == 1'd0) & (tmp_156_i_fu_568_p2 == 1'd1) & (tmp_154_i_fu_557_p2 == 1'd1) & (tmp_152_i_fu_540_p2 == 1'd1) & (tmp_147_i_fu_492_p2 == 1'd1) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001)) | (~((ap_start == 1'b0) | (numReps_out_full_n == 1'b0) | (numReps_empty_n == 1'b0) | (ap_done_reg == 1'b1)) & (1'b1 == ap_CS_fsm_state1)))) begin
        k_y_2_fu_106 <= 32'd0;
    end
end

always @ (posedge ap_clk) begin
    if (((tmp_157_i_fu_588_p2 == 1'd0) & (tmp_i_2857_fu_483_p2 == 1'd0) & (tmp_156_i_fu_568_p2 == 1'd1) & (tmp_154_i_fu_557_p2 == 1'd1) & (tmp_152_i_fu_540_p2 == 1'd1) & (tmp_147_i_fu_492_p2 == 1'd1) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        ofm_x_2_fu_102 <= ofm_x_fu_582_p2;
    end else if ((((tmp_i_2857_fu_483_p2 == 1'd0) & (tmp_157_i_fu_588_p2 == 1'd1) & (tmp_156_i_fu_568_p2 == 1'd1) & (tmp_154_i_fu_557_p2 == 1'd1) & (tmp_152_i_fu_540_p2 == 1'd1) & (tmp_147_i_fu_492_p2 == 1'd1) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001)) | (~((ap_start == 1'b0) | (numReps_out_full_n == 1'b0) | (numReps_empty_n == 1'b0) | (ap_done_reg == 1'b1)) & (1'b1 == ap_CS_fsm_state1)))) begin
        ofm_x_2_fu_102 <= 32'd0;
    end
end

always @ (posedge ap_clk) begin
    if (((tmp_i_2857_fu_483_p2 == 1'd0) & (tmp_157_i_fu_588_p2 == 1'd1) & (tmp_156_i_fu_568_p2 == 1'd1) & (tmp_154_i_fu_557_p2 == 1'd1) & (tmp_152_i_fu_540_p2 == 1'd1) & (tmp_147_i_fu_492_p2 == 1'd1) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        ofm_y_1_i_fu_98 <= p_ofm_y_6_i_fu_622_p3;
    end else if ((~((ap_start == 1'b0) | (numReps_out_full_n == 1'b0) | (numReps_empty_n == 1'b0) | (ap_done_reg == 1'b1)) & (1'b1 == ap_CS_fsm_state1))) begin
        ofm_y_1_i_fu_98 <= 32'd0;
    end
end

always @ (posedge ap_clk) begin
    if (((tmp_153_i_fu_366_p2 == 1'd1) & (tmp_i_2857_fu_483_p2 == 1'd1) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        read_block_3_fu_94 <= read_block_fu_741_p2;
    end else if (((tmp_i_2857_fu_483_p2 == 1'd0) & (or_cond_i_fu_655_p2 == 1'd1) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        read_block_3_fu_94 <= read_block_3_cast_i_fu_683_p1;
    end else if ((((tmp_153_i_fu_366_p2 == 1'd0) & (tmp_i_2857_fu_483_p2 == 1'd1) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001)) | ((or_cond_i_fu_655_p2 == 1'd0) & (tmp_i_2857_fu_483_p2 == 1'd0) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001)))) begin
        read_block_3_fu_94 <= read_block_1_i_mid2_fu_471_p3;
    end else if ((~((ap_start == 1'b0) | (numReps_out_full_n == 1'b0) | (numReps_empty_n == 1'b0) | (ap_done_reg == 1'b1)) & (1'b1 == ap_CS_fsm_state1))) begin
        read_block_3_fu_94 <= 32'd0;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state2)) begin
        bound_reg_971[40 : 7] <= bound_fu_428_p2[40 : 7];
    end
end

always @ (posedge ap_clk) begin
    if (((tmp_i_2857_fu_483_p2 == 1'd0) & (tmp_147_i_fu_492_p2 == 1'd1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        count_simd_2_load_reg_1003 <= count_simd_2_fu_118;
        tmp_148_i_reg_1013 <= tmp_148_i_fu_528_p2;
        tmp_2985_reg_1008 <= tmp_2985_fu_510_p1;
    end
end

always @ (posedge ap_clk) begin
    if (((tmp_147_i_reg_999 == 1'd1) & (tmp_i_2857_reg_995 == 1'd0) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        current_block_read_reg_1052 <= current_block_read_fu_774_p2;
        current_line_in_bloc_reg_1047 <= current_line_in_bloc_fu_763_p2;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b0 == ap_block_pp0_stage0_11001)) begin
        current_block_read_reg_1052_pp0_iter3_reg <= current_block_read_reg_1052;
        or_cond_i_reg_1034_pp0_iter2_reg <= or_cond_i_reg_1034;
        tmp_147_i_reg_999_pp0_iter2_reg <= tmp_147_i_reg_999;
        tmp_147_i_reg_999_pp0_iter3_reg <= tmp_147_i_reg_999_pp0_iter2_reg;
        tmp_147_i_reg_999_pp0_iter4_reg <= tmp_147_i_reg_999_pp0_iter3_reg;
        tmp_i_2857_reg_995_pp0_iter2_reg <= tmp_i_2857_reg_995;
        tmp_i_2857_reg_995_pp0_iter3_reg <= tmp_i_2857_reg_995_pp0_iter2_reg;
        tmp_i_2857_reg_995_pp0_iter4_reg <= tmp_i_2857_reg_995_pp0_iter3_reg;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        exitcond_flatten_reg_976 <= exitcond_flatten_fu_434_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((ap_predicate_op159_read_state5 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        inputBuf_0_V_addr_4_reg_1061 <= tmp_161_i_fu_779_p1;
        inputBuf_1_V_addr_4_reg_1066 <= tmp_161_i_fu_779_p1;
        inputBuf_2_V_addr_4_reg_1071 <= tmp_161_i_fu_779_p1;
        inputBuf_3_V_addr_4_reg_1076 <= tmp_161_i_fu_779_p1;
        tmp_2989_reg_1057 <= tmp_2989_fu_787_p1;
    end
end

always @ (posedge ap_clk) begin
    if (((tmp_i_2857_reg_995 == 1'd1) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        inputBuf_0_V_addr_reg_1085 <= tmp_146_i_fu_826_p1;
        inputBuf_1_V_addr_reg_1090 <= tmp_146_i_fu_826_p1;
        inputBuf_2_V_addr_reg_1095 <= tmp_146_i_fu_826_p1;
        inputBuf_3_V_addr_reg_1100 <= tmp_146_i_fu_826_p1;
        tmp_2984_reg_1081 <= tmp_2984_fu_834_p1;
    end
end

always @ (posedge ap_clk) begin
    if ((~((ap_start == 1'b0) | (numReps_out_full_n == 1'b0) | (numReps_empty_n == 1'b0) | (ap_done_reg == 1'b1)) & (1'b1 == ap_CS_fsm_state1))) begin
        numReps_read_reg_965 <= numReps_dout;
    end
end

always @ (posedge ap_clk) begin
    if (((tmp_i_2857_fu_483_p2 == 1'd0) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        or_cond_i_reg_1034 <= or_cond_i_fu_655_p2;
        tmp_147_i_reg_999 <= tmp_147_i_fu_492_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((tmp_i_2857_reg_995_pp0_iter3_reg == 1'd0) & (tmp_147_i_reg_999_pp0_iter3_reg == 1'd1) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        outElem_V_reg_1125 <= outElem_V_fu_870_p6;
    end
end

always @ (posedge ap_clk) begin
    if ((((tmp_i_2857_fu_483_p2 == 1'd1) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001)) | ((tmp_i_2857_fu_483_p2 == 1'd0) & (or_cond_i_fu_655_p2 == 1'd1) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001)))) begin
        reg_378 <= current_line_3_fu_126;
    end
end

always @ (posedge ap_clk) begin
    if ((((ap_predicate_op159_read_state5 == 1'b1) & (ap_enable_reg_pp0_iter2 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001)) | ((tmp_i_2857_reg_995 == 1'd1) & (ap_enable_reg_pp0_iter2 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001)))) begin
        reg_382 <= in_V_V_dout;
    end
end

always @ (posedge ap_clk) begin
    if (((tmp_i_2857_fu_483_p2 == 1'd1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        tmp_153_i_reg_1043 <= tmp_153_i_fu_366_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((tmp_i_2857_fu_483_p2 == 1'd0) & (or_cond_i_fu_655_p2 == 1'd1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        tmp_162_i_reg_1038 <= tmp_162_i_fu_360_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((exitcond_flatten_reg_976 == 1'd0) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        tmp_i_2857_reg_995 <= tmp_i_2857_fu_483_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((exitcond_flatten_fu_434_p2 == 1'd0) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        tmp_i_reg_985 <= tmp_i_fu_445_p2;
    end
end

always @ (*) begin
    if ((exitcond_flatten_fu_434_p2 == 1'd1)) begin
        ap_condition_pp0_exit_iter0_state3 = 1'b1;
    end else begin
        ap_condition_pp0_exit_iter0_state3 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state9)) begin
        ap_done = 1'b1;
    end else begin
        ap_done = ap_done_reg;
    end
end

always @ (*) begin
    if (((ap_start == 1'b0) & (1'b1 == ap_CS_fsm_state1))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter1 == 1'b0) & (ap_enable_reg_pp0_iter5 == 1'b0) & (ap_enable_reg_pp0_iter2 == 1'b0) & (ap_enable_reg_pp0_iter4 == 1'b0) & (ap_enable_reg_pp0_iter3 == 1'b0) & (ap_enable_reg_pp0_iter0 == 1'b0))) begin
        ap_idle_pp0 = 1'b1;
    end else begin
        ap_idle_pp0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state9)) begin
        ap_ready = 1'b1;
    end else begin
        ap_ready = 1'b0;
    end
end

always @ (*) begin
    if ((((or_cond_i_reg_1034 == 1'd1) & (tmp_i_2857_reg_995 == 1'd0) & (1'b0 == ap_block_pp0_stage0) & (ap_enable_reg_pp0_iter2 == 1'b1)) | ((tmp_i_2857_reg_995 == 1'd1) & (1'b0 == ap_block_pp0_stage0) & (ap_enable_reg_pp0_iter2 == 1'b1)))) begin
        in_V_V_blk_n = in_V_V_empty_n;
    end else begin
        in_V_V_blk_n = 1'b1;
    end
end

always @ (*) begin
    if ((((ap_predicate_op159_read_state5 == 1'b1) & (ap_enable_reg_pp0_iter2 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001)) | ((tmp_i_2857_reg_995 == 1'd1) & (ap_enable_reg_pp0_iter2 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001)))) begin
        in_V_V_read = 1'b1;
    end else begin
        in_V_V_read = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0) & (ap_enable_reg_pp0_iter3 == 1'b1))) begin
        if (((tmp_i_2857_reg_995_pp0_iter2_reg == 1'd1) & (tmp_2984_reg_1081 == 2'd0))) begin
            inputBuf_0_V_address1 = inputBuf_0_V_addr_reg_1085;
        end else if ((1'b1 == ap_condition_460)) begin
            inputBuf_0_V_address1 = inputBuf_0_V_addr_4_reg_1061;
        end else begin
            inputBuf_0_V_address1 = 'bx;
        end
    end else begin
        inputBuf_0_V_address1 = 'bx;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter3 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        inputBuf_0_V_ce0 = 1'b1;
    end else begin
        inputBuf_0_V_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((((tmp_i_2857_reg_995_pp0_iter2_reg == 1'd1) & (tmp_2984_reg_1081 == 2'd0) & (ap_enable_reg_pp0_iter3 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001)) | ((tmp_i_2857_reg_995_pp0_iter2_reg == 1'd0) & (or_cond_i_reg_1034_pp0_iter2_reg == 1'd1) & (tmp_2989_reg_1057 == 2'd0) & (ap_enable_reg_pp0_iter3 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001)))) begin
        inputBuf_0_V_ce1 = 1'b1;
    end else begin
        inputBuf_0_V_ce1 = 1'b0;
    end
end

always @ (*) begin
    if ((((tmp_i_2857_reg_995_pp0_iter2_reg == 1'd1) & (tmp_2984_reg_1081 == 2'd0) & (ap_enable_reg_pp0_iter3 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001)) | ((tmp_i_2857_reg_995_pp0_iter2_reg == 1'd0) & (or_cond_i_reg_1034_pp0_iter2_reg == 1'd1) & (tmp_2989_reg_1057 == 2'd0) & (ap_enable_reg_pp0_iter3 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001)))) begin
        inputBuf_0_V_we1 = 1'b1;
    end else begin
        inputBuf_0_V_we1 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0) & (ap_enable_reg_pp0_iter3 == 1'b1))) begin
        if (((tmp_i_2857_reg_995_pp0_iter2_reg == 1'd1) & (tmp_2984_reg_1081 == 2'd1))) begin
            inputBuf_1_V_address1 = inputBuf_1_V_addr_reg_1090;
        end else if ((1'b1 == ap_condition_472)) begin
            inputBuf_1_V_address1 = inputBuf_1_V_addr_4_reg_1066;
        end else begin
            inputBuf_1_V_address1 = 'bx;
        end
    end else begin
        inputBuf_1_V_address1 = 'bx;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter3 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        inputBuf_1_V_ce0 = 1'b1;
    end else begin
        inputBuf_1_V_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((((tmp_i_2857_reg_995_pp0_iter2_reg == 1'd1) & (tmp_2984_reg_1081 == 2'd1) & (ap_enable_reg_pp0_iter3 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001)) | ((tmp_i_2857_reg_995_pp0_iter2_reg == 1'd0) & (or_cond_i_reg_1034_pp0_iter2_reg == 1'd1) & (tmp_2989_reg_1057 == 2'd1) & (ap_enable_reg_pp0_iter3 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001)))) begin
        inputBuf_1_V_ce1 = 1'b1;
    end else begin
        inputBuf_1_V_ce1 = 1'b0;
    end
end

always @ (*) begin
    if ((((tmp_i_2857_reg_995_pp0_iter2_reg == 1'd1) & (tmp_2984_reg_1081 == 2'd1) & (ap_enable_reg_pp0_iter3 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001)) | ((tmp_i_2857_reg_995_pp0_iter2_reg == 1'd0) & (or_cond_i_reg_1034_pp0_iter2_reg == 1'd1) & (tmp_2989_reg_1057 == 2'd1) & (ap_enable_reg_pp0_iter3 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001)))) begin
        inputBuf_1_V_we1 = 1'b1;
    end else begin
        inputBuf_1_V_we1 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0) & (ap_enable_reg_pp0_iter3 == 1'b1))) begin
        if (((tmp_i_2857_reg_995_pp0_iter2_reg == 1'd1) & (tmp_2984_reg_1081 == 2'd2))) begin
            inputBuf_2_V_address1 = inputBuf_2_V_addr_reg_1095;
        end else if ((1'b1 == ap_condition_483)) begin
            inputBuf_2_V_address1 = inputBuf_2_V_addr_4_reg_1071;
        end else begin
            inputBuf_2_V_address1 = 'bx;
        end
    end else begin
        inputBuf_2_V_address1 = 'bx;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter3 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        inputBuf_2_V_ce0 = 1'b1;
    end else begin
        inputBuf_2_V_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((((tmp_i_2857_reg_995_pp0_iter2_reg == 1'd1) & (tmp_2984_reg_1081 == 2'd2) & (ap_enable_reg_pp0_iter3 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001)) | ((tmp_i_2857_reg_995_pp0_iter2_reg == 1'd0) & (or_cond_i_reg_1034_pp0_iter2_reg == 1'd1) & (tmp_2989_reg_1057 == 2'd2) & (ap_enable_reg_pp0_iter3 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001)))) begin
        inputBuf_2_V_ce1 = 1'b1;
    end else begin
        inputBuf_2_V_ce1 = 1'b0;
    end
end

always @ (*) begin
    if ((((tmp_i_2857_reg_995_pp0_iter2_reg == 1'd1) & (tmp_2984_reg_1081 == 2'd2) & (ap_enable_reg_pp0_iter3 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001)) | ((tmp_i_2857_reg_995_pp0_iter2_reg == 1'd0) & (or_cond_i_reg_1034_pp0_iter2_reg == 1'd1) & (tmp_2989_reg_1057 == 2'd2) & (ap_enable_reg_pp0_iter3 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001)))) begin
        inputBuf_2_V_we1 = 1'b1;
    end else begin
        inputBuf_2_V_we1 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0) & (ap_enable_reg_pp0_iter3 == 1'b1))) begin
        if (((tmp_i_2857_reg_995_pp0_iter2_reg == 1'd1) & (tmp_2984_reg_1081 == 2'd3))) begin
            inputBuf_3_V_address1 = inputBuf_3_V_addr_reg_1100;
        end else if ((1'b1 == ap_condition_494)) begin
            inputBuf_3_V_address1 = inputBuf_3_V_addr_4_reg_1076;
        end else begin
            inputBuf_3_V_address1 = 'bx;
        end
    end else begin
        inputBuf_3_V_address1 = 'bx;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter3 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        inputBuf_3_V_ce0 = 1'b1;
    end else begin
        inputBuf_3_V_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((((tmp_i_2857_reg_995_pp0_iter2_reg == 1'd1) & (tmp_2984_reg_1081 == 2'd3) & (ap_enable_reg_pp0_iter3 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001)) | ((tmp_i_2857_reg_995_pp0_iter2_reg == 1'd0) & (or_cond_i_reg_1034_pp0_iter2_reg == 1'd1) & (tmp_2989_reg_1057 == 2'd3) & (ap_enable_reg_pp0_iter3 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001)))) begin
        inputBuf_3_V_ce1 = 1'b1;
    end else begin
        inputBuf_3_V_ce1 = 1'b0;
    end
end

always @ (*) begin
    if ((((tmp_i_2857_reg_995_pp0_iter2_reg == 1'd1) & (tmp_2984_reg_1081 == 2'd3) & (ap_enable_reg_pp0_iter3 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001)) | ((tmp_i_2857_reg_995_pp0_iter2_reg == 1'd0) & (or_cond_i_reg_1034_pp0_iter2_reg == 1'd1) & (tmp_2989_reg_1057 == 2'd3) & (ap_enable_reg_pp0_iter3 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001)))) begin
        inputBuf_3_V_we1 = 1'b1;
    end else begin
        inputBuf_3_V_we1 = 1'b0;
    end
end

always @ (*) begin
    if ((~((ap_start == 1'b0) | (ap_done_reg == 1'b1)) & (1'b1 == ap_CS_fsm_state1))) begin
        numReps_blk_n = numReps_empty_n;
    end else begin
        numReps_blk_n = 1'b1;
    end
end

always @ (*) begin
    if ((~((ap_start == 1'b0) | (ap_done_reg == 1'b1)) & (1'b1 == ap_CS_fsm_state1))) begin
        numReps_out_blk_n = numReps_out_full_n;
    end else begin
        numReps_out_blk_n = 1'b1;
    end
end

always @ (*) begin
    if ((~((ap_start == 1'b0) | (numReps_out_full_n == 1'b0) | (numReps_empty_n == 1'b0) | (ap_done_reg == 1'b1)) & (1'b1 == ap_CS_fsm_state1))) begin
        numReps_out_write = 1'b1;
    end else begin
        numReps_out_write = 1'b0;
    end
end

always @ (*) begin
    if ((~((ap_start == 1'b0) | (numReps_out_full_n == 1'b0) | (numReps_empty_n == 1'b0) | (ap_done_reg == 1'b1)) & (1'b1 == ap_CS_fsm_state1))) begin
        numReps_read = 1'b1;
    end else begin
        numReps_read = 1'b0;
    end
end

always @ (*) begin
    if (((tmp_i_2857_reg_995_pp0_iter4_reg == 1'd0) & (tmp_147_i_reg_999_pp0_iter4_reg == 1'd1) & (1'b0 == ap_block_pp0_stage0) & (ap_enable_reg_pp0_iter5 == 1'b1))) begin
        out_V_V_blk_n = out_V_V_full_n;
    end else begin
        out_V_V_blk_n = 1'b1;
    end
end

always @ (*) begin
    if (((ap_predicate_op223_write_state8 == 1'b1) & (ap_enable_reg_pp0_iter5 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        out_V_V_write = 1'b1;
    end else begin
        out_V_V_write = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_state1 : begin
            if ((~((ap_start == 1'b0) | (numReps_out_full_n == 1'b0) | (numReps_empty_n == 1'b0) | (ap_done_reg == 1'b1)) & (1'b1 == ap_CS_fsm_state1))) begin
                ap_NS_fsm = ap_ST_fsm_state2;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state1;
            end
        end
        ap_ST_fsm_state2 : begin
            ap_NS_fsm = ap_ST_fsm_pp0_stage0;
        end
        ap_ST_fsm_pp0_stage0 : begin
            if ((~((ap_enable_reg_pp0_iter1 == 1'b0) & (exitcond_flatten_fu_434_p2 == 1'd1) & (1'b0 == ap_block_pp0_stage0_subdone) & (ap_enable_reg_pp0_iter0 == 1'b1)) & ~((ap_enable_reg_pp0_iter4 == 1'b0) & (1'b0 == ap_block_pp0_stage0_subdone) & (ap_enable_reg_pp0_iter5 == 1'b1)))) begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage0;
            end else if ((((ap_enable_reg_pp0_iter4 == 1'b0) & (1'b0 == ap_block_pp0_stage0_subdone) & (ap_enable_reg_pp0_iter5 == 1'b1)) | ((ap_enable_reg_pp0_iter1 == 1'b0) & (exitcond_flatten_fu_434_p2 == 1'd1) & (1'b0 == ap_block_pp0_stage0_subdone) & (ap_enable_reg_pp0_iter0 == 1'b1)))) begin
                ap_NS_fsm = ap_ST_fsm_state9;
            end else begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage0;
            end
        end
        ap_ST_fsm_state9 : begin
            ap_NS_fsm = ap_ST_fsm_state1;
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign ap_CS_fsm_pp0_stage0 = ap_CS_fsm[32'd2];

assign ap_CS_fsm_state1 = ap_CS_fsm[32'd0];

assign ap_CS_fsm_state2 = ap_CS_fsm[32'd1];

assign ap_CS_fsm_state9 = ap_CS_fsm[32'd3];

assign ap_block_pp0_stage0 = ~(1'b1 == 1'b1);

always @ (*) begin
    ap_block_pp0_stage0_01001 = (((out_V_V_full_n == 1'b0) & (ap_predicate_op223_write_state8 == 1'b1) & (ap_enable_reg_pp0_iter5 == 1'b1)) | ((ap_enable_reg_pp0_iter2 == 1'b1) & (((in_V_V_empty_n == 1'b0) & (ap_predicate_op159_read_state5 == 1'b1)) | ((tmp_i_2857_reg_995 == 1'd1) & (in_V_V_empty_n == 1'b0)))));
end

always @ (*) begin
    ap_block_pp0_stage0_11001 = (((out_V_V_full_n == 1'b0) & (ap_predicate_op223_write_state8 == 1'b1) & (ap_enable_reg_pp0_iter5 == 1'b1)) | ((ap_enable_reg_pp0_iter2 == 1'b1) & (((in_V_V_empty_n == 1'b0) & (ap_predicate_op159_read_state5 == 1'b1)) | ((tmp_i_2857_reg_995 == 1'd1) & (in_V_V_empty_n == 1'b0)))));
end

always @ (*) begin
    ap_block_pp0_stage0_subdone = (((out_V_V_full_n == 1'b0) & (ap_predicate_op223_write_state8 == 1'b1) & (ap_enable_reg_pp0_iter5 == 1'b1)) | ((ap_enable_reg_pp0_iter2 == 1'b1) & (((in_V_V_empty_n == 1'b0) & (ap_predicate_op159_read_state5 == 1'b1)) | ((tmp_i_2857_reg_995 == 1'd1) & (in_V_V_empty_n == 1'b0)))));
end

always @ (*) begin
    ap_block_state1 = ((ap_start == 1'b0) | (numReps_out_full_n == 1'b0) | (numReps_empty_n == 1'b0) | (ap_done_reg == 1'b1));
end

assign ap_block_state3_pp0_stage0_iter0 = ~(1'b1 == 1'b1);

assign ap_block_state4_pp0_stage0_iter1 = ~(1'b1 == 1'b1);

always @ (*) begin
    ap_block_state5_pp0_stage0_iter2 = (((in_V_V_empty_n == 1'b0) & (ap_predicate_op159_read_state5 == 1'b1)) | ((tmp_i_2857_reg_995 == 1'd1) & (in_V_V_empty_n == 1'b0)));
end

assign ap_block_state6_pp0_stage0_iter3 = ~(1'b1 == 1'b1);

assign ap_block_state7_pp0_stage0_iter4 = ~(1'b1 == 1'b1);

always @ (*) begin
    ap_block_state8_pp0_stage0_iter5 = ((out_V_V_full_n == 1'b0) & (ap_predicate_op223_write_state8 == 1'b1));
end

always @ (*) begin
    ap_condition_460 = ((tmp_i_2857_reg_995_pp0_iter2_reg == 1'd0) & (or_cond_i_reg_1034_pp0_iter2_reg == 1'd1) & (tmp_2989_reg_1057 == 2'd0));
end

always @ (*) begin
    ap_condition_472 = ((tmp_i_2857_reg_995_pp0_iter2_reg == 1'd0) & (or_cond_i_reg_1034_pp0_iter2_reg == 1'd1) & (tmp_2989_reg_1057 == 2'd1));
end

always @ (*) begin
    ap_condition_483 = ((tmp_i_2857_reg_995_pp0_iter2_reg == 1'd0) & (or_cond_i_reg_1034_pp0_iter2_reg == 1'd1) & (tmp_2989_reg_1057 == 2'd2));
end

always @ (*) begin
    ap_condition_494 = ((tmp_i_2857_reg_995_pp0_iter2_reg == 1'd0) & (or_cond_i_reg_1034_pp0_iter2_reg == 1'd1) & (tmp_2989_reg_1057 == 2'd3));
end

assign ap_enable_pp0 = (ap_idle_pp0 ^ 1'b1);

always @ (*) begin
    ap_predicate_op159_read_state5 = ((or_cond_i_reg_1034 == 1'd1) & (tmp_i_2857_reg_995 == 1'd0));
end

always @ (*) begin
    ap_predicate_op223_write_state8 = ((tmp_i_2857_reg_995_pp0_iter4_reg == 1'd0) & (tmp_147_i_reg_999_pp0_iter4_reg == 1'd1));
end

assign bound_fu_428_p2 = (p_shl_fu_410_p3 - p_shl2_fu_424_p1);

assign count_simd_fu_534_p2 = (32'd1 + count_simd_2_fu_118);

assign counter_internal_blo_8_fu_700_p2 = (counter_internal_blo_fu_130 + 32'd1);

assign current_block_read_fu_774_p2 = (tmp_fu_768_p2 + tmp_2985_reg_1008);

assign current_block_write_5_2851_fu_850_p3 = ((tmp_155_i_fu_844_p2[0:0] === 1'b1) ? 32'd0 : current_block_write_fu_838_p2);

assign current_block_write_6_2852_fu_794_p2 = (current_block_write_9_fu_122 + 32'd1);

assign current_block_write_7_2853_fu_806_p3 = ((tmp_163_i_fu_800_p2[0:0] === 1'b1) ? 32'd0 : current_block_write_6_2852_fu_794_p2);

assign current_block_write_8_2854_fu_814_p3 = ((tmp_162_i_reg_1038[0:0] === 1'b1) ? current_block_write_7_2853_fu_806_p3 : current_block_write_9_fu_122);

assign current_block_write_fu_838_p2 = (current_block_write_9_fu_122 + 32'd1);

assign current_line_3_i_fu_667_p3 = ((tmp_162_i_fu_360_p2[0:0] === 1'b1) ? 32'd0 : grp_fu_354_p2);

assign current_line_in_bloc_fu_763_p2 = (tmp_150_i_fu_756_p3 + count_simd_2_load_reg_1003);

assign exitcond_flatten_fu_434_p2 = ((indvar_flatten_reg_289 == bound_reg_971) ? 1'b1 : 1'b0);

assign grp_fu_354_p2 = (current_line_3_fu_126 + 32'd1);

assign i_fu_457_p3 = ((tmp_i_fu_445_p2[0:0] === 1'b1) ? 9'd1 : i_i_op_fu_451_p2);

assign i_i_op_fu_451_p2 = (i_i_reg_300 + 9'd1);

assign indvar_flatten_next_fu_439_p2 = (indvar_flatten_reg_289 + 41'd1);

assign inp_fu_725_p2 = (inp_2_fu_110 + 32'd1);

assign inputBuf_0_V_address0 = tmp_151_i_fu_863_p1;

assign inputBuf_1_V_address0 = tmp_151_i_fu_863_p1;

assign inputBuf_2_V_address0 = tmp_151_i_fu_863_p1;

assign inputBuf_3_V_address0 = tmp_151_i_fu_863_p1;

assign k_x_fu_551_p2 = (k_x_2_fu_114 + 32'd1);

assign k_y_fu_514_p2 = (32'd1 + k_y_2_fu_106);

assign numReps_out_din = numReps_dout;

assign ofm_x_fu_582_p2 = (ofm_x_2_fu_102 + 32'd1);

assign ofm_y_fu_602_p2 = (ofm_y_1_i_fu_98 + 32'd1);

assign or_cond_i_fu_655_p2 = (tmp_160_i_fu_649_p2 & tmp_159_i_fu_643_p2);

assign out_V_V_din = outElem_V_reg_1125;

assign p_i_fu_712_p3 = ((tmp_164_i_fu_706_p2[0:0] === 1'b1) ? 32'd0 : counter_internal_blo_8_fu_700_p2);

assign p_inp_1_i_fu_614_p3 = ((tmp_158_i_fu_608_p2[0:0] === 1'b1) ? 32'd0 : inp_2_fu_110);

assign p_ofm_y_6_i_fu_622_p3 = ((tmp_158_i_fu_608_p2[0:0] === 1'b1) ? 32'd0 : ofm_y_fu_602_p2);

assign p_shl2_fu_424_p1 = tmp_s_fu_417_p3;

assign p_shl_fu_410_p3 = {{numReps_read_reg_965}, {9'd0}};

assign read_block_1_i_mid2_fu_471_p3 = ((tmp_i_reg_985[0:0] === 1'b1) ? 32'd0 : read_block_3_fu_94);

assign read_block_2_fu_675_p3 = ((tmp_162_i_fu_360_p2[0:0] === 1'b1) ? read_block_5_cast_fu_661_p2 : tmp_2983_fu_479_p1);

assign read_block_3_cast_i_fu_683_p1 = read_block_2_fu_675_p3;

assign read_block_5_cast_fu_661_p2 = (tmp_2983_fu_479_p1 + 3'd1);

assign read_block_fu_741_p2 = (read_block_1_i_mid2_fu_471_p3 + 32'd1);

assign tmp_146_i_fu_826_p1 = reg_378;

assign tmp_147_i_fu_492_p2 = ((counter_internal_blo_fu_130 < 32'd107) ? 1'b1 : 1'b0);

assign tmp_148_i_fu_528_p2 = (tmp_2988_fu_524_p1 + tmp_2987_fu_520_p1);

assign tmp_150_i_fu_756_p3 = {{tmp_148_i_reg_1013}, {2'd0}};

assign tmp_151_i_fu_863_p1 = current_line_in_bloc_reg_1047;

assign tmp_152_i_fu_540_p2 = ((count_simd_fu_534_p2 == 32'd4) ? 1'b1 : 1'b0);

assign tmp_153_i_fu_366_p2 = ((grp_fu_354_p2 == 32'd20) ? 1'b1 : 1'b0);

assign tmp_154_i_fu_557_p2 = ((k_x_fu_551_p2 == 32'd3) ? 1'b1 : 1'b0);

assign tmp_155_i_fu_844_p2 = ((current_block_write_fu_838_p2 == 32'd4) ? 1'b1 : 1'b0);

assign tmp_156_i_fu_568_p2 = ((k_y_fu_514_p2 == 32'd3) ? 1'b1 : 1'b0);

assign tmp_157_i_fu_588_p2 = ((ofm_x_fu_582_p2 == 32'd3) ? 1'b1 : 1'b0);

assign tmp_158_i_fu_608_p2 = ((ofm_y_fu_602_p2 == 32'd3) ? 1'b1 : 1'b0);

assign tmp_159_i_fu_643_p2 = ((counter_internal_blo_fu_130 < 32'd19) ? 1'b1 : 1'b0);

assign tmp_160_i_fu_649_p2 = ((read_block_1_i_mid2_fu_471_p3 < 32'd5) ? 1'b1 : 1'b0);

assign tmp_161_i_fu_779_p1 = reg_378;

assign tmp_162_i_fu_360_p2 = ((grp_fu_354_p2 == 32'd20) ? 1'b1 : 1'b0);

assign tmp_163_i_fu_800_p2 = ((current_block_write_6_2852_fu_794_p2 == 32'd4) ? 1'b1 : 1'b0);

assign tmp_164_i_fu_706_p2 = ((counter_internal_blo_8_fu_700_p2 == 32'd107) ? 1'b1 : 1'b0);

assign tmp_2983_fu_479_p1 = read_block_1_i_mid2_fu_471_p3[2:0];

assign tmp_2984_fu_834_p1 = current_block_write_9_fu_122[1:0];

assign tmp_2985_fu_510_p1 = k_y_2_fu_106[1:0];

assign tmp_2986_fu_752_p1 = current_block_write_9_fu_122[1:0];

assign tmp_2987_fu_520_p1 = k_x_2_fu_114[29:0];

assign tmp_2988_fu_524_p1 = ofm_x_2_fu_102[29:0];

assign tmp_2989_fu_787_p1 = current_block_write_9_fu_122[1:0];

assign tmp_fu_768_p2 = (2'd1 + tmp_2986_fu_752_p1);

assign tmp_i_2857_fu_483_p2 = ((inp_2_fu_110 < 32'd60) ? 1'b1 : 1'b0);

assign tmp_i_fu_445_p2 = ((i_i_reg_300 == 9'd384) ? 1'b1 : 1'b0);

assign tmp_s_fu_417_p3 = {{numReps_read_reg_965}, {7'd0}};

always @ (posedge ap_clk) begin
    bound_reg_971[6:0] <= 7'b0000000;
end

endmodule //ConvolutionInputGene_4
