// ==============================================================
// RTL generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
// Version: 2018.2
// Copyright (C) 1986-2018 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

#include "DoCompute_entry33612.h"
#include "AESL_pkg.h"

using namespace std;

namespace ap_rtl {

const sc_logic DoCompute_entry33612::ap_const_logic_1 = sc_dt::Log_1;
const sc_logic DoCompute_entry33612::ap_const_logic_0 = sc_dt::Log_0;
const sc_lv<1> DoCompute_entry33612::ap_ST_fsm_state1 = "1";
const sc_lv<32> DoCompute_entry33612::ap_const_lv32_0 = "00000000000000000000000000000000";
const bool DoCompute_entry33612::ap_const_boolean_1 = true;

DoCompute_entry33612::DoCompute_entry33612(sc_module_name name) : sc_module(name), mVcdFile(0) {

    SC_METHOD(thread_ap_clk_no_reset_);
    dont_initialize();
    sensitive << ( ap_clk.pos() );

    SC_METHOD(thread_ap_CS_fsm_state1);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_block_state1);
    sensitive << ( real_start );
    sensitive << ( ap_done_reg );
    sensitive << ( numReps_out_full_n );
    sensitive << ( numReps_out1_full_n );
    sensitive << ( numReps_out2_full_n );
    sensitive << ( numReps_out3_full_n );
    sensitive << ( numReps_out4_full_n );
    sensitive << ( numReps_out5_full_n );
    sensitive << ( in_V_offset_out_full_n );
    sensitive << ( out_V_offset_out_full_n );

    SC_METHOD(thread_ap_done);
    sensitive << ( real_start );
    sensitive << ( ap_done_reg );
    sensitive << ( ap_CS_fsm_state1 );
    sensitive << ( numReps_out_full_n );
    sensitive << ( numReps_out1_full_n );
    sensitive << ( numReps_out2_full_n );
    sensitive << ( numReps_out3_full_n );
    sensitive << ( numReps_out4_full_n );
    sensitive << ( numReps_out5_full_n );
    sensitive << ( in_V_offset_out_full_n );
    sensitive << ( out_V_offset_out_full_n );

    SC_METHOD(thread_ap_idle);
    sensitive << ( real_start );
    sensitive << ( ap_CS_fsm_state1 );

    SC_METHOD(thread_ap_ready);
    sensitive << ( internal_ap_ready );

    SC_METHOD(thread_in_V_offset_out_blk_n);
    sensitive << ( ap_CS_fsm_state1 );
    sensitive << ( in_V_offset_out_full_n );

    SC_METHOD(thread_in_V_offset_out_din);
    sensitive << ( real_start );
    sensitive << ( ap_done_reg );
    sensitive << ( ap_CS_fsm_state1 );
    sensitive << ( numReps_out_full_n );
    sensitive << ( numReps_out1_full_n );
    sensitive << ( numReps_out2_full_n );
    sensitive << ( numReps_out3_full_n );
    sensitive << ( numReps_out4_full_n );
    sensitive << ( numReps_out5_full_n );
    sensitive << ( in_V_offset );
    sensitive << ( in_V_offset_out_full_n );
    sensitive << ( out_V_offset_out_full_n );

    SC_METHOD(thread_in_V_offset_out_write);
    sensitive << ( real_start );
    sensitive << ( ap_done_reg );
    sensitive << ( ap_CS_fsm_state1 );
    sensitive << ( numReps_out_full_n );
    sensitive << ( numReps_out1_full_n );
    sensitive << ( numReps_out2_full_n );
    sensitive << ( numReps_out3_full_n );
    sensitive << ( numReps_out4_full_n );
    sensitive << ( numReps_out5_full_n );
    sensitive << ( in_V_offset_out_full_n );
    sensitive << ( out_V_offset_out_full_n );

    SC_METHOD(thread_internal_ap_ready);
    sensitive << ( real_start );
    sensitive << ( ap_done_reg );
    sensitive << ( ap_CS_fsm_state1 );
    sensitive << ( numReps_out_full_n );
    sensitive << ( numReps_out1_full_n );
    sensitive << ( numReps_out2_full_n );
    sensitive << ( numReps_out3_full_n );
    sensitive << ( numReps_out4_full_n );
    sensitive << ( numReps_out5_full_n );
    sensitive << ( in_V_offset_out_full_n );
    sensitive << ( out_V_offset_out_full_n );

    SC_METHOD(thread_numReps_out1_blk_n);
    sensitive << ( ap_CS_fsm_state1 );
    sensitive << ( numReps_out1_full_n );

    SC_METHOD(thread_numReps_out1_din);
    sensitive << ( real_start );
    sensitive << ( ap_done_reg );
    sensitive << ( ap_CS_fsm_state1 );
    sensitive << ( numReps );
    sensitive << ( numReps_out_full_n );
    sensitive << ( numReps_out1_full_n );
    sensitive << ( numReps_out2_full_n );
    sensitive << ( numReps_out3_full_n );
    sensitive << ( numReps_out4_full_n );
    sensitive << ( numReps_out5_full_n );
    sensitive << ( in_V_offset_out_full_n );
    sensitive << ( out_V_offset_out_full_n );

    SC_METHOD(thread_numReps_out1_write);
    sensitive << ( real_start );
    sensitive << ( ap_done_reg );
    sensitive << ( ap_CS_fsm_state1 );
    sensitive << ( numReps_out_full_n );
    sensitive << ( numReps_out1_full_n );
    sensitive << ( numReps_out2_full_n );
    sensitive << ( numReps_out3_full_n );
    sensitive << ( numReps_out4_full_n );
    sensitive << ( numReps_out5_full_n );
    sensitive << ( in_V_offset_out_full_n );
    sensitive << ( out_V_offset_out_full_n );

    SC_METHOD(thread_numReps_out2_blk_n);
    sensitive << ( ap_CS_fsm_state1 );
    sensitive << ( numReps_out2_full_n );

    SC_METHOD(thread_numReps_out2_din);
    sensitive << ( real_start );
    sensitive << ( ap_done_reg );
    sensitive << ( ap_CS_fsm_state1 );
    sensitive << ( numReps );
    sensitive << ( numReps_out_full_n );
    sensitive << ( numReps_out1_full_n );
    sensitive << ( numReps_out2_full_n );
    sensitive << ( numReps_out3_full_n );
    sensitive << ( numReps_out4_full_n );
    sensitive << ( numReps_out5_full_n );
    sensitive << ( in_V_offset_out_full_n );
    sensitive << ( out_V_offset_out_full_n );

    SC_METHOD(thread_numReps_out2_write);
    sensitive << ( real_start );
    sensitive << ( ap_done_reg );
    sensitive << ( ap_CS_fsm_state1 );
    sensitive << ( numReps_out_full_n );
    sensitive << ( numReps_out1_full_n );
    sensitive << ( numReps_out2_full_n );
    sensitive << ( numReps_out3_full_n );
    sensitive << ( numReps_out4_full_n );
    sensitive << ( numReps_out5_full_n );
    sensitive << ( in_V_offset_out_full_n );
    sensitive << ( out_V_offset_out_full_n );

    SC_METHOD(thread_numReps_out3_blk_n);
    sensitive << ( ap_CS_fsm_state1 );
    sensitive << ( numReps_out3_full_n );

    SC_METHOD(thread_numReps_out3_din);
    sensitive << ( real_start );
    sensitive << ( ap_done_reg );
    sensitive << ( ap_CS_fsm_state1 );
    sensitive << ( numReps );
    sensitive << ( numReps_out_full_n );
    sensitive << ( numReps_out1_full_n );
    sensitive << ( numReps_out2_full_n );
    sensitive << ( numReps_out3_full_n );
    sensitive << ( numReps_out4_full_n );
    sensitive << ( numReps_out5_full_n );
    sensitive << ( in_V_offset_out_full_n );
    sensitive << ( out_V_offset_out_full_n );

    SC_METHOD(thread_numReps_out3_write);
    sensitive << ( real_start );
    sensitive << ( ap_done_reg );
    sensitive << ( ap_CS_fsm_state1 );
    sensitive << ( numReps_out_full_n );
    sensitive << ( numReps_out1_full_n );
    sensitive << ( numReps_out2_full_n );
    sensitive << ( numReps_out3_full_n );
    sensitive << ( numReps_out4_full_n );
    sensitive << ( numReps_out5_full_n );
    sensitive << ( in_V_offset_out_full_n );
    sensitive << ( out_V_offset_out_full_n );

    SC_METHOD(thread_numReps_out4_blk_n);
    sensitive << ( ap_CS_fsm_state1 );
    sensitive << ( numReps_out4_full_n );

    SC_METHOD(thread_numReps_out4_din);
    sensitive << ( real_start );
    sensitive << ( ap_done_reg );
    sensitive << ( ap_CS_fsm_state1 );
    sensitive << ( numReps );
    sensitive << ( numReps_out_full_n );
    sensitive << ( numReps_out1_full_n );
    sensitive << ( numReps_out2_full_n );
    sensitive << ( numReps_out3_full_n );
    sensitive << ( numReps_out4_full_n );
    sensitive << ( numReps_out5_full_n );
    sensitive << ( in_V_offset_out_full_n );
    sensitive << ( out_V_offset_out_full_n );

    SC_METHOD(thread_numReps_out4_write);
    sensitive << ( real_start );
    sensitive << ( ap_done_reg );
    sensitive << ( ap_CS_fsm_state1 );
    sensitive << ( numReps_out_full_n );
    sensitive << ( numReps_out1_full_n );
    sensitive << ( numReps_out2_full_n );
    sensitive << ( numReps_out3_full_n );
    sensitive << ( numReps_out4_full_n );
    sensitive << ( numReps_out5_full_n );
    sensitive << ( in_V_offset_out_full_n );
    sensitive << ( out_V_offset_out_full_n );

    SC_METHOD(thread_numReps_out5_blk_n);
    sensitive << ( ap_CS_fsm_state1 );
    sensitive << ( numReps_out5_full_n );

    SC_METHOD(thread_numReps_out5_din);
    sensitive << ( real_start );
    sensitive << ( ap_done_reg );
    sensitive << ( ap_CS_fsm_state1 );
    sensitive << ( numReps );
    sensitive << ( numReps_out_full_n );
    sensitive << ( numReps_out1_full_n );
    sensitive << ( numReps_out2_full_n );
    sensitive << ( numReps_out3_full_n );
    sensitive << ( numReps_out4_full_n );
    sensitive << ( numReps_out5_full_n );
    sensitive << ( in_V_offset_out_full_n );
    sensitive << ( out_V_offset_out_full_n );

    SC_METHOD(thread_numReps_out5_write);
    sensitive << ( real_start );
    sensitive << ( ap_done_reg );
    sensitive << ( ap_CS_fsm_state1 );
    sensitive << ( numReps_out_full_n );
    sensitive << ( numReps_out1_full_n );
    sensitive << ( numReps_out2_full_n );
    sensitive << ( numReps_out3_full_n );
    sensitive << ( numReps_out4_full_n );
    sensitive << ( numReps_out5_full_n );
    sensitive << ( in_V_offset_out_full_n );
    sensitive << ( out_V_offset_out_full_n );

    SC_METHOD(thread_numReps_out_blk_n);
    sensitive << ( ap_CS_fsm_state1 );
    sensitive << ( numReps_out_full_n );

    SC_METHOD(thread_numReps_out_din);
    sensitive << ( real_start );
    sensitive << ( ap_done_reg );
    sensitive << ( ap_CS_fsm_state1 );
    sensitive << ( numReps );
    sensitive << ( numReps_out_full_n );
    sensitive << ( numReps_out1_full_n );
    sensitive << ( numReps_out2_full_n );
    sensitive << ( numReps_out3_full_n );
    sensitive << ( numReps_out4_full_n );
    sensitive << ( numReps_out5_full_n );
    sensitive << ( in_V_offset_out_full_n );
    sensitive << ( out_V_offset_out_full_n );

    SC_METHOD(thread_numReps_out_write);
    sensitive << ( real_start );
    sensitive << ( ap_done_reg );
    sensitive << ( ap_CS_fsm_state1 );
    sensitive << ( numReps_out_full_n );
    sensitive << ( numReps_out1_full_n );
    sensitive << ( numReps_out2_full_n );
    sensitive << ( numReps_out3_full_n );
    sensitive << ( numReps_out4_full_n );
    sensitive << ( numReps_out5_full_n );
    sensitive << ( in_V_offset_out_full_n );
    sensitive << ( out_V_offset_out_full_n );

    SC_METHOD(thread_out_V_offset_out_blk_n);
    sensitive << ( ap_CS_fsm_state1 );
    sensitive << ( out_V_offset_out_full_n );

    SC_METHOD(thread_out_V_offset_out_din);
    sensitive << ( real_start );
    sensitive << ( ap_done_reg );
    sensitive << ( ap_CS_fsm_state1 );
    sensitive << ( numReps_out_full_n );
    sensitive << ( numReps_out1_full_n );
    sensitive << ( numReps_out2_full_n );
    sensitive << ( numReps_out3_full_n );
    sensitive << ( numReps_out4_full_n );
    sensitive << ( numReps_out5_full_n );
    sensitive << ( out_V_offset );
    sensitive << ( in_V_offset_out_full_n );
    sensitive << ( out_V_offset_out_full_n );

    SC_METHOD(thread_out_V_offset_out_write);
    sensitive << ( real_start );
    sensitive << ( ap_done_reg );
    sensitive << ( ap_CS_fsm_state1 );
    sensitive << ( numReps_out_full_n );
    sensitive << ( numReps_out1_full_n );
    sensitive << ( numReps_out2_full_n );
    sensitive << ( numReps_out3_full_n );
    sensitive << ( numReps_out4_full_n );
    sensitive << ( numReps_out5_full_n );
    sensitive << ( in_V_offset_out_full_n );
    sensitive << ( out_V_offset_out_full_n );

    SC_METHOD(thread_real_start);
    sensitive << ( ap_start );
    sensitive << ( start_full_n );
    sensitive << ( start_once_reg );

    SC_METHOD(thread_start_out);
    sensitive << ( real_start );

    SC_METHOD(thread_start_write);
    sensitive << ( real_start );
    sensitive << ( start_once_reg );

    SC_METHOD(thread_ap_NS_fsm);
    sensitive << ( real_start );
    sensitive << ( ap_done_reg );
    sensitive << ( ap_CS_fsm );
    sensitive << ( ap_CS_fsm_state1 );
    sensitive << ( numReps_out_full_n );
    sensitive << ( numReps_out1_full_n );
    sensitive << ( numReps_out2_full_n );
    sensitive << ( numReps_out3_full_n );
    sensitive << ( numReps_out4_full_n );
    sensitive << ( numReps_out5_full_n );
    sensitive << ( in_V_offset_out_full_n );
    sensitive << ( out_V_offset_out_full_n );

    start_once_reg = SC_LOGIC_0;
    ap_done_reg = SC_LOGIC_0;
    ap_CS_fsm = "1";
    static int apTFileNum = 0;
    stringstream apTFilenSS;
    apTFilenSS << "DoCompute_entry33612_sc_trace_" << apTFileNum ++;
    string apTFn = apTFilenSS.str();
    mVcdFile = sc_create_vcd_trace_file(apTFn.c_str());
    mVcdFile->set_time_unit(1, SC_PS);
    if (1) {
#ifdef __HLS_TRACE_LEVEL_PORT_HIER__
    sc_trace(mVcdFile, ap_clk, "(port)ap_clk");
    sc_trace(mVcdFile, ap_rst, "(port)ap_rst");
    sc_trace(mVcdFile, ap_start, "(port)ap_start");
    sc_trace(mVcdFile, start_full_n, "(port)start_full_n");
    sc_trace(mVcdFile, ap_done, "(port)ap_done");
    sc_trace(mVcdFile, ap_continue, "(port)ap_continue");
    sc_trace(mVcdFile, ap_idle, "(port)ap_idle");
    sc_trace(mVcdFile, ap_ready, "(port)ap_ready");
    sc_trace(mVcdFile, start_out, "(port)start_out");
    sc_trace(mVcdFile, start_write, "(port)start_write");
    sc_trace(mVcdFile, numReps, "(port)numReps");
    sc_trace(mVcdFile, numReps_out_din, "(port)numReps_out_din");
    sc_trace(mVcdFile, numReps_out_full_n, "(port)numReps_out_full_n");
    sc_trace(mVcdFile, numReps_out_write, "(port)numReps_out_write");
    sc_trace(mVcdFile, numReps_out1_din, "(port)numReps_out1_din");
    sc_trace(mVcdFile, numReps_out1_full_n, "(port)numReps_out1_full_n");
    sc_trace(mVcdFile, numReps_out1_write, "(port)numReps_out1_write");
    sc_trace(mVcdFile, numReps_out2_din, "(port)numReps_out2_din");
    sc_trace(mVcdFile, numReps_out2_full_n, "(port)numReps_out2_full_n");
    sc_trace(mVcdFile, numReps_out2_write, "(port)numReps_out2_write");
    sc_trace(mVcdFile, numReps_out3_din, "(port)numReps_out3_din");
    sc_trace(mVcdFile, numReps_out3_full_n, "(port)numReps_out3_full_n");
    sc_trace(mVcdFile, numReps_out3_write, "(port)numReps_out3_write");
    sc_trace(mVcdFile, numReps_out4_din, "(port)numReps_out4_din");
    sc_trace(mVcdFile, numReps_out4_full_n, "(port)numReps_out4_full_n");
    sc_trace(mVcdFile, numReps_out4_write, "(port)numReps_out4_write");
    sc_trace(mVcdFile, numReps_out5_din, "(port)numReps_out5_din");
    sc_trace(mVcdFile, numReps_out5_full_n, "(port)numReps_out5_full_n");
    sc_trace(mVcdFile, numReps_out5_write, "(port)numReps_out5_write");
    sc_trace(mVcdFile, in_V_offset, "(port)in_V_offset");
    sc_trace(mVcdFile, out_V_offset, "(port)out_V_offset");
    sc_trace(mVcdFile, in_V_offset_out_din, "(port)in_V_offset_out_din");
    sc_trace(mVcdFile, in_V_offset_out_full_n, "(port)in_V_offset_out_full_n");
    sc_trace(mVcdFile, in_V_offset_out_write, "(port)in_V_offset_out_write");
    sc_trace(mVcdFile, out_V_offset_out_din, "(port)out_V_offset_out_din");
    sc_trace(mVcdFile, out_V_offset_out_full_n, "(port)out_V_offset_out_full_n");
    sc_trace(mVcdFile, out_V_offset_out_write, "(port)out_V_offset_out_write");
#endif
#ifdef __HLS_TRACE_LEVEL_INT__
    sc_trace(mVcdFile, real_start, "real_start");
    sc_trace(mVcdFile, start_once_reg, "start_once_reg");
    sc_trace(mVcdFile, ap_done_reg, "ap_done_reg");
    sc_trace(mVcdFile, ap_CS_fsm, "ap_CS_fsm");
    sc_trace(mVcdFile, ap_CS_fsm_state1, "ap_CS_fsm_state1");
    sc_trace(mVcdFile, internal_ap_ready, "internal_ap_ready");
    sc_trace(mVcdFile, numReps_out_blk_n, "numReps_out_blk_n");
    sc_trace(mVcdFile, numReps_out1_blk_n, "numReps_out1_blk_n");
    sc_trace(mVcdFile, numReps_out2_blk_n, "numReps_out2_blk_n");
    sc_trace(mVcdFile, numReps_out3_blk_n, "numReps_out3_blk_n");
    sc_trace(mVcdFile, numReps_out4_blk_n, "numReps_out4_blk_n");
    sc_trace(mVcdFile, numReps_out5_blk_n, "numReps_out5_blk_n");
    sc_trace(mVcdFile, in_V_offset_out_blk_n, "in_V_offset_out_blk_n");
    sc_trace(mVcdFile, out_V_offset_out_blk_n, "out_V_offset_out_blk_n");
    sc_trace(mVcdFile, ap_block_state1, "ap_block_state1");
    sc_trace(mVcdFile, ap_NS_fsm, "ap_NS_fsm");
#endif

    }
}

DoCompute_entry33612::~DoCompute_entry33612() {
    if (mVcdFile) 
        sc_close_vcd_trace_file(mVcdFile);

}

void DoCompute_entry33612::thread_ap_clk_no_reset_() {
    if ( ap_rst.read() == ap_const_logic_1) {
        ap_CS_fsm = ap_ST_fsm_state1;
    } else {
        ap_CS_fsm = ap_NS_fsm.read();
    }
    if ( ap_rst.read() == ap_const_logic_1) {
        ap_done_reg = ap_const_logic_0;
    } else {
        if (esl_seteq<1,1,1>(ap_const_logic_1, ap_continue.read())) {
            ap_done_reg = ap_const_logic_0;
        } else if ((!(esl_seteq<1,1,1>(out_V_offset_out_full_n.read(), ap_const_logic_0) || esl_seteq<1,1,1>(real_start.read(), ap_const_logic_0) || esl_seteq<1,1,1>(in_V_offset_out_full_n.read(), ap_const_logic_0) || esl_seteq<1,1,1>(numReps_out5_full_n.read(), ap_const_logic_0) || esl_seteq<1,1,1>(numReps_out4_full_n.read(), ap_const_logic_0) || esl_seteq<1,1,1>(numReps_out3_full_n.read(), ap_const_logic_0) || esl_seteq<1,1,1>(numReps_out2_full_n.read(), ap_const_logic_0) || esl_seteq<1,1,1>(numReps_out1_full_n.read(), ap_const_logic_0) || esl_seteq<1,1,1>(numReps_out_full_n.read(), ap_const_logic_0) || esl_seteq<1,1,1>(ap_done_reg.read(), ap_const_logic_1)) && 
                    esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state1.read()))) {
            ap_done_reg = ap_const_logic_1;
        }
    }
    if ( ap_rst.read() == ap_const_logic_1) {
        start_once_reg = ap_const_logic_0;
    } else {
        if ((esl_seteq<1,1,1>(ap_const_logic_1, real_start.read()) && 
             esl_seteq<1,1,1>(ap_const_logic_0, internal_ap_ready.read()))) {
            start_once_reg = ap_const_logic_1;
        } else if (esl_seteq<1,1,1>(ap_const_logic_1, internal_ap_ready.read())) {
            start_once_reg = ap_const_logic_0;
        }
    }
}

void DoCompute_entry33612::thread_ap_CS_fsm_state1() {
    ap_CS_fsm_state1 = ap_CS_fsm.read()[0];
}

void DoCompute_entry33612::thread_ap_block_state1() {
    ap_block_state1 = (esl_seteq<1,1,1>(out_V_offset_out_full_n.read(), ap_const_logic_0) || esl_seteq<1,1,1>(real_start.read(), ap_const_logic_0) || esl_seteq<1,1,1>(in_V_offset_out_full_n.read(), ap_const_logic_0) || esl_seteq<1,1,1>(numReps_out5_full_n.read(), ap_const_logic_0) || esl_seteq<1,1,1>(numReps_out4_full_n.read(), ap_const_logic_0) || esl_seteq<1,1,1>(numReps_out3_full_n.read(), ap_const_logic_0) || esl_seteq<1,1,1>(numReps_out2_full_n.read(), ap_const_logic_0) || esl_seteq<1,1,1>(numReps_out1_full_n.read(), ap_const_logic_0) || esl_seteq<1,1,1>(numReps_out_full_n.read(), ap_const_logic_0) || esl_seteq<1,1,1>(ap_done_reg.read(), ap_const_logic_1));
}

void DoCompute_entry33612::thread_ap_done() {
    if ((!(esl_seteq<1,1,1>(out_V_offset_out_full_n.read(), ap_const_logic_0) || esl_seteq<1,1,1>(real_start.read(), ap_const_logic_0) || esl_seteq<1,1,1>(in_V_offset_out_full_n.read(), ap_const_logic_0) || esl_seteq<1,1,1>(numReps_out5_full_n.read(), ap_const_logic_0) || esl_seteq<1,1,1>(numReps_out4_full_n.read(), ap_const_logic_0) || esl_seteq<1,1,1>(numReps_out3_full_n.read(), ap_const_logic_0) || esl_seteq<1,1,1>(numReps_out2_full_n.read(), ap_const_logic_0) || esl_seteq<1,1,1>(numReps_out1_full_n.read(), ap_const_logic_0) || esl_seteq<1,1,1>(numReps_out_full_n.read(), ap_const_logic_0) || esl_seteq<1,1,1>(ap_done_reg.read(), ap_const_logic_1)) && 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state1.read()))) {
        ap_done = ap_const_logic_1;
    } else {
        ap_done = ap_done_reg.read();
    }
}

void DoCompute_entry33612::thread_ap_idle() {
    if ((esl_seteq<1,1,1>(real_start.read(), ap_const_logic_0) && 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state1.read()))) {
        ap_idle = ap_const_logic_1;
    } else {
        ap_idle = ap_const_logic_0;
    }
}

void DoCompute_entry33612::thread_ap_ready() {
    ap_ready = internal_ap_ready.read();
}

void DoCompute_entry33612::thread_in_V_offset_out_blk_n() {
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state1.read())) {
        in_V_offset_out_blk_n = in_V_offset_out_full_n.read();
    } else {
        in_V_offset_out_blk_n = ap_const_logic_1;
    }
}

void DoCompute_entry33612::thread_in_V_offset_out_din() {
    in_V_offset_out_din = in_V_offset.read();
}

void DoCompute_entry33612::thread_in_V_offset_out_write() {
    if ((!(esl_seteq<1,1,1>(out_V_offset_out_full_n.read(), ap_const_logic_0) || esl_seteq<1,1,1>(real_start.read(), ap_const_logic_0) || esl_seteq<1,1,1>(in_V_offset_out_full_n.read(), ap_const_logic_0) || esl_seteq<1,1,1>(numReps_out5_full_n.read(), ap_const_logic_0) || esl_seteq<1,1,1>(numReps_out4_full_n.read(), ap_const_logic_0) || esl_seteq<1,1,1>(numReps_out3_full_n.read(), ap_const_logic_0) || esl_seteq<1,1,1>(numReps_out2_full_n.read(), ap_const_logic_0) || esl_seteq<1,1,1>(numReps_out1_full_n.read(), ap_const_logic_0) || esl_seteq<1,1,1>(numReps_out_full_n.read(), ap_const_logic_0) || esl_seteq<1,1,1>(ap_done_reg.read(), ap_const_logic_1)) && 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state1.read()))) {
        in_V_offset_out_write = ap_const_logic_1;
    } else {
        in_V_offset_out_write = ap_const_logic_0;
    }
}

void DoCompute_entry33612::thread_internal_ap_ready() {
    if ((!(esl_seteq<1,1,1>(out_V_offset_out_full_n.read(), ap_const_logic_0) || esl_seteq<1,1,1>(real_start.read(), ap_const_logic_0) || esl_seteq<1,1,1>(in_V_offset_out_full_n.read(), ap_const_logic_0) || esl_seteq<1,1,1>(numReps_out5_full_n.read(), ap_const_logic_0) || esl_seteq<1,1,1>(numReps_out4_full_n.read(), ap_const_logic_0) || esl_seteq<1,1,1>(numReps_out3_full_n.read(), ap_const_logic_0) || esl_seteq<1,1,1>(numReps_out2_full_n.read(), ap_const_logic_0) || esl_seteq<1,1,1>(numReps_out1_full_n.read(), ap_const_logic_0) || esl_seteq<1,1,1>(numReps_out_full_n.read(), ap_const_logic_0) || esl_seteq<1,1,1>(ap_done_reg.read(), ap_const_logic_1)) && 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state1.read()))) {
        internal_ap_ready = ap_const_logic_1;
    } else {
        internal_ap_ready = ap_const_logic_0;
    }
}

void DoCompute_entry33612::thread_numReps_out1_blk_n() {
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state1.read())) {
        numReps_out1_blk_n = numReps_out1_full_n.read();
    } else {
        numReps_out1_blk_n = ap_const_logic_1;
    }
}

void DoCompute_entry33612::thread_numReps_out1_din() {
    numReps_out1_din = numReps.read();
}

void DoCompute_entry33612::thread_numReps_out1_write() {
    if ((!(esl_seteq<1,1,1>(out_V_offset_out_full_n.read(), ap_const_logic_0) || esl_seteq<1,1,1>(real_start.read(), ap_const_logic_0) || esl_seteq<1,1,1>(in_V_offset_out_full_n.read(), ap_const_logic_0) || esl_seteq<1,1,1>(numReps_out5_full_n.read(), ap_const_logic_0) || esl_seteq<1,1,1>(numReps_out4_full_n.read(), ap_const_logic_0) || esl_seteq<1,1,1>(numReps_out3_full_n.read(), ap_const_logic_0) || esl_seteq<1,1,1>(numReps_out2_full_n.read(), ap_const_logic_0) || esl_seteq<1,1,1>(numReps_out1_full_n.read(), ap_const_logic_0) || esl_seteq<1,1,1>(numReps_out_full_n.read(), ap_const_logic_0) || esl_seteq<1,1,1>(ap_done_reg.read(), ap_const_logic_1)) && 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state1.read()))) {
        numReps_out1_write = ap_const_logic_1;
    } else {
        numReps_out1_write = ap_const_logic_0;
    }
}

void DoCompute_entry33612::thread_numReps_out2_blk_n() {
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state1.read())) {
        numReps_out2_blk_n = numReps_out2_full_n.read();
    } else {
        numReps_out2_blk_n = ap_const_logic_1;
    }
}

void DoCompute_entry33612::thread_numReps_out2_din() {
    numReps_out2_din = numReps.read();
}

void DoCompute_entry33612::thread_numReps_out2_write() {
    if ((!(esl_seteq<1,1,1>(out_V_offset_out_full_n.read(), ap_const_logic_0) || esl_seteq<1,1,1>(real_start.read(), ap_const_logic_0) || esl_seteq<1,1,1>(in_V_offset_out_full_n.read(), ap_const_logic_0) || esl_seteq<1,1,1>(numReps_out5_full_n.read(), ap_const_logic_0) || esl_seteq<1,1,1>(numReps_out4_full_n.read(), ap_const_logic_0) || esl_seteq<1,1,1>(numReps_out3_full_n.read(), ap_const_logic_0) || esl_seteq<1,1,1>(numReps_out2_full_n.read(), ap_const_logic_0) || esl_seteq<1,1,1>(numReps_out1_full_n.read(), ap_const_logic_0) || esl_seteq<1,1,1>(numReps_out_full_n.read(), ap_const_logic_0) || esl_seteq<1,1,1>(ap_done_reg.read(), ap_const_logic_1)) && 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state1.read()))) {
        numReps_out2_write = ap_const_logic_1;
    } else {
        numReps_out2_write = ap_const_logic_0;
    }
}

void DoCompute_entry33612::thread_numReps_out3_blk_n() {
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state1.read())) {
        numReps_out3_blk_n = numReps_out3_full_n.read();
    } else {
        numReps_out3_blk_n = ap_const_logic_1;
    }
}

void DoCompute_entry33612::thread_numReps_out3_din() {
    numReps_out3_din = numReps.read();
}

void DoCompute_entry33612::thread_numReps_out3_write() {
    if ((!(esl_seteq<1,1,1>(out_V_offset_out_full_n.read(), ap_const_logic_0) || esl_seteq<1,1,1>(real_start.read(), ap_const_logic_0) || esl_seteq<1,1,1>(in_V_offset_out_full_n.read(), ap_const_logic_0) || esl_seteq<1,1,1>(numReps_out5_full_n.read(), ap_const_logic_0) || esl_seteq<1,1,1>(numReps_out4_full_n.read(), ap_const_logic_0) || esl_seteq<1,1,1>(numReps_out3_full_n.read(), ap_const_logic_0) || esl_seteq<1,1,1>(numReps_out2_full_n.read(), ap_const_logic_0) || esl_seteq<1,1,1>(numReps_out1_full_n.read(), ap_const_logic_0) || esl_seteq<1,1,1>(numReps_out_full_n.read(), ap_const_logic_0) || esl_seteq<1,1,1>(ap_done_reg.read(), ap_const_logic_1)) && 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state1.read()))) {
        numReps_out3_write = ap_const_logic_1;
    } else {
        numReps_out3_write = ap_const_logic_0;
    }
}

void DoCompute_entry33612::thread_numReps_out4_blk_n() {
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state1.read())) {
        numReps_out4_blk_n = numReps_out4_full_n.read();
    } else {
        numReps_out4_blk_n = ap_const_logic_1;
    }
}

void DoCompute_entry33612::thread_numReps_out4_din() {
    numReps_out4_din = numReps.read();
}

void DoCompute_entry33612::thread_numReps_out4_write() {
    if ((!(esl_seteq<1,1,1>(out_V_offset_out_full_n.read(), ap_const_logic_0) || esl_seteq<1,1,1>(real_start.read(), ap_const_logic_0) || esl_seteq<1,1,1>(in_V_offset_out_full_n.read(), ap_const_logic_0) || esl_seteq<1,1,1>(numReps_out5_full_n.read(), ap_const_logic_0) || esl_seteq<1,1,1>(numReps_out4_full_n.read(), ap_const_logic_0) || esl_seteq<1,1,1>(numReps_out3_full_n.read(), ap_const_logic_0) || esl_seteq<1,1,1>(numReps_out2_full_n.read(), ap_const_logic_0) || esl_seteq<1,1,1>(numReps_out1_full_n.read(), ap_const_logic_0) || esl_seteq<1,1,1>(numReps_out_full_n.read(), ap_const_logic_0) || esl_seteq<1,1,1>(ap_done_reg.read(), ap_const_logic_1)) && 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state1.read()))) {
        numReps_out4_write = ap_const_logic_1;
    } else {
        numReps_out4_write = ap_const_logic_0;
    }
}

void DoCompute_entry33612::thread_numReps_out5_blk_n() {
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state1.read())) {
        numReps_out5_blk_n = numReps_out5_full_n.read();
    } else {
        numReps_out5_blk_n = ap_const_logic_1;
    }
}

void DoCompute_entry33612::thread_numReps_out5_din() {
    numReps_out5_din = numReps.read();
}

void DoCompute_entry33612::thread_numReps_out5_write() {
    if ((!(esl_seteq<1,1,1>(out_V_offset_out_full_n.read(), ap_const_logic_0) || esl_seteq<1,1,1>(real_start.read(), ap_const_logic_0) || esl_seteq<1,1,1>(in_V_offset_out_full_n.read(), ap_const_logic_0) || esl_seteq<1,1,1>(numReps_out5_full_n.read(), ap_const_logic_0) || esl_seteq<1,1,1>(numReps_out4_full_n.read(), ap_const_logic_0) || esl_seteq<1,1,1>(numReps_out3_full_n.read(), ap_const_logic_0) || esl_seteq<1,1,1>(numReps_out2_full_n.read(), ap_const_logic_0) || esl_seteq<1,1,1>(numReps_out1_full_n.read(), ap_const_logic_0) || esl_seteq<1,1,1>(numReps_out_full_n.read(), ap_const_logic_0) || esl_seteq<1,1,1>(ap_done_reg.read(), ap_const_logic_1)) && 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state1.read()))) {
        numReps_out5_write = ap_const_logic_1;
    } else {
        numReps_out5_write = ap_const_logic_0;
    }
}

void DoCompute_entry33612::thread_numReps_out_blk_n() {
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state1.read())) {
        numReps_out_blk_n = numReps_out_full_n.read();
    } else {
        numReps_out_blk_n = ap_const_logic_1;
    }
}

void DoCompute_entry33612::thread_numReps_out_din() {
    numReps_out_din = numReps.read();
}

void DoCompute_entry33612::thread_numReps_out_write() {
    if ((!(esl_seteq<1,1,1>(out_V_offset_out_full_n.read(), ap_const_logic_0) || esl_seteq<1,1,1>(real_start.read(), ap_const_logic_0) || esl_seteq<1,1,1>(in_V_offset_out_full_n.read(), ap_const_logic_0) || esl_seteq<1,1,1>(numReps_out5_full_n.read(), ap_const_logic_0) || esl_seteq<1,1,1>(numReps_out4_full_n.read(), ap_const_logic_0) || esl_seteq<1,1,1>(numReps_out3_full_n.read(), ap_const_logic_0) || esl_seteq<1,1,1>(numReps_out2_full_n.read(), ap_const_logic_0) || esl_seteq<1,1,1>(numReps_out1_full_n.read(), ap_const_logic_0) || esl_seteq<1,1,1>(numReps_out_full_n.read(), ap_const_logic_0) || esl_seteq<1,1,1>(ap_done_reg.read(), ap_const_logic_1)) && 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state1.read()))) {
        numReps_out_write = ap_const_logic_1;
    } else {
        numReps_out_write = ap_const_logic_0;
    }
}

void DoCompute_entry33612::thread_out_V_offset_out_blk_n() {
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state1.read())) {
        out_V_offset_out_blk_n = out_V_offset_out_full_n.read();
    } else {
        out_V_offset_out_blk_n = ap_const_logic_1;
    }
}

void DoCompute_entry33612::thread_out_V_offset_out_din() {
    out_V_offset_out_din = out_V_offset.read();
}

void DoCompute_entry33612::thread_out_V_offset_out_write() {
    if ((!(esl_seteq<1,1,1>(out_V_offset_out_full_n.read(), ap_const_logic_0) || esl_seteq<1,1,1>(real_start.read(), ap_const_logic_0) || esl_seteq<1,1,1>(in_V_offset_out_full_n.read(), ap_const_logic_0) || esl_seteq<1,1,1>(numReps_out5_full_n.read(), ap_const_logic_0) || esl_seteq<1,1,1>(numReps_out4_full_n.read(), ap_const_logic_0) || esl_seteq<1,1,1>(numReps_out3_full_n.read(), ap_const_logic_0) || esl_seteq<1,1,1>(numReps_out2_full_n.read(), ap_const_logic_0) || esl_seteq<1,1,1>(numReps_out1_full_n.read(), ap_const_logic_0) || esl_seteq<1,1,1>(numReps_out_full_n.read(), ap_const_logic_0) || esl_seteq<1,1,1>(ap_done_reg.read(), ap_const_logic_1)) && 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state1.read()))) {
        out_V_offset_out_write = ap_const_logic_1;
    } else {
        out_V_offset_out_write = ap_const_logic_0;
    }
}

void DoCompute_entry33612::thread_real_start() {
    if ((esl_seteq<1,1,1>(ap_const_logic_0, start_full_n.read()) && 
         esl_seteq<1,1,1>(ap_const_logic_0, start_once_reg.read()))) {
        real_start = ap_const_logic_0;
    } else {
        real_start = ap_start.read();
    }
}

void DoCompute_entry33612::thread_start_out() {
    start_out = real_start.read();
}

void DoCompute_entry33612::thread_start_write() {
    if ((esl_seteq<1,1,1>(ap_const_logic_0, start_once_reg.read()) && 
         esl_seteq<1,1,1>(ap_const_logic_1, real_start.read()))) {
        start_write = ap_const_logic_1;
    } else {
        start_write = ap_const_logic_0;
    }
}

void DoCompute_entry33612::thread_ap_NS_fsm() {
    switch (ap_CS_fsm.read().to_uint64()) {
        case 1 : 
            ap_NS_fsm = ap_ST_fsm_state1;
break;
        default : 
            ap_NS_fsm = "X";
            break;
    }
}

}

