# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: c:/Users/danielellerbrock/Documents/vivado_projects/BNN-PYNQ/bnn/src/network/output/vivado/cnvW1A1-pynqZ1-Z2/cnvW1A1-pynqZ1-Z2.srcs/sources_1/bd/procsys/ip/procsys_axi_iic_0_0/procsys_axi_iic_0_0.xci
# IP: The module: 'procsys_axi_iic_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/danielellerbrock/Documents/vivado_projects/BNN-PYNQ/bnn/src/network/output/vivado/cnvW1A1-pynqZ1-Z2/cnvW1A1-pynqZ1-Z2.srcs/sources_1/bd/procsys/ip/procsys_axi_iic_0_0/procsys_axi_iic_0_0_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'procsys_axi_iic_0_0'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# XDC: c:/Users/danielellerbrock/Documents/vivado_projects/BNN-PYNQ/bnn/src/network/output/vivado/cnvW1A1-pynqZ1-Z2/cnvW1A1-pynqZ1-Z2.srcs/sources_1/bd/procsys/ip/procsys_axi_iic_0_0/procsys_axi_iic_0_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'procsys_axi_iic_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# IP: c:/Users/danielellerbrock/Documents/vivado_projects/BNN-PYNQ/bnn/src/network/output/vivado/cnvW1A1-pynqZ1-Z2/cnvW1A1-pynqZ1-Z2.srcs/sources_1/bd/procsys/ip/procsys_axi_iic_0_0/procsys_axi_iic_0_0.xci
# IP: The module: 'procsys_axi_iic_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/danielellerbrock/Documents/vivado_projects/BNN-PYNQ/bnn/src/network/output/vivado/cnvW1A1-pynqZ1-Z2/cnvW1A1-pynqZ1-Z2.srcs/sources_1/bd/procsys/ip/procsys_axi_iic_0_0/procsys_axi_iic_0_0_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'procsys_axi_iic_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# XDC: c:/Users/danielellerbrock/Documents/vivado_projects/BNN-PYNQ/bnn/src/network/output/vivado/cnvW1A1-pynqZ1-Z2/cnvW1A1-pynqZ1-Z2.srcs/sources_1/bd/procsys/ip/procsys_axi_iic_0_0/procsys_axi_iic_0_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'procsys_axi_iic_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet
