# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: C:/Users/danielellerbrock/Documents/vivado_projects/BNN-PYNQ/bnn/src/library/script/pynqZ1-Z2/pynqZ1-Z2.xdc

# Block Designs: bd/procsys/procsys.bd
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==procsys || ORIG_REF_NAME==procsys} -quiet] -quiet

# IP: bd/procsys/ip/procsys_ps7_0/procsys_ps7_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==procsys_ps7_0 || ORIG_REF_NAME==procsys_ps7_0} -quiet] -quiet

# IP: bd/procsys/ip/procsys_BlackBoxJam_0_0/procsys_BlackBoxJam_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==procsys_BlackBoxJam_0_0 || ORIG_REF_NAME==procsys_BlackBoxJam_0_0} -quiet] -quiet

# IP: bd/procsys/ip/procsys_axi_mem_intercon_0/procsys_axi_mem_intercon_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==procsys_axi_mem_intercon_0 || ORIG_REF_NAME==procsys_axi_mem_intercon_0} -quiet] -quiet

# IP: bd/procsys/ip/procsys_ps7_axi_periph_0/procsys_ps7_axi_periph_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==procsys_ps7_axi_periph_0 || ORIG_REF_NAME==procsys_ps7_axi_periph_0} -quiet] -quiet

# IP: bd/procsys/ip/procsys_rst_ps7_100M_0/procsys_rst_ps7_100M_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==procsys_rst_ps7_100M_0 || ORIG_REF_NAME==procsys_rst_ps7_100M_0} -quiet] -quiet

# IP: bd/procsys/ip/procsys_xbar_0/procsys_xbar_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==procsys_xbar_0 || ORIG_REF_NAME==procsys_xbar_0} -quiet] -quiet

# IP: bd/procsys/ip/procsys_axi_iic_0_0/procsys_axi_iic_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==procsys_axi_iic_0_0 || ORIG_REF_NAME==procsys_axi_iic_0_0} -quiet] -quiet

# IP: bd/procsys/ip/procsys_auto_pc_0/procsys_auto_pc_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==procsys_auto_pc_0 || ORIG_REF_NAME==procsys_auto_pc_0} -quiet] -quiet

# IP: bd/procsys/ip/procsys_auto_pc_1/procsys_auto_pc_1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==procsys_auto_pc_1 || ORIG_REF_NAME==procsys_auto_pc_1} -quiet] -quiet

# XDC: bd/procsys/procsys_ooc.xdc
